<form action="<?= current_url();?>" method="post">
    <input type="hidden" name="id" value="<?= $taxonomies->id; ?>">
    <div class="card">
        <h5 class="card-header d-flex justify-content-between align-items-center">
            <?php echo $page->title; ?>

            <div class="card-options">
                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                    CANCEL
                </button>
                <button type="submit" class="btn btn-primary btn-md">
                    SAVE
                </button>
            </div>
        </h5>
    </div>

    <div class="card">
        <div class="card-body">                       
            <!-- <div class="form-group">
                <label>Parent</label>
                <select name="record_status" class="form-control">
                    <option value="">

                    </option>
                </select>
            </div>   -->
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="name" type="text" value="<?= $taxonomies->name; ?>" required="">
            </div>
            <div class="form-group">
                <label>Slug</label>
                <input class="form-control" name="slug" type="text" value="<?= $taxonomies->slug; ?>" required="">
            </div>  
            <div class="form-group">
                <label>Code</label>
                <input class="form-control" name="code" type="text" value="<?= $taxonomies->code; ?>" required="">
            </div>
            <div class="form-group">
                <label>Description</label>
                <textarea name="description" class="form-control"><?= $taxonomies->description; ?></textarea>
            </div>

        </div>
    </div>
</form>