<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h3 class="mb-4">Detail Taxonomies</h3>
                    </div>
                </div>

                <div class="card">
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Parent</th>
                                    <td><?= $taxonomies->title; ?></td>
                                </tr>
                                <tr>
                                    <th>Name</th>
                                    <td><?= $taxonomies->name; ?></td>
                                </tr>
                                <tr>
                                    <th>Slug</th>
                                    <td><?= $taxonomies->slug; ?></td>
                                </tr>
                                <tr>
                                    <th>Code</th>
                                    <td><?= $taxonomies->code; ?></td>
                                </tr>
                                <tr>
                                    <th>Description</th>
                                    <td><?= $taxonomies->description; ?></td>
                                </tr>
                                <tr>
                                    <th>Date Created</th>
                                    <td><?= $taxonomies->record_create_timestamp; ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <?php //echo view('components/pagination', [], true); ?>
                
            </div>
        </div>
    </div>
</div>