<div class="container-fluid">
    <form id="form-data" method="post" action="<?php echo current_url() ?>" enctype="multipart/form-data">
        <?php if ($post->id): ?>
            <input type="hidden" name="id" value="<?= $post->id ?>">
        <?php endif; ?>
        <div class="card">
            <h5 class="card-header d-flex justify-content-between align-items-center">
                <?php echo $page->title; ?>

                <div class="card-options">
                    <button type="button" class="btn btn-default btn-md" data-action="cancel">
                        <?php echo $language->getLine('BTN_CANCEL'); ?>
                    </button>
                    <button type="submit" class="btn btn-primary btn-md">
                        <?php echo $language->getLine('BTN_SAVE'); ?>
                    </button>
                </div>
            </h5>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <h6 class="card-header">
                        Title
                    </h6>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <input class="form-control" type="text" name="title" value="<?= $post->title ?>">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-link"></i>
                                        </span>
                                    </div>
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <?php echo domain_url(null, null, null);?>
                                        </span>
                                    </div>
                                    <input class="form-control" name="slug" value="<?= $post->slug ?>" <?= ($post->slug ? 'readonly' : '') ?> type="text">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <h6 class="card-header">
                        Content
                    </h6>
                    <div class="card-body p-0 post-editor">
                        <div class="form-group row mb-0">
                            <div class="col-md-12">
                                <textarea class="form-control tinymce" name="content"><?= $post->content ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        Image
                    </div>
                    <div class="card-body p-0">
                        <!-- <div id="dropzone-cards" data-action-url="http://8080" data-allowed="image/*" data-max-files="" data-max-size="">
                            <div class="media-list">
                                <div class="dropzone-form" id="dropzone-cards-form" style="cursor: pointer;">
                                    <div class="dz-message needsclick">
                                        <p>Drop files here or click to upload.<br>
                                            <span class="note needsclick">
                                                (This is just a demo dropzone. Selected files are
                                                <strong>not</strong> actually uploaded.)
                                            </span>
                                        </p>
                                    </div>
                                    <div class="dropzone-previews" id="dropzone-previews">
                                        <div class="dz-template" id="dropzone-cards-template">
                                            <div class="media-list-item uploading">
                                                <div class="media-list-action d-flex">
                                                    <button type="button" class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal"
                                                        data-target="#modal-edit">Edit</button>
                                                    <button type="button" class="btn btn-danger btn-xs">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </div>
                                                
                                                <input type="checkbox" id="media-1">
                                                <label class="media-item" for="media-1">
                                                    <img data-dz-thumbnail>
                                                    <div class="media-item-file-details">
                                                        <div class="media-item-icon">
                                                            <i class="fas fa-file-powerpoint"></i>
                                                        </div>
                                                        <div class="media-item-file-name" data-dz-name></div>
                                                        <div class="media-item-file-extension"></div>
                                                    </div>
                                                </label>
        
                                                <div class="upload-progress">
                                                    <div class="progress">
                                                        <div class="progress-bar progress-bar-striped progress-bar-animated"
                                                            role="progressbar" aria-valuenow="75" aria-valuemin="0"
                                                            aria-valuemax="100" style="width: 0%" data-dz-uploadprogress></div>
                                                    </div>
                                                </div>
        
                                                <div class="media-item-file-error">
                                                    <div class="media-item-icon-error">
                                                        <i class="fas fa-exclamation-circle"></i>
                                                    </div>
                                                    <div class="media-item-file-name-error" data-dz-errormessage></div>
                                                    <div class="media-item-file-extension-error d-flex justify-content-center">
                                                        <button type="button" class="btn btn-outline-light btn-sm"
                                                            data-dz-remove>
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
        
                                    </div>
                                </div>
                            </div>
                        </div> -->
                        <input type="file" name="photo" class="dropify" data-default-file="<?= $post->image ?>">
                    </div>
                </div>

                <div class="card mb-2">
                    <div class="card-header">
                        Search Engine Optimization
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-md-3">Metarobot</label>
                            <div class="col-md-9">
                                <input class="form-control" name="meta[metarobot]" value="<?= ($post->metadata ? ($post->metadata->metarobot ? $post->metadata->metarobot : '') : '') ?>" type="text">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Metatitle</label>
                            <div class="col-md-9">
                                <input class="form-control" name="meta[metatitle]" value="<?= ($post->metadata ? ($post->metadata->metatitle ? $post->metadata->metatitle : '') : '') ?>" type="text">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Metadescription</label>
                            <div class="col-md-9">
                                <textarea class="form-control" cols="5" name="meta[metadescription]"><?= ($post->metadata ? ($post->metadata->metadescription ? $post->metadata->metadescription : '') : '') ?></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Metakeywords</label>
                            <div class="col-md-9">
                                <input class="tagsinput form-control" data-role="tagsinput" name="meta[metakeywords]" value="<?= ($post->metadata ? ($post->metadata->metakeywords ? $post->metadata->metakeywords : '') : '') ?>" type="text">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label>Language</label>
                            <select class="custom-select form-control" name="settings[language]">
                                <?php foreach ($world_languages as $key => $value): ?>
                                    <option value="<?= $key ?>" <?= ($post->settings ? ($post->settings->language == $key ? 'selected' : '') : '') ?>><?= $value ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <!-- <div class="form-group">
                            <label>Format</label>
                            <select class="custom-select form-control" name="settings[format]">
                                <option>Post</option>
                            </select>
                        </div> -->
                        <div class="form-group">
                            <label>Status</label>
                            <select class="custom-select form-control" name="record_status">
                                <?php foreach ($status as $key => $value): ?>
                                    <option value="<?= $key ?>" <?= ($post->record ? ($post->record->status == $key ? 'selected' : '') : '') ?>><?= $value ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Visibility</label>
                            <select class="custom-select form-control" name="visibility">
                                <?php if ($visibility): ?>
                                    <?php foreach ($visibility as $key => $value): ?>
                                        <option value="<?= $key ?>" <?= $post->visibility == $key ? 'selected' : '' ?>><?= $value ?></option>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">Publishing</h6>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Start Publishing</label>
                            <input type="datetime-local" name="settings[publish_start]" class="form-control" value="<?= ($post->start_publishing ? date('Y-m-d\TH:i:s', strtotime($post->start_publishing)) : '')  ?>">
                        </div>
                        <div class="form-group">
                            <label>Finish Publishing</label>
                            <input type="datetime-local" name="settings[publish_finish]" class="form-control" value="<?= ($post->finish_publishing ? date('Y-m-d\TH:i:s', strtotime($post->finish_publishing)) : '')  ?>">
                        </div>
                    </div>
                </div>

                <!-- <div class="card">
                    <h6 class="card-header">
                        Categories
                    </h6>
                    <div class="card-body">
                        <div class="form-group">
                            <select class="form-control custom-select selectize-single" name="" placeholder="Select or Add">
                                <option value="" selected>Test</option>
                                <option>First</option>
                                <option>Second</option>
                                <option>Third</option>
                            </select>
                        </div>
                    </div>
                </div> -->

                <!-- <div class="card">
                    <h6 class="card-header">
                        Tags
                    </h6>
                    <div class="card-body">
                        <div class="form-group mb-0">
                            <input type="text" name="tags[name]" data-role="tagsinput" value="<?= ($post->tag ? $post->tag->name : '') ?>" />
                        </div>
                    </div>
                </div> -->

                <div class="card">
                    <h6 class="card-header">Sharing</h6>
                    <div class="card-body">
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Show sharing buttons</label>
                            <label class="switch">
                                <input type="hidden" name="settings[sharing_button]" value="off" />
                                <input type="checkbox" <?= ($post->settings ? ($post->settings->sharing_button ? ($post->settings->sharing_button == 'on' ? 'checked' : '') : '') : '') ?> name="settings[sharing_button]">
                                <span></span> 
                            </label>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Show like button</label>
                            <label class="switch">
                                <input type="hidden" name="settings[like_button]" value="off" />
                                <input type="checkbox" <?= ($post->settings ? ($post->settings->like_button ? ($post->settings->like_button == 'on' ? 'checked' : '') : '') : '') ?> name="settings[like_button]">
                                <span></span> 
                            </label>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">More Options</h6>
                    <div class="card-body">
                        <!-- <div class="form-group">
                            <label>Excerpt</label>
                            <textarea name="excerpt" class="form-control" placeholder="Write an excerpt"><?= $post->excerpt ?></textarea>
                        </div> -->
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Featured</label>
                            <label class="switch">
                                <input type="hidden" name="settings[featured]" value="off" />
                                <input type="checkbox" <?= ($post->settings ? ($post->settings->featured ? ($post->settings->featured == 'on' ? 'checked' : '') : '') : '') ?> name="settings[featured]">
                                <span></span> 
                            </label>
                        </div>
                        <div class="form-group mb-0">
                            <label class="text-muted small">DISCUSSION</label>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Allow Comments</label>
                            <label class="switch">
                                <input type="hidden" name="settings[allow_comments]" value="off" />
                                <input type="checkbox" <?= ($post->settings ? ($post->settings->allow_comments ? ($post->settings->allow_comments == 'on' ? 'checked' : '') : '') : '') ?> name="settings[allow_comments]">
                                <span></span> 
                            </label>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center mb-0">
                            <label class="mb-0">Allow Pingbacks &amp; Trackbacks</label>
                            <label class="switch">
                                <input type="hidden" name="settings[allow_pingbacks]" value="off" />
                                <input type="checkbox" <?= ($post->settings ? ($post->settings->allow_pingbacks ? ($post->settings->allow_pingbacks == 'on' ? 'checked' : '') : '') : '') ?> name="settings[allow_pingbacks]">
                                <span></span> 
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $('#form-data').on('submit', function (e) {
    e.preventDefault();
    var data = new FormData(this);
    let domain_url = "<?= domain_url('/pages/'.($post->id ? 'update' : 'create'), null, 'api') ?>";
    $.ajax({
        url: domain_url,
        type: "POST",
        data:data,
        async: false,
        processData: false,
        contentType: false,
        success: function(result){
            window.location.href =  espresso.helpers.url.base("site/page");
        },
        error: function (error) {
            window.location.href =  espresso.helpers.url.base("site/page");
        }
    });
});
</script>