<form id="form-data" method="post" action="<?php echo current_url() ?>" enctype="multipart/form-data">
    <div class="card">
        <div class="card-header">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto">
                    <h5 class="mb-0"><?=$page->title;?></h5>
                </div>
                <div class="col-auto">
                    <div class="form-row justify-content-end">
                        <div class="col-auto">
                            <a class="btn btn-default" data-action="sidebar-right-toggle" href="javascript:void(0);"><i class="fa fa-cogs"></i></a>
                        </div>

                        <div class="col-auto">
                            <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                <?php echo language('BTN_CANCEL'); ?>
                            </button>
                            <button type="submit" class="btn btn-primary btn-md">
                                <?php echo language('BTN_SAVE'); ?>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-center post-editor">
            <div class="col-lg-8 col-md-10">
                <div class="form-group mb-0">
                    <?php if ($post->id): ?>
                        <input type="hidden" name="id" value="<?= $post->id ?>">
                    <?php endif; ?>
                    <input class="form-control editor-title p-0" type="text" name="title" value="<?= $post->title ?>" placeholder="Add Title" required>
                </div>
                <div class="form-group">
                    <div class="editor-slug">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text px-0 text-muted">
                                    <i class="fas fa-link"></i>&nbsp;
                                    <?php echo domain_url(null, null, null);?>
                                </span>
                            </div>
                            <input class="form-control pl-0" name="slug" value="<?= $post->slug ?>" type="text" required>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div name="content" class="tinymce-inline">Write your content here...</div>
                </div>
            </div>
        </div>

        <div class="right-sidebar">
            <div class="top-title">
                <h6>Page Settings</h6>
                <a href="javascript:void" class="rightside-toggle"><i class="fa fa-times"></i></a>
            </div>

            <div class="sidebar-scroll perfect-scrollbar position-relative">
                <div id="settings" role="tablist">
                    <div class="card">
                        <div class="card-header" role="tab" id="settings-record-status" class="collapsed" data-toggle="collapse"
                            href="#status" aria-expanded="false" aria-controls="collapse-settings-record-status">
                            <h5 class="mb-0">
                                <a role="button">
                                    Status
                                </a>
                            </h5>
                        </div>

                        <div id="status" class="collapse" role="tabpanel" aria-labelledby="settings-record-status"
                            data-parent="#settings">
                            <div class="card-body">
                                <div class="form-group">
                                    <label><?=language('LANGUAGE')?></label>
                                    <select class="custom-select form-control" name="language">
                                        <?php foreach ($options->languages as $value => $option): ?>
                                            <option value="<?= $value ?>" <?= ($post->settings ? ($post->language == $value ? 'selected' : '') : '') ?>><?= $option ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label><?=language('STATUS')?></label>
                                    <select class="custom-select form-control" name="record_status">
                                        <?php foreach ($options->status as $value => $option): ?>
                                            <option value="<?= $value ?>" <?= ($post->record ? ($post->record->status == $value ? 'selected' : '') : '') ?>><?= $option ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label><?=language('VISIBILITY')?></label>
                                    <select class="custom-select form-control" name="visibility">
                                        <?php foreach ($options->visibility as $value => $option): ?>
                                            <option value="<?= $value ?>" <?= $post->visibility == $value ? 'selected' : '' ?>><?= $option ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" role="tab" id="settings-featured-image" class="collapsed" data-toggle="collapse"
                            href="#featured-image" aria-expanded="false" aria-controls="collapse-settings-featured-image">
                            <h5 class="mb-0">
                                <a role="button">
                                    Featured Image
                                </a>
                            </h5>
                        </div>
                        <div id="featured-image" class="collapse" role="tabpanel" aria-labelledby="settings-featured-image"
                            data-parent="#settings">
                            <div class="card-body">
                                <input type="file" name="photo" class="dropify" data-default-file="<?= $post->image ?>">
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" role="tab" id="settings-setting-others" class="collapsed" data-toggle="collapse"
                            href="#setting-others" aria-expanded="false" aria-controls="collapse-settings-setting-others">
                            <h5 class="mb-0">
                                <a role="button">
                                    Others
                                </a>
                            </h5>
                        </div>
                        <div id="setting-others" class="collapse" role="tabpanel" aria-labelledby="settings-setting-others"
                            data-parent="#settings">
                            <div class="card-body">
                                <div class="form-group d-flex justify-content-between align-items-center">
                                    <label class="mb-0"><?=language('FEATURED')?></label>
                                    <label class="switch">
                                        <input type="hidden" name="settings[featured]" value="off" />
                                        <input type="checkbox" <?= ($post->settings ? ($post->settings->featured ? ($post->settings->featured == 'on' ? 'checked' : '') : '') : '') ?> name="settings[featured]">
                                        <span></span> 
                                    </label>
                                </div>
                                <div class="form-group mb-0">
                                    <label class="text-muted small">
                                        <?=language('DISCUSSION')?>
                                    </label>
                                </div>
                                <div class="form-group d-flex justify-content-between align-items-center">
                                    <label class="mb-0">
                                        <?=language('ALLOW_COMMENTS')?>
                                    </label>
                                    <label class="switch">
                                        <input type="hidden" name="settings[allow_comments]" value="off" />
                                        <input type="checkbox" <?= ($post->settings ? ($post->settings->allow_comments ? ($post->settings->allow_comments == 'on' ? 'checked' : '') : '') : '') ?> name="settings[allow_comments]">
                                        <span></span> 
                                    </label>
                                </div>
                                <div class="form-group d-flex justify-content-between align-items-center mb-0">
                                    <label class="mb-0">
                                        <?=language('ALLOW_PINGBACKS_TRACKBACKS')?>
                                    </label>
                                    <label class="switch">
                                        <input type="hidden" name="settings[allow_pingbacks]" value="off" />
                                        <input type="checkbox" <?= ($post->settings ? ($post->settings->allow_pingbacks ? ($post->settings->allow_pingbacks == 'on' ? 'checked' : '') : '') : '') ?> name="settings[allow_pingbacks]">
                                        <span></span> 
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" role="tab" id="settings-search-engine-optimization" class="collapsed" data-toggle="collapse"
                            href="#search-engine-optimization" aria-expanded="false" aria-controls="collapse-settings-search-engine-optimization">
                            <h5 class="mb-0">
                                <a role="button">
                                    Search Engine Optimization
                                </a>
                            </h5>
                        </div>
                        <div id="search-engine-optimization" class="collapse" role="tabpanel" aria-labelledby="settings-search-engine-optimization"
                            data-parent="#settings">
                            <div class="card-body">
                                <div class="form-group">
                                    <label><?=language('META_ROBOT')?></label>
                                    <input class="form-control" name="meta[robot]" value="<?= ($post->metadata ? ($post->metadata->robot ? $post->metadata->robot : '') : '') ?>" type="text">
                                </div>
                                <div class="form-group">
                                    <label><?=language('META_TITLE')?></label>
                                    <input class="form-control" name="meta[title]" value="<?= ($post->metadata ? ($post->metadata->title ? $post->metadata->title : '') : '') ?>" type="text">
                                </div>
                                <div class="form-group">
                                    <label><?=language('META_DESCRIPTION')?></label>
                                    <textarea class="form-control" cols="5" name="meta[description]"><?= ($post->metadata ? ($post->metadata->description ? $post->metadata->description : '') : '') ?></textarea>
                                </div>
                                <div class="form-group">
                                    <label><?=language('META_KEYWORDS')?></label>
                                    <input class="tagsinput form-control" data-role="tagsinput" name="meta[keywords]" value="<?= ($post->metadata ? ($post->metadata->keywords ? $post->metadata->keywords : '') : '') ?>" type="text">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-header" role="tab" id="settings-setting-socmed" class="collapsed" data-toggle="collapse"
                            href="#setting-socmed" aria-expanded="false" aria-controls="collapse-settings-setting-socmed">
                            <h5 class="mb-0">
                                <a role="button">
                                    Social Media
                                </a>
                            </h5>
                        </div>
                        <div id="setting-socmed" class="collapse" role="tabpanel" aria-labelledby="settings-setting-socmed"
                            data-parent="#settings">
                            <div class="card-body">
                                <div class="form-group d-flex justify-content-between align-items-center">
                                    <label class="mb-0"><?=language('SOCIALMEDIA_SHOW_SHARING_BUTTONS')?></label>
                                    <label class="switch">
                                        <input type="hidden" name="settings[sharing_button]" value="off" />
                                        <input type="checkbox" <?= ($post->settings ? ($post->settings->sharing_button ? ($post->settings->sharing_button == 'on' ? 'checked' : '') : '') : '') ?> name="settings[sharing_button]">
                                        <span></span>
                                    </label>
                                </div>
                                <div class="form-group d-flex justify-content-between align-items-center">
                                    <label class="mb-0"><?=language('SOCIALMEDIA_SHOW_LIKE_BUTTONS')?></label>
                                    <label class="switch">
                                        <input type="hidden" name="settings[like_button]" value="off" />
                                        <input type="checkbox" <?= ($post->settings ? ($post->settings->like_button ? ($post->settings->like_button == 'on' ? 'checked' : '') : '') : '') ?> name="settings[like_button]">
                                        <span></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>
<script>
	$('[data-action="cancel"]').click(function(){
	    window.location = "/site/pages";
	});

    $('#form-data').on('submit', function (e) {
        e.preventDefault();
        ajaxSettings.method = "POST";
        ajaxSettings.url = "/api/site/pages/<?=($post->id ? 'update' : 'create')?>";
        ajaxSettings.data = new FormData(this);
        ajaxSettings.processData = false;
        ajaxSettings.contentType = false;

        $.ajax(ajaxSettings).done(function(response){
            window.location.href = '/site/pages';
    });
});
</script>