<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-12">
	        <div class="card">
		        <div class="card-header">
			        <div class="row align-items-center justify-content-between">
				        <div class="col-auto">
					        <h5 class="mb-0"><?=$page->title;?></h5>
				        </div>
				        <div class="col-auto">
					        <a href="<?php echo base_url('/site/pages/form'); ?>" class="btn btn-primary btn-md">
						        <?=language('BTN_ADD_NEW')?>
					        </a>
				        </div>
			        </div>

		        </div>
	        </div>
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">    
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link <?=$get->status === 'PUBLISH' ? 'active' : '' ?>" href="<?= base_url('site/page') ?>">Published</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link <?=$get->status === 'DRAFT' ? 'active' : '' ?>" href="<?= base_url('site/page',['status' => 'DRAFT']) ?>">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link <?=$get->status === 'TRASH' ? 'active' : '' ?>" href="<?= base_url('site/page',['status' => 'TRASH']) ?>">Trash</a>
                            </li>
                        </ul>

                        <form class="nav-search">
                            <div class="search-icon open-search">
                                <i class="fas fa-search"></i>
                            </div>
                            <div class="search-input">
                                <input type="search" placeholder="Search..." name="title">
                            </div>
                            <div class="search-icon close-search">
                                <i class="fas fa-times"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <?php if ($pages): ?>
            <div class="post-list">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
	                    <div class="list-group mb-3">
	                        <?php foreach ($pages as $page): ?>
	                            <div class="list-group-item">
		                            <div class="post-item">
			                            <div class="post-item-detail">
				                            <h1>
					                            <a href="<?php echo base_url('/site/pages/edit/'.$page->id); ?>"><?= $page->title ?></a>
				                            </h1>
				                            <div class="post-item-meta">
					                            <span class="post-time"><?= date('M j, Y h:i A', strtotime($page->record->create->timestamp)) ?></span>
				                            </div>
			                            </div>
			                            <div class="post-thumbnail">
				                            <a href="#">
					                            <img src="<?= $page->image ?>">
				                            </a>
			                            </div>
			                            <div class="post-action">
				                            <div class="dropdown">
					                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					                            </a>
					                            <div class="dropdown-menu dropdown-menu-right">
						                            <a class="dropdown-item" href="<?php echo base_url('/site/pages/edit/'.$page->id); ?>">
							                            <i class="fas fa-pencil-alt"></i>
	                                                    <?=language('EDIT')?>
						                            </a>
						                            <a class="dropdown-item" href="<?php echo base_url('/site/pages/stats/'.$page->id); ?>">
							                            <i class="fas fa-chart-bar"></i>
	                                                    <?=language('STATS')?>
						                            </a>
						                            <a class="dropdown-item" href="<?php echo base_url('/site/pages/copy/'.$page->id); ?>" data-action="copy">
							                            <i class="fa fa-copy"></i>
	                                                    <?=language('COPY')?>
						                            </a>
						                            <div class="dropdown-divider"></div>
						                            <a class="dropdown-item" href="<?php echo base_url('/site/pages/delete/'.$page->id); ?>" data-action="delete">
							                            <i class="fa fa-trash"></i>
	                                                    <?=language('DELETE')?>
						                            </a>
					                            </div>
				                            </div>
			                            </div>
		                            </div>
	                            </div>
	                        <?php endforeach ?>
	                    </div>
                        <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('site/page', [
                                        'status'    => $get->status,
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo language('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('site/page', [
                                        'status'    => $get->status,
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $pages->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo language('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="status" value="<?= $get->status ?>">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="period" value="<?= $get->period ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $pages->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$pages->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
    <?php else: ?>
        <div data-role="search-not-found" class="row justify-content-center">
            <div class="col-md-4 text-center p-3">
                <img src="./assets/img/nopost.png" class="img-fluid">
                <h3 class="mt-3">Whoops!</h3>
                <h6 class="text-danger mb-4">
                    No pages found.
                </h6>
                <a href="<?php echo base_url('/site/page/form'); ?>" class="btn btn-primary btn-md">Add New Page</a>
            </div>
        </div>
    <?php endif; ?>
</div>

<script>
    $(document).ready(function(){
        $(document).on('click', '[data-action="delete"]', function(e){
            e.preventDefault();
            var id = $(this).data('id');
            let domain_url = "<?= domain_url('/pages/delete', null, 'api') ?>";
            $.ajax({
                url: '/api/site/pages/delete',
                type: "POST",
                data:"id="+id,
                success: function(result){
                    window.location.href =  espresso.helpers.url.base("site/pages");
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
    });
</script>