<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">    
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link active" href="<?= base_url('site/page') ?>">Published</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= base_url('site/page/drafts') ?>">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= base_url('site/page/trash') ?>">Trash</a>
                            </li>
                        </ul>

                        <form class="nav-search">
                            <div class="search-icon open-search">
                                <i class="fas fa-search"></i>
                            </div>
                            <div class="search-input">
                                <input type="search" placeholder="Search...">
                            </div>
                            <div class="search-icon close-search">
                                <i class="fas fa-times"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <a href="<?php echo base_url('/site/page/form'); ?>" class="btn btn-primary btn-md">Add New Page</a>
                </div>
            </div>
        </div>
    </div>

    <?php if ($pages): ?>
            <div class="post-list">
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-10">
                        <?php foreach ($pages as $page): ?>
                            <div class="card">
                                <div class="card-body">
                                    <div class="post-item">
                                        <div class="post-item-detail">
                                            <h1>
                                                <a href="#"><?= $page->title ?></a>
                                            </h1>
                                            <div class="post-item-meta">
                                                <span class="post-time"><?= date('M j, Y h:i A', strtotime($page->record->create->timestamp)) ?></span>   
                                            </div>
                                        </div>
                                        <div class="post-thumbnail">
                                            <a href="#">
                                                <img src="<?= $page->image ?>">
                                            </a>
                                        </div>
                                        <div class="post-action">
                                            <div class="dropdown">
                                                <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" href="<?php echo base_url('/site/page/form/'.$page->id); ?>">
                                                        <i class="fas fa-pencil-alt"></i>
                                                        Edit
                                                    </a>
                                                    <!-- <a class="dropdown-item" href="#">
                                                        <i class="fa fa-eye"></i>
                                                        View
                                                    </a>
                                                    <a class="dropdown-item" href="#">
                                                        <i class="fas fa-chart-bar"></i>
                                                        Stats
                                                    </a>
                                                    <a class="dropdown-item" href="#">
                                                        <i class="fa fa-copy"></i>
                                                        Copy
                                                    </a> -->
                                                    <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item" href="<?= current_url(); ?>" data-id="<?= $page->id ?>" data-action="delete">
                                                        <i class="fa fa-trash"></i>
                                                        Trash
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                        <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('site/page', [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('site/page', [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $pages->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="period" value="<?= $get->period ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $pages->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$pages->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
    <?php else: ?>
        <div data-role="search-not-found" class="row justify-content-center">
            <div class="col-md-4 text-center p-3">
                <img src="./assets/img/nopost.png" class="img-fluid">
                <h3 class="mt-3">Whoops!</h3>
                <h6 class="text-danger mb-4">
                    No pages found.
                </h6>
                <a href="<?php echo base_url('/site/page/form'); ?>" class="btn btn-primary btn-md">Add New Page</a>
            </div>
        </div>
    <?php endif; ?>

    

    <!-- <nav>
        <ul class="pagination d-flex justify-content-center">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav> -->
</div>

<script>
    $(document).ready(function(){
        $(document).on('click', '[data-action="delete"]', function(e){
            e.preventDefault();
            var id = $(this).data('id');
            let domain_url = "<?= domain_url('/pages/delete', null, 'api') ?>";
            $.ajax({
                url: domain_url,
                type: "POST",
                data:"id="+id,
                success: function(result){
                    window.location.href =  espresso.helpers.url.base("site/page");
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
    });
    
</script>