<div class="container-fluid pt-0 pl-2 pr-2 pb-0">
    <input type="hidden" id="getPage" value="">
    <div class="row">
        <div id="personal-notes-sidebar" class="col-lg-3 col-md-3">
            <form role="form">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="query" placeholder="Search">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary" style="box-shadow: none; border-top-left-radius: 0 !important; border-bottom-left-radius: 0 !important;"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            <ul class="notes-list">
                <li class="notes-list-item" data-note="21" style="">
                    <div class="item-label">
                        <input type="text" class="" value="Untitled Note" name="note-label" data-search="" readonly="">
                        <button class="btn btn-xs btn-default" data-action="note-delete" style="">
                                <i class="fa fa-trash"></i>
                        </button>
                    </div>
                    <ul class="pages-list">
                        <li class="pages-list-item" data-page="" data-tpl="pages-list-item" style="display: none;">
                            <div class="item-title">
                                <a href="javascript:void(0);" class="" data-action="page-load" data-search="" data-toggle="tooltip" data-placement="top" title="" data-original-title="">
                                        Untitled Page
                                    </a>
                                <div class="btn-group" role="group">
                                    <button class="btn btn-xs btn-default" data-action="page-edit">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                    <button class="btn btn-xs btn-default" data-action="page-delete">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </li>
                        <li class="pages-list-item" data-page="100" style="">
                            <div class="item-title">
                                <a href="javascript:void(0);" class="" data-action="page-load" data-search="" data-toggle="tooltip" data-placement="top" title="Untitled Page" data-original-title="">Untitled Page</a>
                                <div class="btn-group" role="group">
                                    <button class="btn btn-xs btn-default" data-action="page-edit">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                    <button class="btn btn-xs btn-default" data-action="page-delete">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                            </div>
                        </li>
                        <li class="pages-list-add" data-action="page-add">
                            <div class="row align-items-center">
                                <div class="col-md-11 pr-0">
                                    <hr class="m-0">
                                </div>
                                <div class="col-md-1 pl-0">
                                    <i class="fa fa-plus-circle"></i>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="notes-list-item" data-note="26" style="">
                    <div class="item-label">
                        <input type="text" class="" value="Untitled Note" name="note-label" data-search="" readonly="">
                        <button class="btn btn-xs btn-default" data-action="note-delete" style="">
                                <i class="fa fa-trash"></i>
                        </button>
                    </div>
                    <ul class="pages-list">
                        <li class="pages-list-item" data-page="" data-tpl="pages-list-item" style="display: none;">
                            <div class="item-title">
                                <a href="javascript:void(0);" class="" data-action="page-load" data-search="" data-toggle="tooltip" data-placement="top" title="" data-original-title="">
                                        Untitled Page
                                    </a>
                                <div class="btn-group" role="group">
                                    <button class="btn btn-xs btn-default" data-action="page-edit">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    <button class="btn btn-xs btn-default" data-action="page-delete">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                </div>
                            </div>
                        </li>
                        <li class="pages-list-add" data-action="page-add">
                            <div class="row align-items-center">
                                <div class="col-md-11 pr-0">
                                    <hr class="m-0">
                                </div>
                                <div class="col-md-1 pl-0">
                                    <i class="fa fa-plus-circle"></i>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="notes-list-item" data-note="" data-tpl="notes-list-item" style="display: none;">
                    <div class="item-label">
                        <input type="text" class="" value="Untitled Note" name="note-label" data-search="" readonly="">
                        <button class="btn btn-xs btn-default" data-action="note-delete" style="">
                            <i class="fa fa-trash"></i>                            
                        </button>
                    </div>
                    <ul class="pages-list">
                        <li class="pages-list-item" data-page="" data-tpl="pages-list-item" style="display: none;">
                            <div class="item-title">
                                <a href="javascript:void(0);" class="" data-action="page-load" data-search="" data-toggle="tooltip" data-placement="top" title="" data-original-title="">
                                        Untitled Page
                                    </a>
                                <div class="btn-group" role="group">
                                    <button class="btn btn-xs btn-default" data-action="page-edit">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    <button class="btn btn-xs btn-default" data-action="page-delete">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                </div>
                            </div>
                        </li>
                        <li class="pages-list-add" data-action="page-add">
                            <div class="row align-items-center">
                                <div class="col-md-11 pr-0">
                                    <hr class="m-0">
                                </div>
                                <div class="col-md-1 pl-0">
                                    <i class="fa fa-plus-circle"></i>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="notes-list-add">
                    <a href="javascript:void(0);" class="" data-action="note-add">
                        Add New Note
                    </a>
                </li>
            </ul>
        </div>
        <div id="personal-notes-page" class="col-lg-9 col-md-9">
            <form role="form" action="" method="post">
                <div class="form-group">
                    <input type="hidden" name="id" value="">
                    <input type="hidden" name="id_personal_note" value="">
                    <input type="text" class="form-control" name="title" value="Untitled" placeholder="Title">
                    <small class="text-muted" name="last-update">
                            <i class="fa fa-clock"></i>
                            Last updated 36 minutes ago
                        </small>
                </div>
                <hr>
                <div class="form-group mb-0">
                    <div class="tinymce-inline content mce-content-body" name="content" id="mce_0" spellcheck="false" contenteditable="true">
                        <p>Enter your content here...</p>
                    </div><input type="hidden" name="mce_0">
                </div>
            </form>
        </div>
    </div>
</div>