<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h3 class="mb-4">Detail Tags</h3>
                    </div>
                </div>

                <div class="card">
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Title</th>
                                    <td><?= $tag->title; ?></td>
                                </tr>
                                <tr>
                                    <th>Record Status</th>
                                    <td><?= $tag->record_status; ?></td>
                                </tr>
                                <tr>
                                    <th>Date Created</th>
                                    <td><?= $tag->record_create_timestamp; ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <?php //echo view('components/pagination', [], true); ?>
                
            </div>
        </div>
    </div>
</div>