<div class="page-form">
    <div class="container-fluid">
        <form action="<?= current_url();?>" method="post">
            <input type="hidden" name="id" value="<?= $bank->id; ?>">
            <div class="card">
                <h5 class="card-header d-flex justify-content-between align-items-center">
                    <?php echo $page->title; ?>

                    <div class="card-options">
                        <button type="button" class="btn btn-default btn-md" data-action="cancel">
                            CANCEL
                        </button>
                        <button type="submit" class="btn btn-primary btn-md">
                            SAVE
                        </button>
                    </div>
                </h5>
            </div>

            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input class="form-control" name="name" type="text" value="<?= $bank->name;?>" required="">
                    </div>
                    <div class="form-group">
                        <label>Alias</label>
                        <input class="form-control" name="alias" type="text" value="<?= $bank->alias;?>" required="">
                    </div>
                    <div class="form-group">
                        <label>Company</label>
                        <input class="form-control" name="company" type="text" value="<?= $bank->company;?>" required="">
                    </div>
                    <div class="form-group">
                        <label>Code</label>
                        <input class="form-control" name="code" type="text" value="<?= $bank->code;?>" required="">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
