<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" action="<?php echo base_url('/master/geodirectories/form'); ?>" enctype="multipart/form-data">
                    <?php if ($post->id): ?>
                        <input type="hidden" name="id" value="<?= $post->id ?>">
                    <?php endif; ?>
                    <div class="card">
                        <h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->title; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                    </div>
                    <div class="card">
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>ID Parent</label>
                                        <select class="form-control select-dropdown" data-live-search="true" name="id_parent">
                                            <option value="1">Root</option>
                                            <?php if ($parents): ?>
                                                <?php foreach ($parents as $parent): ?>
                                                    <option value="<?= $parent->id ?>" <?= ($post->id_parent == $parent->id ? 'selected' : '') ?>><?= $parent->name ?></option>
                                                <?php endforeach ?>
                                            <?php endif ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input class="form-control" type="text" name="name" value="<?= $post->name ?>" placeholder="" required="">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Type</label>
                                        <select name="type" class="form-control custom-select" required="">
                                            <?php foreach ($types as $key => $value): ?>
                                                <option value="<?= $key ?>" <?= ($post->type == $key ? 'selected' : '') ?>><?= $value ?></option>
                                            <?php endforeach ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Postal Code</label>
                                        <input class="form-control" type="number" maxlength="5" name="postal" value="<?= $post->postal ?>" placeholder="" required="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
$(document).on('click', '[data-action="add-item"]', function (e) {
    e.preventDefault();
    var row = $(this).parents('.card').find('[data-tpl="item"]');
    var clone = row.clone();

    clone.attr('data-tpl', 'item-cloned');
    clone.removeClass('d-none');

    clone.find('input').each(function () {
        $(this).val('');
    });

    clone.find('[data-action="remove-item"]').removeClass('d-none');
    row.before(clone);
});
</script>