<div class="page-table">
    <div class="container-fluid">
        <div class="row justify-content-between align-items-center">
            <div class="col-md-auto">
                <h3 class="mb-1 font-weight-bold"><?php echo language('USERS_LIST'); ?></h3>
                <p class="text-muted">You have total 2,595 users.</p>
            </div>
            <div class="col-md-auto">
                <div class="form-row justify-content-end">
                    <div class="col-auto">
                        <div class="form-group">
                            <a href="#" class="btn btn-default">
                                <i class="fas fa-download"></i>
                                <?php echo language('EXPORT'); ?>
                            </a>
                        </div>
                    </div>
                    <div class="col-auto">
                        <div class="form-group">
                            <div class="drodown">
                                <a href="#" class="dropdown-toggle btn btn-primary remove-caret" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fas fa-plus"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="<?= base_url('people/form'); ?>" class="dropdown-item">
                                        <?php echo language('BTN_ADD_USER'); ?>
                                    </a>
                                    <a href="#" class="dropdown-item">
                                        <?php echo language('BTN_ADD_TYPE'); ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header pb-0">
                <div class="row">
                    <div class="col-md-6">
                        <form action="">
                            <div class="form-row">
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <select name="" id="" class="form-control custom-select">
                                            <option value="">Option</option>
                                            <option value="">Option</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-auto">
                                    <button class="btn btn-default" type="submit">Apply</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-6">
                        <div class="form-row justify-content-end">
                            <div class="col-auto">
                                <a href="#" class="btn btn-link" data-toggle="search">
                                    <i class="fas fa-search"></i>
                                </a>
                            </div>
                            <div class="col-auto">
                                <div class="dropdown">
                                    <a href="#" class="btn btn-link dropdown-toggle remove-caret" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fas fa-filter"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-xl dropdown-menu-right p-0 stop-propagation">
                                        <div class="dropdown-head">
                                            <h6 class="font-weight-bold">Filters</h6>
                                        </div>
                                        <div class="dropdown-body">
                                            <div class="row">
                                                <div class="col-6">
                                                    <div class="form-group">
                                                        <div class="custom-control custom-control-sm custom-checkbox">
                                                            <input type="checkbox" class="custom-control-input" id="hasBalance">
                                                            <label class="custom-control-label" for="hasBalance"> Have Balance</label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-6">
                                                    <div class="form-group">
                                                        <div class="custom-control custom-control-sm custom-checkbox">
                                                            <input type="checkbox" class="custom-control-input" id="hasKYC">
                                                            <label class="custom-control-label" for="hasKYC"> KYC Verified</label>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-6">
                                                    <div class="form-group">
                                                        <label>Role</label>
                                                        <select class="form-select custom-select">
                                                            <option value="any">Any Role</option>
                                                            <option value="investor">Investor</option>
                                                            <option value="seller">Seller</option>
                                                            <option value="buyer">Buyer</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-6">
                                                    <div class="form-group">
                                                        <label>Status</label>
                                                        <select class="form-select custom-select">
                                                            <option value="any" data-select2-id="9">Any Status</option>
                                                            <option value="active">Active</option>
                                                            <option value="pending">Pending</option>
                                                            <option value="suspend">Suspend</option>
                                                            <option value="deleted">Deleted</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-group">
                                                        <button type="button" class="btn btn-primary">Filter</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="dropdown-foot justify-content-between">
                                            <a class="clickable" href="#">Reset Filter</a>
                                            <a href="#">Save Filter</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-search">
                    <form action="<?= current_url(); ?>" method="get">
                        <div class="form-row">
                            <div class="col-auto">
                                <a href="#" class="btn btn-link" data-toggle="search"><i class="fas fa-arrow-left"></i></a>
                            </div>
                            <div class="col">
                                <input type="text" name="keyword" class="form-control" placeholder="Search...">
                            </div>
                            <div class="col-auto">
                                <button class="btn btn-link" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th width="5%">
                                <div class="custom-control custom-control-sm custom-checkbox ml-2">
                                    <input type="checkbox" class="custom-control-input" id="uid">
                                    <label class="custom-control-label" for="uid">&nbsp;</label>
                                </div>
                            </th>
                            <th>Fullname</th>
                            <th>Cover</th>
                            <th>Gender</th>
                            <th>Record Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody class="text-nowrap">
                        <?php foreach ($peoples as $people) : ?>
                            <tr>
                                <td>
                                    <div class="custom-control custom-control-sm custom-checkbox ml-2">
                                        <input type="checkbox" class="custom-control-input" id="uid-1">
                                        <label class="custom-control-label" for="uid-1">&nbsp;</label>
                                    </div>
                                </td>
                                <td>
                                    <div class="media align-items-center">
                                        <div class="avatar avatar-40 mr-2">
                                            <img src="assets/img/avatar.jpg" alt="">
                                        </div>
                                        <div class="media-body">
                                            <h6 class="font-weight-bold mb-0"><?= $people->fullname ?></h6>
                                            <p class="mb-0 text-muted small">Frontend Developer</p>
                                        </div>
                                    </div>
                                </td>
                                <td><?= $people->cover; ?></td>
                                <td><?= $people->gender; ?></td>
                                <td><?= $people->record_status; ?></td>
                                <td>
                                    <div class="dropdown">
                                        <a href="#" class="dropdown-toggle remove-caret" data-toggle="dropdown" aria-expanded="false">
                                            <i class="fas fa-ellipsis-h"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a href="<?= base_url('people/detail/' . $people->id); ?>" class="dropdown-item">
                                                <i class="fas fa-eye"></i> View
                                            </a>
                                            <a href="<?= base_url('people/form/' . $people->id); ?>" class="dropdown-item">
                                                <i class="fas fa-pencil-alt"></i> Edit
                                            </a>
                                            <a href="<?= base_url('people/delete/' . $people->id); ?>" class="dropdown-item">
                                                <i class="fas fa-trash"></i> Delete
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>