<div class="page-administrator">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="user-list">
                    <div class="card">
                        <div class="card-body">
                            <div class="media align-items-center">
                                <div class="media-body d-flex align-items-center justify-content-between">
                                    <div>
                                        <h5 class="mb-1">
                                            <a href="#"
                                               class="d-flex align-items-center">
                                                <span class="btn btn-default btn-xs mr-2 text-uppercase">DEVELOPER</span>
                                                Developer
                                            </a>
                                        </h5>
                                        <blockquote>
                                            <p>somebody with access to the site content management system with
                                                development features and all other features</p>
                                        </blockquote>
                                    </div>
                                    <div class="user-action">
                                        <div class="dropdown">
                                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item"
                                                   href="#">
                                                    <i class="fas fa-pencil-alt"></i> Edit
                                                </a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item"
                                                   href="#">
                                                    <i class="fa fa-trash"></i> Delete
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body with-table">
                            <div class="table-responsive">
                                <table class="table table-striped valign-middle">
                                    <thead>
                                    <tr>
                                        <th>Namespace</th>
                                        <th>Type</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=15">
                                                App\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">APP</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/15">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/15"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=1">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">APP</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/1">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/1"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=3">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\BuildingManagement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/3">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/3"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=4">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Company\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/4">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/4"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=5">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Finance\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/5">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/5"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=6">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Goods\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/6">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/6"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=7">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\HumanResource\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/7">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/7"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=8">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Learning\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/8">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/8"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=9">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\MasterData\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/9">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/9"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=10">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Office\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/10">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/10"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=11">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Personal\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/11">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/11"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=12">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Scrum\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/12">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/12"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=13">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Shuttle\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/13">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/13"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=14">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\System\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/14">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/14"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=37">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\FixedAssets\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/37">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/37"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=38">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Customers\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/38">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/38"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=39">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Companies\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/39">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/39"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=43">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Quiz\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/43">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/43"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=2">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\AssetsManagement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/2">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/2"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=16">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Administrator\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/16">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/16"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=17">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\AssetsManagement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/17">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/17"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=18">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\BuildingManagement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/18">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/18"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=19">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Company\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/19">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/19"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=20">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Customers\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/20">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/20"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=21">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Documentations\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/21">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/21"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=22">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Finance\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/22">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/22"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=23">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                Goods\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/23">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/23"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=24">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Helpdesk\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/24">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/24"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=25">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\HumanResource\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/25">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/25"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=26">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Learning\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/26">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/26"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=27">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Office\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/27">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/27"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=28">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Personal\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/28">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/28"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=29">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Shuttle\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/29">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/29"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=30">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Goods\Backup\Inventory\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/30">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/30"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=31">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Goods\Backup\Procurement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/31">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/31"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=32">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Api\Modules\Goods\Backup\Suppliers\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/32">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/32"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=33">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                Procurement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/33">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/33"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=34">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                Suppliers\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/34">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/34"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=35">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\FixedAssets\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/35">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/35"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=36">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Tasks\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/36">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/36"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=40">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Companies\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/40">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/40"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=41">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\ProjectManagement\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/41">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/41"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=42">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Quiz\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/42">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/42"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=44">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Agenda\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/44">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/44"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <a href="https://itsynergy.mandayamedical.group/administrator/modules/roles/detail/1?id_segment=45">
                                                &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                                App\Modules\Documents\ </a>
                                        </td>
                                        <td>
                                            <span class="text-uppercase badge badge-info">MODULE</span>
                                        </td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/form/45">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-default btn-sm"
                                                   href="https://itsynergy.mandayamedical.group/administrator/modules/delete/45"
                                                   data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>