<form action="<?= current_url();?>" method="post">
    <input type="hidden" name="id" value="<?= $role->id; ?>">
    <div class="card">
        <h5 class="card-header d-flex justify-content-between align-items-center">
            <?php echo $page->title; ?>

            <div class="card-options">
                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                    CANCEL
                </button>
                <button type="submit" class="btn btn-primary btn-md">
                    SAVE
                </button>
            </div>
        </h5>
    </div>

    <div class="card">
        <div class="card-body">                       
            <div class="form-group">
                <label>PARENT</label>
                <select name="id_sys_module" class="form-control">
                    <option value="1">test</option>
                </select>
            </div>                           
            <div class="form-group">
                <label>CODE</label>
                <input class="form-control" name="code" type="text" value="<?= $role->code; ?>" required="">
            </div>
            <div class="form-group">
                <label>LABEL</label>
                <input class="form-control" name="label" type="text" value="<?= $role->label; ?>" required="">
            </div>
            <div class="form-group">
                <label>DESCRIPTION</label>
                <textarea name="description" class="form-control" required=""><?= $role->description; ?></textarea>
            </div>
        </div>
    </div>
</form>