<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <div class="notifications">
                <div class="card unread">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-10">
                                <a href="#">
                                    <div class="media align-items-center">
                                        <img src="assets/img/avatar-male.png" width="50" height="50">
                                        <div class="media-body">
                                            <h4 class="notifiction-title">
                                                <strong>Teguh Rianto</strong> menyukai <strong>Anda</strong>
                                            </h4>
                                            <p class="notification-time">
                                                <i class="fas fa-clock"></i> 11 Oct 2018, 01:45
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-2 text-right">
                                <div class="dropdown">
                                    <a class="dropdown-toggle custom-dropdown-toggle dropdown-ellipsis" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" href="#"><i class="fas fa-eye"></i> Mark Read</a>
                                        <a class="dropdown-item" href="#"><i class="fa fa-trash"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>