<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">    
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="<?=base_url('system');?>">Information</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="<?=base_url('system/folder-permissions');?>">Folder Permission</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?=base_url('system/php-settings');?>">PHP Settings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?=base_url('system/php-info');?>">PHP Info</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">Folder Permissions</h3>
                </div>
                <div class="card-body with-table">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped mb-0">
                            <thead>
                            <tr>
                                <th>Folder</th>
                                <th>Permissions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach( $folderPermissions as $folder => $permission ): ?>
                                <tr>
                                    <td><?php echo $folder; ?></td>
                                    <td>
                                        <?php if( $permission === true ): ?>
                                            <span class="badge badge-success">writable</span>
                                        <?php else: ?>
                                            <span class="badge badge-danger">not-writable</span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>