<div class="container-fluid">
    <form id="form-posts" method="post" action="<?php echo base_url('posts/form'); ?>" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <h6 class="card-header">
                        Title
                    </h6>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <input class="form-control" type="text" name="title" value="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-link"></i>
                                        </span>
                                    </div>
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            http://yourdomain.com/
                                        </span>
                                    </div>
                                    <input class="form-control" name="segments" value="" type="text">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <h6 class="card-header">
                        Content
                    </h6>
                    <div class="card-body p-0 post-editor">
                        <div class="form-group row mb-0">
                            <div class="col-md-12">
                                <textarea class="form-control tinymce" name="content">
                                    
                                </textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        Images
                    </div>
                    <div class="card-body p-0">
                        <div id="dropzone-cards" data-action-url="http://localhost:8080/">
                            <div class="media-list">
                                <div class="dropzone-form" id="dropzone-cards-form" style="cursor: pointer;">
                                    <div class="dz-message needsclick">
                                        <p>Drop files here or click to upload.<br>
                                            <span class="note needsclick">
                                                (This is just a demo dropzone. Selected files are
                                                <strong>not</strong> actually uploaded.)
                                            </span>
                                        </p>
                                    </div>
                                    <div class="dropzone-previews" id="dropzone-previews">
                                        <div class="dz-template" id="dropzone-cards-template">
                                            <div class="media-list-item uploading">
                                                <div class="media-list-action d-flex">
                                                    <button type="button" class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal"
                                                        data-target="#modal-edit">Edit</button>
                                                    <button type="button" class="btn btn-danger btn-xs">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </div>
                                                
                                                <input type="checkbox" id="media-1">
                                                <label class="media-item" for="media-1">
                                                    <img data-dz-thumbnail>
                                                    <div class="media-item-file-details">
                                                        <div class="media-item-icon">
                                                            <i class="fas fa-file-powerpoint"></i>
                                                        </div>
                                                        <div class="media-item-file-name" data-dz-name></div>
                                                        <div class="media-item-file-extension"></div>
                                                    </div>
                                                </label>
        
                                                <div class="upload-progress">
                                                    <div class="progress">
                                                        <div class="progress-bar progress-bar-striped progress-bar-animated"
                                                            role="progressbar" aria-valuenow="75" aria-valuemin="0"
                                                            aria-valuemax="100" style="width: 0%" data-dz-uploadprogress></div>
                                                    </div>
                                                </div>
        
                                                <div class="media-item-file-error">
                                                    <div class="media-item-icon-error">
                                                        <i class="fas fa-exclamation-circle"></i>
                                                    </div>
                                                    <div class="media-item-file-name-error" data-dz-errormessage></div>
                                                    <div class="media-item-file-extension-error d-flex justify-content-center">
                                                        <button type="button" class="btn btn-outline-light btn-sm"
                                                            data-dz-remove>
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mb-2">
                    <div class="card-header">
                        Search Engine Optimization
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <label class="col-md-3">Metarobot</label>
                            <div class="col-md-9">
                                <input class="form-control" name="meta[robot]" value="" type="text">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Metatitle</label>
                            <div class="col-md-9">
                                <input class="form-control" name="meta[title]" value="" type="text">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Metadescription</label>
                            <div class="col-md-9">
                                <textarea class="form-control" cols="5" name="meta[description]"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-3">Metakeywords</label>
                            <div class="col-md-9">
                                <input class="tagsinput form-control" data-role="tagsinput" name="meta[keywords]" value="" type="text">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label>Language</label>
                            <select class="custom-select form-control">
                                <option>English</option>
                                <option>Indonesia</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Format</label>
                            <select class="custom-select form-control">
                                <option>Post</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <select class="custom-select form-control">
                                <option>Publish</option>
                                <option>Draft</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Visibility</label>
                            <select class="custom-select form-control">
                                <option>Public</option>
                                <option>Private</option>
                            </select>
                        </div>
                        <div class="form-group mb-0 text-right">
                            <a class="btn btn-default" href="#">
                                Preview
                            </a>
                            <button type="submit" class="btn btn-primary ml-2" data-action="save">
                                Save
                            </button>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">Publishing</h6>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Start Publishing</label>
                            <input type="datetime-local" name="publish[start]" class="form-control" value="">
                        </div>
                        <div class="form-group">
                            <label>Finish Publishing</label>
                            <input type="datetime-local" name="publish[finish]" class="form-control" value="">
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">
                        Categories
                    </h6>
                    <div class="card-body">
                        <div class="form-group">
                            <select class="form-control custom-select selectize-single" name="" placeholder="Select or Add">
                                <option value="" selected>Test</option>
                                <option>First</option>
                                <option>Second</option>
                                <option>Third</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">
                        Tags
                    </h6>
                    <div class="card-body">
                        <div class="form-group mb-0">
                            <input type="text" name="tags" data-role="tagsinput" value="" />
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">Sharing</h6>
                    <div class="card-body">
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Show sharing buttons</label>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span></span> 
                            </label>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Show like button</label>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span></span> 
                            </label>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">More Options</h6>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Excerpt</label>
                            <textarea name="excerpt" class="form-control" placeholder="Write an excerpt"></textarea>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Featured</label>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span></span> 
                            </label>
                        </div>
                        <div class="form-group mb-0">
                            <label class="text-muted small">DISCUSSION</label>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center">
                            <label class="mb-0">Allow Comments</label>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span></span> 
                            </label>
                        </div>
                        <div class="form-group d-flex justify-content-between align-items-center mb-0">
                            <label class="mb-0">Allow Pingbacks &amp; Trackbacks</label>
                            <label class="switch">
                                <input type="checkbox" checked>
                                <span></span> 
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>