<!DOCTYPE html>
<html>
<head>
    <title><?php echo $page->title; ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $meta; ?>
    <?php echo $assets->head; ?>
</head>
<body class="admin-ui fix-header fix-sidebar">
    <form id="form-pages" action="<?php echo base_url('pages/form'); ?>" method="post" role="form" enctype="multipart/form-data">
        <header class="header">
            <?php echo $partials->header; ?>
        </header>

        <main class="main bg-white ml-0">
            <div class="container-fluid">
                <?php echo $partials->content; ?>
            </div>
        </main>
    </form>
    <?php echo $assets->body; ?>
</body>
</html>