<div class="page-system">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">Companies</h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <div class="dropdown">
                                            <a class="btn btn-default dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <?php echo $language->getLine('MANAGE'); ?>
                                            </a>
                                            <div class="dropdown-menu">
                                                <a href="<?= base_url('/companies'); ?>" class="dropdown-item">
                                                    <?php echo $language->getLine('COMPANIES'); ?>
                                                </a>
                                                <a href="<?= base_url('/companies/table'); ?>" class="dropdown-item">
                                                    <?php echo $language->getLine('TABLE'); ?>
                                                </a>
                                                <a href="<?= base_url('/companies/categories'); ?>" class="dropdown-item">
                                                    <?php echo $language->getLine('COMPANIES_CATEGORIES'); ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-auto">
                                        <a href="<?=base_url('/companies/form');?>" class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?=current_url();?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <?php foreach($entries as $entry): ?>
                                                    <option value="<?php echo $entry; ?>" <?php echo ($get->entries == $entry ? 'selected' : ''); ?>><?php echo $entry; ?></option>
                                                <?php endforeach; ?>
                                                <option value="ALL" <?= ($get->entries ? (!is_numeric($get->entries) ? 'selected' : '') : '') ?>><?php echo $language->getLine('ALL') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Period</span>
                                            </div>
                                            <input class="form-control input-daterange-datepicker-empty" type="text" name="period" value="<?= ($get->period ? $get->period : '') ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Company Name" value="<?= ($get->keyword ? $get->keyword : '') ?>" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="<?= base_url('companies') ?>">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <?php if ($companies): ?>
                <?php foreach ($companies as $company): ?>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="card">
                            <div class="card-body text-center pt-0">
                                <div class="dropdown text-right">
                                    <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="<?php echo base_url('companies/form/'.$company->id); ?>">
                                            <i class="fas fa-pencil-alt"></i>
                                            Edit
                                        </a>
                                        <a class="dropdown-item" href="<?=base_url('companies/overview/'.$company->id);?>">
                                            <i class="fa fa-eye"></i>
                                            View
                                        </a>
                                        <!-- <a class="dropdown-item" href="#">
                                            <i class="fas fa-chart-bar"></i>
                                            Stats
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            <i class="fa fa-copy"></i>
                                            Copy
                                        </a> -->
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="<?php echo base_url('companies/delete/'.$company->id); ?>">
                                            <i class="fa fa-trash"></i>
                                            Trash
                                        </a>
                                    </div>
                                </div>
                                <div class="avatar-80 mb-2 mx-auto">
                                    <img src="<?= $company->image ?>" alt="">
                                </div>
                                <span class="btn btn-default btn-xs text-uppercase"><?= ($company->category ? $company->category->title : '') ?></span>
                                <h4 class="mb-2">
                                    <a href="<?=base_url('companies/overview/'.$company->id);?>"><?= $company->name ?></a>
                                </h4>
                                <?php if ($company->contact): ?>
                                    <h6 class="mb-0"><?= $company->contact->name ?></h6>
                                    <p><?= $company->contact->job_title ?></p>
                                <?php endif; ?>
                                
                                <?php if ($company->metadata('email')): ?>
                                <a href="mailto:<?= $company->metadata('email')->email ?>" class="btn btn-default btn-sm">
                                    <?= $company->metadata('email')->email ?>
                                </a>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
        <?php if ($companies): ?>
            <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('companies', [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('companies', [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $companies->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="period" value="<?= $get->period ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $companies->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$companies->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
        <?php endif ?>
    </div>
</div>