<div class="page-master">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- Standard -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Basic Tables</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Using the most basic table up, here’s how
                        
                            <code>.table</code>-based tables look in Bootstrap. You can use any example
                        of below table for your table and it can be use with any type of bootstrap tables.
                        </p>
                        <p>
                            <span class="text-bold-600">Example 1:</span> Table with outer spacing
                        </p>
                        <!-- Table with outer spacing -->
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>NAME</th>
                                        <th>RATE</th>
                                        <th>SKILL</th>
                                        <th>TYPE</th>
                                        <th>LOCATION</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="text-bold-500">Michael Right</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">UI/UX</td>
                                        <td>Remote</td>
                                        <td>Austin,Taxes</td>
                                        <td>
                                            <a href="#" class="btn btn-default btn-sm">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Morgan Vanblum</td>
                                        <td>$13/hr</td>
                                        <td class="text-bold-500">Graphic concepts</td>
                                        <td>Remote</td>
                                        <td>Shangai,China</td>
                                        <td>
                                            <a href="#" class="btn btn-default btn-sm">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Tiffani Blogz</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#" class="btn btn-default btn-sm">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Ashley Boul</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#" class="btn btn-default btn-sm">
                                               <i class="fas fa-envelope"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#" class="btn btn-default btn-sm">
                                               <i class="fas fa-envelope"></i>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <p class="px-2">
                        <span class="text-bold-600">Example 2:</span> Minimal Table with no outer spacing.
                    </p>
                    <!-- Table with no outer spacing -->
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead>
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                           <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                           <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                           <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                           <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                           <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <!-- Inverse -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Inverse table</h4>
                    </div>
                    <p class="p-2">You can also invert the colors—with light text on dark backgrounds—with 
                        <code>.table-dark</code>.
                    </p>
                    <!-- table with dark -->
                    <div class="table-responsive">
                        <table class="table table-dark mb-0">
                            <thead>
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <p class="p-2">You can also invert the colors—with dark text on light backgrounds—with 
                        <code>.table-light</code>.
                    </p>
                    <!-- table with light -->
                    <div class="table-responsive">
                        <table class="table table-light mb-0">
                            <thead>
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#" class="btn btn-default btn-sm">
                                            <i class="fas fa-envelope"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Table head options</h4>
                    </div>
                    <div class="card-body">
                        <p>Similar to tables and dark tables, use the modifier classes 
                            <code>.thead-light</code> or 
                            <code>.thead-dark</code> to
                        make 
                            <code>thead</code>s appear light or dark gray.
                        </p>
                    </div>
                    <!-- table head dark -->
                    <div class="table-responsive">
                        <table class="table mb-0">
                            <thead class="thead-dark">
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Striped rows</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <p class="card-text">Use 
                                <code class="highlighter-rouge">.table-striped</code> to add zebra-striping to any
                            table row within the 
                                <code class="highlighter-rouge">tbody</code>. This styling doesn't work in IE8
                            and below as 
                                <code>:nth-child</code> CSS selector isn't supported.
                            </p>
                        </div>
                        <!-- table striped -->
                        <div class="table-responsive">
                            <table class="table table-striped mb-0">
                                <thead>
                                    <tr>
                                        <th>NAME</th>
                                        <th>RATE</th>
                                        <th>SKILL</th>
                                        <th>TYPE</th>
                                        <th>LOCATION</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="text-bold-500">Michael Right</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">UI/UX</td>
                                        <td>Remote</td>
                                        <td>Austin,Taxes</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Morgan Vanblum</td>
                                        <td>$13/hr</td>
                                        <td class="text-bold-500">Graphic concepts</td>
                                        <td>Remote</td>
                                        <td>Shangai,China</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Tiffani Blogz</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Ashley Boul</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Striped inverse dark</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <p class="card-text">Use 
                                <code>.table-dark</code> with 
                                <code>.table-striped</code> to add zebra-striping to
                            any inverse table row within the 
                                <code>tbody</code>. This styling doesn't work in IE8 and below as
                            
                                <code>:nth-child</code> CSS selector isn't supported.
                            </p>
                        </div>
                        <!-- table strip dark -->
                        <div class="table-responsive">
                            <table class="table table-striped table-dark mb-0">
                                <thead>
                                    <tr>
                                        <th>NAME</th>
                                        <th>RATE</th>
                                        <th>SKILL</th>
                                        <th>TYPE</th>
                                        <th>LOCATION</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="text-bold-500">Michael Right</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">UI/UX</td>
                                        <td>Remote</td>
                                        <td>Austin,Taxes</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Morgan Vanblum</td>
                                        <td>$13/hr</td>
                                        <td class="text-bold-500">Graphic concepts</td>
                                        <td>Remote</td>
                                        <td>Shangai,China</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Tiffani Blogz</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Ashley Boul</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Bordered table</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Add 
                            <code>.table-bordered</code> for borders on all sides of the table and cells. For
                        Inverse Dark Table, add 
                            <code>.table-dark</code> along with 
                            <code>.table-bordered</code>.
                        </p>
                    </div>
                    <!-- table bordered -->
                    <div class="table-responsive">
                        <table class="table table-bordered mb-0">
                            <thead>
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Borderless Table</h4>
                    </div>
                    <div class="card-body">
                        <p class="card-text">Add 
                            <code>.table-borderless</code> for a table without borders. It can also be used on
                        dark tables.
                        </p>
                    </div>
                    <!-- table with no border -->
                    <div class="table-responsive">
                        <table class="table table-borderless mb-0">
                            <thead>
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Hoverable rows</h4>
                    </div>
                    <div class="card-body">
                        <p>Add 
                            <code class="highlighter-rouge">.table-hover</code> to enable a hover state on table rows within a
                        
                            <code class="highlighter-rouge">tbody</code>.
                        </p>
                    </div>
                    <!-- table hover -->
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                                <tr>
                                    <th>NAME</th>
                                    <th>RATE</th>
                                    <th>SKILL</th>
                                    <th>TYPE</th>
                                    <th>LOCATION</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-bold-500">Michael Right</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">UI/UX</td>
                                    <td>Remote</td>
                                    <td>Austin,Taxes</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Morgan Vanblum</td>
                                    <td>$13/hr</td>
                                    <td class="text-bold-500">Graphic concepts</td>
                                    <td>Remote</td>
                                    <td>Shangai,China</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Tiffani Blogz</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Ashley Boul</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-bold-500">Mikkey Mice</td>
                                    <td>$15/hr</td>
                                    <td class="text-bold-500">Animation</td>
                                    <td>Remote</td>
                                    <td>Austin,Texas</td>
                                    <td>
                                        <a href="#">
                                            <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Contextual classes</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <p>Use contextual classes to color table rows or individual cells. Read full documnetation 
                                <a href="https://getbootstrap.com/docs/4.3/content/tables/#contextual-classes" target="_blank">here.</a>
                            </p>
                        </div>
                        <!-- table contextual / colored -->
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead>
                                    <tr>
                                        <th>NAME</th>
                                        <th>RATE</th>
                                        <th>SKILL</th>
                                        <th>TYPE</th>
                                        <th>LOCATION</th>
                                        <th>ACTION</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="table-active">
                                        <td class="text-bold-500">Michael Right</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">UI/UX</td>
                                        <td>Remote</td>
                                        <td>Austin,Taxes</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-primary">
                                        <td class="text-bold-500">Morgan Vanblum</td>
                                        <td>$13/hr</td>
                                        <td class="text-bold-500">Graphic concepts</td>
                                        <td>Remote</td>
                                        <td>Shangai,China</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-secondary">
                                        <td class="text-bold-500">Tiffani Blogz</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-success">
                                        <td class="text-bold-500">Ashley Boul</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-danger">
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-warning">
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-info">
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-light">
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <tr class="table-dark">
                                        <td class="text-bold-500">Mikkey Mice</td>
                                        <td>$15/hr</td>
                                        <td class="text-bold-500">Animation</td>
                                        <td>Remote</td>
                                        <td>Austin,Texas</td>
                                        <td>
                                            <a href="#">
                                                <i class="badge-circle badge-circle-light-secondary bx bx-envelope font-medium-1"></i>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>