<div class="container-fluid">
    <form id="form-data" method="post" action="" enctype="multipart/form-data">
        <div class="card">
            <h5 class="card-header d-flex justify-content-between align-items-center">
                <?php echo $page->title; ?>

                <div class="card-options">
                    <button type="button" class="btn btn-default btn-md" data-action="cancel">
                        <?php echo $language->getLine('BTN_CANCEL'); ?>
                    </button>
                    <button type="submit" class="btn btn-primary btn-md">
                        <?php echo $language->getLine('BTN_SAVE'); ?>
                    </button>
                </div>
            </h5>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <h5 class="card-header">Caption</h5>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Title</label>
                            <input class="form-control" type="text" name="title" value="">
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea class="form-control" name="content"></textarea>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <h5 class="card-header">
                        Images/Videos
                    </h5>
                    <div class="card-body p-0">
                        <div id="dropzone-cards" data-action-url="\" data-allowed="image/*, .mp4, .webm, .ogg" data-max-files="1" data-max-size="">
                            <div class="media-list">
                                <div class="dropzone-form" id="dropzone-cards-form" style="cursor: pointer;">
                                    <div class="dz-message needsclick">
                                        <p>Drop files here or click to upload.<br>
                                            <span class="note needsclick">
                                                (This is NOT just a demo dropzone. Selected files are
                                                <strong>ACTUALLY</strong> uploaded.)
                                            </span>
                                        </p>
                                    </div>
                                    <div class="dropzone-previews" id="dropzone-previews">
                                        <div class="dz-template" id="dropzone-cards-template">
                                            <div class="media-list-item uploading">
                                                <div class="media-list-action d-flex">
                                                    <button type="button" class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal"
                                                        data-target="#modal-edit">Edit</button>
                                                    <button type="button" class="btn btn-danger btn-xs">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </div>
                                                
                                                <input type="checkbox" id="media-1">
                                                <label class="media-item" for="media-1">
                                                    <img data-dz-thumbnail>
                                                    <div class="media-item-file-details">
                                                        <div class="media-item-icon">
                                                            <i class="fas fa-file-powerpoint"></i>
                                                        </div>
                                                        <div class="media-item-file-name" data-dz-name></div>
                                                        <div class="media-item-file-extension"></div>
                                                    </div>
                                                </label>
        
                                                <div class="upload-progress">
                                                    <div class="progress">
                                                        <div class="progress-bar progress-bar-striped progress-bar-animated"
                                                            role="progressbar" aria-valuenow="75" aria-valuemin="0"
                                                            aria-valuemax="100" style="width: 0%" data-dz-uploadprogress></div>
                                                    </div>
                                                </div>
        
                                                <div class="media-item-file-error">
                                                    <div class="media-item-icon-error">
                                                        <i class="fas fa-exclamation-circle"></i>
                                                    </div>
                                                    <div class="media-item-file-name-error" data-dz-errormessage></div>
                                                    <div class="media-item-file-extension-error d-flex justify-content-center">
                                                        <button type="button" class="btn btn-outline-light btn-sm"
                                                            data-dz-remove>
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
        
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label>Status</label>
                            <select class="custom-select form-control" name="record_status">
                                <option>Publish</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Visibility</label>
                            <select class="custom-select form-control" name="visibility">
                                <option>Public</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">
                        Taxonomies
                    </h6>
                    <div class="card-body">
                        <div class="form-group">
                            <input type="hidden" name="id_taxonomy" value=">
                            <input type="text" class="form-control" readonly value="Banner">
                        </div>
                    </div>
                </div>

                <div class="card">
                    <h6 class="card-header">
                        Tags
                    </h6>
                    <div class="card-body">
                        <div class="form-group mb-0">
                            <input type="text" name="tags[name]" data-role="tagsinput" value="" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>