<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <div class="card">
                <div class="card-header d-flex flex-wrap align-items-center justify-content-between p-0">
                    <div class="nav-pages">    
                        <ul class="nav" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#install-computer" role="tab" aria-controls="install-computer" aria-selected="true">Install From Computer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#install-folder" role="tab" aria-controls="install-folder" aria-selected="false">Install From Folder</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#install-url" role="tab" aria-controls="install-url" aria-selected="false">Install From URL</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <div class="tab-content p-0 border-0 mb-0">
                        <div class="tab-pane active" id="install-computer" role="tabpanel" aria-labelledby="install-computer">
                            <form>
                                <input type="hidden" value="http://example.com/action" name="dropzone-url">
                                <div class="media-list">
                                    <div class="dropzone-form" style="cursor: pointer;">
                                        <div class="dz-message needsclick">
                                            <p>Drop files here or click to upload.<br>
                                                <span class="note needsclick">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span></p>
                                        </div>
                                        <div class="dropzone-previews" id="dropzone-previews">
                                            <div class="dz-template" id="dropzone-preview">
                                                <div class="media-list-item uploading">
                                                    <div class="media-list-action d-flex">
                                                        <button type="button" class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal" data-target="#modal-edit">Edit</button>
                                                        <button type="button" class="btn btn-danger btn-xs">
                                                            <i class="fas fa-trash"></i>
                                                        </button>
                                                    </div>

                                                    <div class="media-item">
                                                        <img data-dz-thumbnail>
                                                        <div class="media-item-file-details">
                                                            <div class="media-item-icon">
                                                                <i class="fas fa-file-powerpoint"></i>
                                                            </div>
                                                            <div class="media-item-file-name" data-dz-name></div>
                                                            <div class="media-item-file-extension"></div>
                                                        </div>
                                                    </div>

                                                    <div class="upload-progress">
                                                        <div class="progress">
                                                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 0%" data-dz-uploadprogress></div>
                                                        </div>
                                                    </div>

                                                    <div class="media-item-file-error">
                                                        <div class="media-item-icon-error">
                                                            <i class="fas fa-exclamation-circle"></i>
                                                        </div>
                                                        <div class="media-item-file-name-error" data-dz-errormessage></div>
                                                        <div class="media-item-file-extension-error d-flex justify-content-center">
                                                            <button type="button" class="btn btn-outline-light btn-sm" data-dz-remove>
                                                                <i class="fas fa-trash"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane" id="install-folder" role="tabpanel" aria-labelledby="install-folder">
                            <form>
                                <div class="input-group">
                                    <input class="form-control" placeholder="var/www/" type="text">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary">Check &amp; Install</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane" id="install-url" role="tabpanel" aria-labelledby="install-url">
                            <form>
                                <div class="input-group">
                                    <input class="form-control" placeholder="https://" type="text">
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-primary">Check &amp; Install</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#install1" role="tab">Install From URL</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#install2" role="tab">Install From Folder</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#install3" role="tab">Install From Computer</a>
            </li>
        </ul>
        <div class="tab-content tabs bg-white p-3">
            <div class="tab-pane active" id="install1" role="tabpanel">
                <form>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Install From URL</label>
                        <div class="col-sm-9">
                            <input class="form-control" placeholder="https://" type="text">
                        </div>
                    </div>
                    <div class="form-group row mb-0">
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn btn-primary">Check and Install</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane" id="install2" role="tabpanel">
                <form>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Install From Folder</label>
                        <div class="col-sm-9">
                            <input class="form-control" placeholder="var/www/" type="text">
                        </div>
                    </div>
                    <div class="form-group row mb-0">
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn btn-primary">Check and Install</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane" id="install3" role="tabpanel">
                <form class="form-horizontal" action="data/upload-file.php">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="dropzone" id="dropzone-wrap">
                                <div class="fallback">
                                    <input name="file" type="file" multiple />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 mt-3 hidden" id="dze_info">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th width="40%">File name</th>
                                        <th width="15%">Size</th>
                                        <th width="15%">Type</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="4"></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>