<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h3 class="mb-4"><?php echo language('PAGES'); ?></h3>
                    </div>
                    <div class="col-auto ml-auto">
                        <a href="<?php echo base_url('pages/form');?>" class="btn btn-primary btn-md mb-4">
                            <?php echo language('BTN_ADD_NEW_PAGE'); ?>
                        </a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">    
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === '' ? 'active': ''); ?>>" href="<?php echo base_url('pages');?>">
                                        <?php echo language('PUBLISHED'); ?>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === 'UNPUBLISH' ? 'active': ''); ?>>" href="<?php echo base_url('pages', ['status' => 'UNPUBLISH']);?>">
                                        <?php echo language('UNPUBLISHED'); ?>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === 'DRAFT' ? 'active': ''); ?>" href="<?php echo base_url('pages', ['status' => 'DRAFT']);?>">
                                        <?php echo language('DRAFTS'); ?>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === 'ARCHIVE' ? 'active': ''); ?>>" href="<?php echo base_url('pages', ['status' => 'ARCHIVE']);?>">
                                        <?php echo language('ARCHIVES'); ?>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === 'DELETED' || input()->get('status') === '' ? 'active': ''); ?>" href="<?php echo base_url('pages', ['status' => 'DELETED']);?>">
                                        <?php echo language('TRASH'); ?>
                                    </a>
                                </li>
                            </ul>
                            <form class="nav-search" action="<?php echo current_url(); ?>" method="get">
                                <div class="search-icon open-search">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="search-input">
                                    <input type="search" name="keyword" placeholder="<?php echo language('SEARCH'); ?>..." value="<?php echo input()->get('keyword'); ?>">
                                </div>
                                <div class="search-icon close-search">
                                    <i class="fas fa-times"></i>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="post-list">

                    <?php if($pages->first()): ?>
                    
                    <div class="list-group mb-3">
                        <?php foreach($pages as $page): ?>
                            <div class="list-group-item">
                                <div class="post-item">
                                    <div class="post-item-detail">
                                        <a href="<?php echo base_url('pages/form/' . $page->id, ['record_language' => $page->record->language]);?>">
                                            <h1>
                                                <?php echo $page->title; ?>
                                            </h1>
                                        </a>
                                        <div class="post-item-meta">
                                            <span class="post-time">
                                                <?php echo $page->record->create->timestamp->format('M j, Y H:i a'); ?>
                                            </span>
                                        </div>
                                    </div>
                                    <?php if(!empty($page->image)): ?>
                                        <div class="post-thumbnail">
                                            <a href="<?php echo base_url('pages/form/' . $page->id, ['record_language' => $page->record->language]);?>">
                                                <img src="<?php echo $page->image_url; ?>">
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                    <div class="post-action">
                                        <div class="dropdown">
                                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="<?php echo base_url('pages/form/' . $page->id, ['record_language' => $page->record->language]);?>">
                                                    <i class="fas fa-pencil-alt"></i>
                                                    <?php echo language('BTN_EDIT'); ?>
                                                </a>
                                                <div class="dropdown-divider"></div>
                                                <?php if(input()->get('status') === 'PUBLISH'): ?>
                                                    <a class="dropdown-item" href="<?php echo base_url('pages/unpublish/' . $page->id, ['record_language' => $page->record->language]);?>">
                                                        <i class="fas fa-eye-slash"></i>
                                                        <?php echo language('UNPUBLISH'); ?>
                                                    </a>
                                                <?php elseif(input()->get('status') === 'UNPUBLISH' || input()->get('status') === 'DRAFT'): ?>
                                                    <a class="dropdown-item" href="<?php echo base_url('pages/publish/' . $page->id, ['record_language' => $page->record->language]);?>">
                                                        <i class="fas fa-eye"></i>
                                                        <?php echo language('PUBLISH'); ?>
                                                    </a>
                                                <?php elseif(input()->get('status') === 'ARCHIVE' || input()->get('status') === 'TRASH'): ?>
                                                    <a class="dropdown-item" href="<?php echo base_url('pages/restore/' . $page->id, ['record_language' => $page->record->language]);?>">
                                                        <i class="fas fa-recycle"></i>
                                                        <?php echo language('RESTORE'); ?>
                                                    </a>
                                                <?php endif; ?>
                                                <a class="dropdown-item" href="<?php echo base_url('pages/delete/' . $page->id);?>" data-id="<?php echo $page->id; ?>" data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                    <?php echo language('BTN_DELETE'); ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <?php else: ?>
                        <div class="alert alert-info"><?php echo language('NO_DATA'); ?></div>
                    <?php endif; ?>
                </div>

                <?php echo $pages->pagination(); ?>
            </div>
        </div>
    </div>
</div>