<div class="page-wrapper">
	<div class="container-fluid">
		<div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0"><?=$page->title;?></h5>
                            </div>
                            <div class="col-auto">
                                <a href="<?php echo base_url('site/posts/form'); ?>" class="btn btn-primary btn-md">
                                    <?=language('BTN_ADD_NEW')?>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">    
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link <?=$get->status === 'PUBLISH' ? 'active' : '' ?>" href="<?=base_url('site/media',[
                                        'status'    => 'PUBLISH'
                                    ]);?> href="#">Published</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?=$get->status === 'UNPUBLISH' ? 'active' : '' ?>" href="<?=base_url('site/media',[
                                            'status'    => 'UNPUBLISH'
                                    ]);?>">Trash</a>
                                </li>
                            </ul>

                            <form class="nav-search">
                                <div class="search-icon open-search">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="search-input">
                                    <input type="search" placeholder="Search...">
                                </div>
                                <div class="search-icon close-search">
                                    <i class="fas fa-times"></i>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="dropzone-cards" data-action-url="<?=base_url('site/media/upload');?>" data-allowed="" data-max-files="" data-max-size="">
            <div class="media-list">
                <div class="dropzone-form <?php echo  $medias ? 'dz-started' : ''?>" id="dropzone-cards-form" style="cursor: pointer;">
                    <div class="dz-message needsclick">
                        <p>Drop files here or click to upload.<br>
                            <span class="note needsclick">
                                (This is just a demo dropzone. Selected files are
                                <strong>not</strong> actually uploaded.)
                            </span>
                        </p>
                    </div>
                    <div class="dropzone" id="dropzone-previews">
                        <div class="dz-template" id="dropzone-cards-template">
                            <div class="media-list-item uploading">
                                <div class="media-list-action d-flex">
                                    <button type="button"  class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal"
                                        data-target="#modal-edit">Edit</button>
                                    <button type="button" class="btn btn-danger btn-xs">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>
                                
                                <input type="checkbox" id="media-1">
                                <label class="media-item" for="media-1">
                                    <img data-dz-thumbnail>
                                    <div class="media-item-file-details">
                                        <div class="media-item-icon">
                                            <i class="fas fa-file-powerpoint"></i>
                                        </div>
                                        <div class="media-item-file-name" data-dz-name></div>
                                        <div class="media-item-file-extension"></div>
                                    </div>
                                </label>

                                <div class="upload-progress">
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-striped progress-bar-animated"
                                            role="progressbar" aria-valuenow="75" aria-valuemin="0"
                                            aria-valuemax="100" style="width: 0%" data-dz-uploadprogress></div>
                                    </div>
                                </div>

                                <div class="media-item-file-error">
                                    <div class="media-item-icon-error">
                                        <i class="fas fa-exclamation-circle"></i>
                                    </div>
                                    <div class="media-item-file-name-error" data-dz-errormessage></div>
                                    <div class="media-item-file-extension-error d-flex justify-content-center">
                                        <button type="button" class="btn btn-outline-light btn-sm"
                                            data-dz-remove>
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php if($medias):?>
                        <?php foreach ($medias as $key => $media):?>
                            <div class="dz-template">
                            <div class="media-list-item uploading">
                                <div class="media-list-action d-flex">
                                    <button type="button" data-media ="<?php echo $media->id;?>" class="btn btn-info btn-xs btn-edit mr-2" data-toggle="modal"
                                            data-target="#modal-edit">Edit</button>
                                    <button type="button" class="btn btn-danger btn-delete-media btn-xs" data-delete="<?=$media->id;?>">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>

                                <input type="checkbox" id="media-<?=$key;?>">
                                <label class="media-item" for="media-<?=$key;?>">
                                    <?php if($media->mime === 'IMAGE'):?>
                                    <img src="<?=$media->path;?>">
                                    <?php else:?>
                                    <div class="media-item-file-details">
                                        <div class="media-item-icon">
                                            <i class="fas fa-file-powerpoint"></i>
                                        </div>
                                        <div class="media-item-file-name">
                                            <?php echo $media->filename;?>
                                        </div>
                                        <div class="media-item-file-extension"></div>
                                    </div>
                                    <?php endif;?>
                                </label>


                                <div class="media-item-file-error">
                                    <div class="media-item-icon-error">
                                        <i class="fas fa-exclamation-circle"></i>
                                    </div>
                                    <div class="media-item-file-name-error" data-dz-errormessage></div>
                                    <div class="media-item-file-extension-error d-flex justify-content-center">
                                        <button type="button" class="btn btn-outline-light btn-sm"
                                                data-dz-remove>
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endforeach;?>
                    <?php endif;?>
                </div>
            </div>
        </div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade modal-scroll" id="modal-edit" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modalEdit" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <form id="form-media">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEdit">Media Edit</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="media-editor-wrapper">
                                <img src="assets/img/cover.jpg">
                            </div>
                        </div>
                        <input type="hidden" name="name" value="info">
                        <input type="hidden" name="id_media">
                        <div class="col-sm-5">
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" class="form-control" name="content[title]" id="title">
                            </div>
                            <div class="form-group">
                                <label>Caption</label>
                                <textarea class="form-control" name="content[caption]" id="caption"></textarea>
                            </div>
                            <div class="form-group">
                                <label>Alt Text</label>
                                <input type="text" class="form-control" name="content[alt_text]" id="alt_text">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control" name="content[description]" id="description"></textarea>
                            </div>
                            <div class="form-group">
                                <label>URL</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="url" readonly="">
                                    <div class="input-group-append">
                                        <button type="button" class="btn btn-default">Copy</button>
                                    </div>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table file-info">
                                    <tr>
                                        <td width="50%" class="border-0">
                                            <span class="text-muted" >File Name</span><br>
                                            <span id="filename"></span>
                                        </td>
                                        <td class="border-0">
                                            <span class="text-muted">File Type</span><br>
                                            <span id="mime"></span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="border-0">
                                            <span class="text-muted">Upload Date</span><br>
                                            <span id="record_create"></span>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(".btn-delete-media").on('click', function () {
        var template = ($(this).parents('.dz-template'));
        Swal.fire({
            title: "Are you sure?",
            text: "You won't be able to revert this!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!"
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    url: "<?=domain_url('media/unpublish',null,'api');?>?id="+$(this).data('delete'),
                    type: "POST",
                    data:'id='+$(this).data('delete'),
                    dataType:'JSON',
                    success: function(){
                        template.remove();
                        Swal.fire("Success", "Your file has been deleted :)", "success");
                    }
                })
            } else {
                Swal.fire("Cancelled", "Your file is safe :)", "error");
            }
        });
    });

    $('#form-media').on('submit', function (e) {
        e.preventDefault();
        var data = $(this).serialize();
        console.log(data);
        $.ajax({
            url: "<?=domain_url('media/metadata/update',null,'api');?>",
            type: "POST",
            data:data,
            dataType:'JSON',
            success: function(){
                $('#modal-edit').hide();
                Swal.fire("Success", "Your file has been updated :)", "success");
            }
        })
    });

    $('.btn-edit').on('click', function () {
        $.ajax({
            url: "<?=domain_url('media',null,'api');?>?id="+$(this).data('media'),
            type: "GET",
            dataType:'JSON',
            success: function(respons){
                var data = respons.result[0];
                var modal = $('#modal-edit');
                modal.find('img').attr('src', data.path);
                modal.find('#title').val(data.metadata.title);
                modal.find('#caption').val(data.metadata.caption);
                modal.find('#alt_text').val(data.metadata.alt_text);
                modal.find('#description').val(data.metadata.description);
                modal.find('[name=url]').val(data.path);
                modal.find('[name=id_media]').val(data.id);
                modal.find('#filename').text(data.filename);
                modal.find('#mime').text(data.mime);
                modal.find('#record_create').text(data.record_create_timestamp);
                console.log(data);
            }
        })
    });

</script>


