<div class="card">
    <div class="card-body p-0">
        <div class="nav-pages">    
            <ul class="nav" id="nav-settings">
                <li class="nav-item">
                    <a class="nav-link" href="<?=base_url('site/settings');?>">General</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?=base_url('site/settings/contents');?>">Contents</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?=base_url('site/settings/discussion');?>">Discussion</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<script>
    var current_url = "<?= current_url(); ?>";
    var activeSlug = $('#nav-settings li a[href="'+ current_url +'"]');

    activeSlug.addClass('active');
</script>