<nav class="navbar top-navbar navbar-expand-md navbar-light">
    <!-- Logo -->
    <div class="navbar-brand">
        <div class="navbar-collapse">
            <ul class="navbar-nav mr-auto mt-md-0 ">
                <li class="nav-item">
                    <a href="{{base_url()}}">
                        <img src="./assets/img/logo/logo-50px.png" alt="logo" />
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav my-lg-0">
                <li class="nav-item">
                    <a class="nav-link 480px" href="javascript:void(0)">
                        <i class="fas fa-mobile"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link 768px" href="javascript:void(0)">
                        <i class="fas fa-tablet"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link reset" href="javascript:void(0)">
                        <i class="fas fa-desktop"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!-- End Logo -->
    <div class="navbar-collapse">
        <!-- toggle and nav items -->
        <ul class="navbar-nav mr-auto mt-md-0 ">
            <!-- This is  -->
            <li class="nav-item">
                <a class="nav-link nav-toggler d-md-none d-block text-muted" href="javascript:void(0)"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link sidebartoggler d-none d-md-none text-muted" href="javascript:void(0)"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item">
                <a class="btn btn-default" href="javascript:void(0)">
                    Preview
                </a>
            </li>
            <li class="nav-item ml-2">
                <button type="submit" class="btn btn-primary" href="javascript:void(0)">
                    Save
                </button>
            </li>
        </ul>

        <ul class="navbar-nav my-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{{base_url('appearance')}}">
                    <small>Back to Appearance</small>
                </a>
            </li>
        </ul>
    </div>
</nav>