<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Published</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Trash</a>
                            </li>
                        </ul>

                        <form class="nav-search">
                            <div class="search-icon open-search">
                                <i class="fas fa-search"></i>
                            </div>
                            <div class="search-input">
                                <input type="search" placeholder="Search...">
                            </div>
                            <div class="search-icon close-search">
                                <i class="fas fa-times"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="themes-list">
                <div class="row">
                    <?php foreach ($themes as $theme) : ?>
                        <div class="col-md-4 col-sm-6">
                            <div class="card">
                                <div class="theme-img">
                                    <img class="card-img-top" src="<?php echo $theme->screenshot; ?>" alt="<?php echo $theme->name; ?>">
                                </div>
                                <div class="card-body p-3">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <h6 class="card-title mb-0 font-weight-bold"><?php echo $theme->name; ?></h6>
                                        <div class="dropdown">
                                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="<?php echo current_url('process'); ?>?theme=<?php echo $theme->name ?>" data-action="activate">
                                                    <i class="fas fa-check-circle"></i>
                                                    <?php echo language('ACTIVATE'); ?>
                                                </a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void (0);" data-action="uninstall">
                                                    <i class="fa fa-trash"></i>
                                                    <?php echo language('UNINSTALL'); ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <p class="mb-0">
                                        <i class="fas fa-clock"></i> <?php echo date('M j, Y H:i a', strtotime($theme->created)); ?> &middot; <i class="fas fa-code-branch"></i> v<?php echo $theme->version; ?> &middot; <i class="fas fa-copyright"></i>
                                        <?php if (isset($theme->author['website'])) : ?>
                                            <a href="<?php echo $theme->author['website']; ?>" target="_blank"><?php echo $theme->author['name']; ?></a>
                                        <?php elseif (isset($theme->author['email'])) : ?>
                                            <a href="mailto:<?php echo $theme->author['email']; ?>"><?php echo $theme->author['name']; ?></a>
                                        <?php else : ?>
                                            <?php echo $theme->author['name']; ?>
                                        <?php endif; ?>
                                    </p>

                                    <?php if ($settings->theme == $theme->name) :?>
                                        <span class="badge badge-success mt-4">Current Theme</span>    
                                    <?php endif;?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>