<nav class="navbar top-navbar navbar-expand-md navbar-light">
    <!-- Logo -->
    <div class="navbar-brand border-0">
        <div class="navbar-collapse">
           <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo base_url('pages'); ?>">
                        <i class="fas fa-times"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!-- End Logo -->
    <div class="navbar-collapse">
        <!-- toggle and nav items -->
        <ul class="navbar-nav mr-auto mt-md-0 ">
            <!-- This is  -->
            <li class="nav-item">
                <a class="nav-link nav-toggler d-md-none d-block text-muted" href="javascript:void(0)"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link sidebartoggler d-none d-md-none text-muted" href="javascript:void(0)"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <ul class="navbar-nav my-lg-0">
            <li class="nav-item">
                <a class="btn btn-default" href="javascript:void(0)" data-action="preview">
                    Preview
                </a>
            </li>
            <li class="nav-item ml-2">
                <button type="submit" class="btn btn-primary" value="save" data-action="save">
                    Save
                </button>
            </li>
        </ul>        
    </div>
</nav>