<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
        	<div class="card-header">Server Config</div>
            <div class="card-body">
            	<form>
	            	<div class="row">
	            		<div class="col-md-6">
	            			<h6>Server Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Path to Temp Folder</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="home/public_html">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Gzip Page Compression</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Error Reporting</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>System Default</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Force HTTPS</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>None</option>
							      	</select>
							    </div>
							</div>

							<h6 class="mt-5">Locations Setting</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Server Time Zone</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>Indonesia</option>
							      	</select>
							    </div>
							</div>

							<h6 class="mt-5">FTP Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Enable FTP</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>

							<h6 class="mt-5">Proxy Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Enable Proxy</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>
	            		</div>
	            		<div class="col-md-6">
	            			<h6>Database Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Database Type</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>MySQLi</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Host</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="localhost">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Database Username</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Database Name</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Database Tables Prefix</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>

							<h6 class="mt-5">Mail Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Send Mail</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Disable Mass Mail</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">From Email</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Reply To Email</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Reply To Name</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Mailer</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>PHP Mail</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
							    <div class="col-sm-12">
							    	<button class="btn btn-default">Send Test Mail</button>
							    </div>
							</div>
	            		</div>
	            	</div>
	            </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>