<div class="header-left">
	<div class="logo-large">
		<img src="assets/img/logo/logo-rectangle.png">
	</div>
	<div class="logo-mini">
		<img src="assets/img/logo/logo-square.png">
	</div>
</div>
<div class="header-right">
	<nav class="navbar navbar-light navbar-expand-sm">
		<div class="navbar-collapse">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="javascript:void(0);" data-toggle="sidebar-left"><i class="fas fa-bars"></i></a>
				</li>
			</ul>

			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdownLanguage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="flag-icon flag-icon-us"></i>
					</a>
					<div class="dropdown-menu" aria-labelledby="dropdownLanguage">
						<a class="dropdown-item" href="#"><i class="flag-icon flag-icon-id"></i> Indonesia</a>
						<a class="dropdown-item" href="#"><i class="flag-icon flag-icon-us"></i> English</a>
					</div>
				</li>

		      	<li class="nav-item dropdown d-none" onload="loadNotifications">
			        <a class="nav-link dropdown-toggle remove-caret" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          	<i class="fas fa-bell"></i>
			          	<span class="notify d-none"></span>
			        </a>
			        <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg py-0" aria-labelledby="navbar-notifications">
			          	<div class="dropdown-item-header">
			          		<p>Notification
				                <span>({{notifications.num}})</span>
				            </p>
			          	</div>
			          	<div class="dropdown-item-list">
				            {{#notifications.items}}
							<a href="{{metadata.url}}" class="dropdown-item" data-id="{{id}}">
								<span class="notif-detail">
									<h6>{{metadata.title}}</h6>
									<p>{{metadata.message}}</p>
								</span>
							</a>
				            {{/notifications.items}}
			          	</div>
			          	<a href="<?=base_url('personal/notifications')?>" class="dropdown-item dropdown-item-footer">View All</a>
			        </div>
		      	</li>

		      	<li class="nav-item dropdown d-none" onload="loadUserAccount">
			        <template>
				        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				            <div class="avatar">
				                <img src="{{profile.photo}}"/>
				            </div>
				            <span>{{profile.name_display}}</span>
				        </a>

				        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUser">
				            <a class="dropdown-item" href="#"><i class="fas fa-user"></i> Profile</a>
				            <a class="dropdown-item" href="#"><i class="fas fa-wallet"></i> Wallet</a>
				            <a class="dropdown-item" href="#"><i class="fas fa-cog"></i> Settings</a>
				            <div class="dropdown-divider"></div>
				            <a class="dropdown-item" href="#"><i class="fas fa-power-off"></i> Logout</a>
				        </div>
					</template>
		      	</li>
			</ul>

			<ul class="navbar-nav" role="preloader-navbar">
				<li class="nav-item dropdown">
					<a class="nav-link" href="#">
						<i class="flag-icon flag-icon-us content-placeholder"></i>
					</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link" href="#">
						<i class="flag-icon flag-icon-us content-placeholder"></i>
					</a>
				</li>

		      	<li class="nav-item dropdown">
			        <a class="nav-link" href="#">
			          	<div class="avatar content-placeholder">
			          		<img src="assets/img/avatar-male.png" alt="">
			          	</div>
			          	<span class="content-placeholder">Rio Haryanto</span>
			        </a>
		      	</li>

			</ul>
		</div>
	</nav>
</div>
