<div class="sidebar-menu">
	<ul class="content-loading" role="preloader">
		<li class="menu-title">
			<span class="content-placeholder" style="width: 100px;">&nbsp;</span>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="#">
					<span>
						<span class="content-placeholder" style="width: 18px;">&nbsp;</span> <span class="content-placeholder" style="width: 100px;">&nbsp;</span></span>
					</span>
				</a>
				<a class="sidebar-button content-placeholder" style="width: 50px;" href="#">
					&nbsp;
				</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="#">
					<span>
						<span class="content-placeholder" style="width: 18px;">&nbsp;</span> <span class="content-placeholder" style="width: 100px;">&nbsp;</span></span>
					</span>
				</a>
				<a class="sidebar-button content-placeholder" style="width: 50px;" href="#">
					&nbsp;
				</a>
			</div>
		</li>
	</ul>
	<ul>
		
		<li>
			<a href="<?=base_url('dashboard');?>">
				<span>
					<i class="fas fa-tachometer-alt"></i> <span class="hide">Dashboard</span></span>
				</span>
			</a>
		</li>
		<li class="menu-title">
			Manage
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('pages'); ?>">
					<span>
						<i class="fas fa-file-alt"></i> <span class="hide">Site Pages</span></span>
					</span>
				</a>
				<a class="sidebar-button" href="<?php echo base_url('pages/form'); ?>">Add</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('posts'); ?>">
					<span>
						<i class="fas fa-align-left"></i> <span class="hide">Blog Posts</span></span>
					</span>
				</a>
				<a class="sidebar-button" href="<?php echo base_url('posts/form'); ?>">Add</a>
			</div>
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('media-upload'); ?>">
					<span>
						<i class="fas fa-image"></i> <span class="hide">Media</span></span>
					</span>
				</a>
			</div>
		</li>

		<li class="menu-title">
			Personalize
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('appearance'); ?>">
					<span>
						<i class="fas fa-palette"></i> <span class="hide">Appearance</span></span>
					</span>
				</a>
			</div>
		</li>

		<li class="menu-title">
			Configure
		</li>
		<li>
			<div class="item-wrapper">
				<a href="<?php echo base_url('users-management'); ?>">
					<span>
						<i class="fas fa-users-cog"></i> <span class="hide">Users Management</span></span>
					</span>
				</a>
			</div>
		</li>
	</ul>
</div>
