<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success">
                                <i class="fa fa-save"></i>
                                Save
                            </button>
                            <button class="btn btn-default">
                                <i class="fa fa-check text-success"></i>
                                Save & Close
                            </button>
                            <button class="btn btn-default">
                                <i class="fa fa-times text-danger"></i>
                                Cancel
                            </button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default">
                                <i class="fa fa-info-circle"></i>
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>