<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-md-12">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h3 class="mb-4">Sliders</h3>
                    </div>
                    <div class="col-auto ml-auto">
                        <a href="<?php echo base_url('appearance/sliders/form');?>" class="btn btn-primary btn-md mb-4">
                            Add New Sliders
                        </a>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === '' ? 'active': ''); ?>>" href="<?php echo base_url('posts');?>">Published</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === 'DRAFT' ? 'active': ''); ?>" href="<?php echo base_url('posts', ['status' => 'DRAFT']);?>">Drafts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link <?php echo(input()->get('status') === 'DELETED' || input()->get('status') === '' ? 'active': ''); ?>" href="<?php echo base_url('posts', ['status' => 'DELETED']);?>">Trash</a>
                                </li>
                            </ul>
                            <form class="nav-search" :class="{ open :  isShowToggle}" action="<?php echo current_url(); ?>" method="get">
                                <div class="search-icon open-search" v-on:click="showToggle">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="search-input">
                                    <input type="search" name="keyword" placeholder="Search..." value="<?php echo input()->get('keyword'); ?>" ref="searchForm">
                                </div>
                                <div class="search-icon close-search" v-on:click="showToggle">
                                    <i class="fas fa-times"></i>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="post-list">
                    <div class="list-group mb-3">
                        <?php foreach($posts as $post): ?>
                            <div class="list-group-item">
                                <div class="post-item">
                                    <div class="post-item-detail">
                                        <a href="<?php echo base_url('appearance/sliders/form/' . $post->id);?>">
                                            <h1>
                                                <?php echo $post->title; ?>
                                            </h1>
                                        </a>
                                        <div class="post-item-meta">
                                            <span class="post-time">
                                                <?php echo $post->record->create->timestamp->format('M j, Y H:i a'); ?>
                                            </span>
                                        </div>
                                    </div>
                                    <?php if(!empty($post->image)): ?>
                                        <div class="post-thumbnail">
                                            <a href="<?php echo base_url('appearance/sliders/form/' . $post->id);?>">
                                                <img src="<?php echo $post->image_url; ?>">
                                            </a>
                                        </div>
                                    <?php endif; ?>
                                    <div class="post-action">
                                        <div class="dropdown">
                                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="<?php echo base_url('appearance/sliders/form/' . $post->id);?>">
                                                    <i class="fas fa-pencil-alt"></i>
                                                    Edit
                                                </a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="<?php echo base_url('appearance/sliders/delete/' . $post->id);?>" data-id="<?php echo $post->id; ?>" data-action="delete">
                                                    <i class="fa fa-trash"></i>
                                                    Trash
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>

                <?php echo view('components/pagination', ['result' => $posts], true); ?>
            </div>
        </div>
    </div>
</div>