<!DOCTYPE html>
<html>
<head>
    <title>{{ $meta->title }}</title>
    {{ $assets->head }}
</head>
<body class="multipurpose">

<div class="page-header fixed-top">
    {{ $partials->header }}
</div>

<div id="page-content" class="page-content">
    {{ $partials->content }}
</div>

<footer class="page-footer">
    {{ $partials->footer }}
</footer>
<a class="scroll-to-top" href="#top"><i class="fas fa-long-arrow-alt-up"></i>To Top</a>
{{ $assets->body }}
</body>
</html>