<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">    
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="<?=base_url('system');?>">Information</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?=base_url('system/folder-permissions');?>">Folder Permission</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="<?=base_url('system/php-settings');?>">PHP Settings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?=base_url('system/php-info');?>">PHP Info</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="mb-0">PHP Settings</h3>
                </div>
                <div class="card-body with-table">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped mb-0">
                            <thead>
                            <tr>
                                <th>Item</th>
                                <th>Global</th>
                                <th>Local</th>
                                <th>Access</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach( $phpSettings as $item => $phpSetting ): ?>
                                <tr>
                                    <td><?php echo $item; ?></td>
                                    <td><?php echo $phpSetting['global_value']; ?></td>
                                    <td><?php echo $phpSetting['local_value']; ?></td>
                                    <td><?php echo $phpSetting['access']; ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>