<div class="page-administrator">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">

                <div class="card">
                    <h1 class="card-header">
                        <?php echo language('APP'); ?>
                        <span class="btn btn-success float-right">
	                        <?php echo language('APP'); ?>
                        </span>
                    </h1>
                    <div class="card-body">
                        <div class="d-flex align-items-center">
                            <h5 class="mb-0">App\</h5>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="card">
                            <h5 class="card-header"><?php echo language('MODULES'); ?></h5>
                            <div class="card-body">
                                <div class="accordion">
                                    <ul class="pl-0 mb-0 list-style-none">
                                        <li>
                                            <a href="#module-15" data-toggle="collapse" aria-expanded="false">
                                                App\ </a>
                                            <ul class="collapse" id="module-15">
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/16">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Administrator\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/17">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\AssetsManagement\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/18">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\BuildingManagement\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/19">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Company\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/20">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Customers\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/21">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Documentations\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/22">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Finance\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/23">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ Goods\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/24">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Helpdesk\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/25">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\HumanResource\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/26">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Learning\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/27">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Office\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/28">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Personal\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/29">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Shuttle\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/33">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ Procurement\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/34">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ Suppliers\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/35">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\FixedAssets\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/36">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Tasks\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/40">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Companies\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/41">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\ProjectManagement\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/42">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Quiz\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/44">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Agenda\ </a>
                                                </li>
                                                <li>
                                                    <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/45">
                                                        &nbsp;&nbsp;&nbsp;&nbsp; ↳ App\Modules\Documents\ </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-body with-table">
                                <div class="accordion">
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                            <tr>
                                                <th colspan="3">Controllers</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-65cac3bb9b80ca800bcd17e31eb68cdb" data-toggle="collapse" aria-expanded="false">
                                                        Assets Management		                                                        </a>
                                                </td>
                                            </tr>
                                            </tbody><tbody id="controller-65cac3bb9b80ca800bcd17e31eb68cdb" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="24" data-permission="DENIED" type="radio" name="role[0]" id="denied-0">
                                                            <label for="denied-0" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="24" data-permission="GRANTED" type="radio" name="role[0]" id="GRANTED-0" value="2">
                                                            <label for="GRANTED-0" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="1" data-segment="24" data-permission="WRITE" type="radio" name="role[0]" id="write-0" value="3">
                                                            <label for="write-0" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="24" data-permission="DENIED" type="radio" name="role[1]" id="denied-1">
                                                            <label for="denied-1" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="24" data-permission="GRANTED" type="radio" name="role[1]" id="GRANTED-1" value="2">
                                                            <label for="GRANTED-1" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="2" data-segment="24" data-permission="WRITE" type="radio" name="role[1]" id="write-1" value="3">
                                                            <label for="write-1" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="24" data-permission="DENIED" type="radio" name="role[2]" id="denied-2">
                                                            <label for="denied-2" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="24" data-permission="GRANTED" type="radio" name="role[2]" id="GRANTED-2" value="2">
                                                            <label for="GRANTED-2" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="24" data-permission="WRITE" type="radio" name="role[2]" id="write-2" value="3">
                                                            <label for="write-2" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="24" data-permission="DENIED" type="radio" name="role[3]" id="denied-3">
                                                            <label for="denied-3" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="24" data-permission="GRANTED" type="radio" name="role[3]" id="GRANTED-3" value="2">
                                                            <label for="GRANTED-3" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="24" data-permission="WRITE" type="radio" name="role[3]" id="write-3" value="3">
                                                            <label for="write-3" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="24" data-permission="DENIED" type="radio" name="role[4]" id="denied-4">
                                                            <label for="denied-4" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="24" data-permission="GRANTED" type="radio" name="role[4]" id="GRANTED-4" value="2">
                                                            <label for="GRANTED-4" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="24" data-permission="WRITE" type="radio" name="role[4]" id="write-4" value="3">
                                                            <label for="write-4" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="24" data-permission="DENIED" type="radio" name="role[5]" id="denied-5">
                                                            <label for="denied-5" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="24" data-permission="GRANTED" type="radio" name="role[5]" id="GRANTED-5" value="2">
                                                            <label for="GRANTED-5" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="24" data-permission="WRITE" type="radio" name="role[5]" id="write-5" value="3">
                                                            <label for="write-5" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-d3f0637f6aa0d0e8c642d1ffadb34c3a" data-toggle="collapse" aria-expanded="false">
                                                        Disposal		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-d3f0637f6aa0d0e8c642d1ffadb34c3a" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="25" data-permission="DENIED" type="radio" name="role[6]" id="denied-6">
                                                            <label for="denied-6" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="25" data-permission="GRANTED" type="radio" name="role[6]" id="GRANTED-6" value="2">
                                                            <label for="GRANTED-6" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="25" data-permission="WRITE" type="radio" name="role[6]" id="write-6" value="3">
                                                            <label for="write-6" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="25" data-permission="DENIED" type="radio" name="role[7]" id="denied-7">
                                                            <label for="denied-7" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="25" data-permission="GRANTED" type="radio" name="role[7]" id="GRANTED-7" value="2">
                                                            <label for="GRANTED-7" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="25" data-permission="WRITE" type="radio" name="role[7]" id="write-7" value="3">
                                                            <label for="write-7" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="25" data-permission="DENIED" type="radio" name="role[8]" id="denied-8">
                                                            <label for="denied-8" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="25" data-permission="GRANTED" type="radio" name="role[8]" id="GRANTED-8" value="2">
                                                            <label for="GRANTED-8" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="25" data-permission="WRITE" type="radio" name="role[8]" id="write-8" value="3">
                                                            <label for="write-8" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="25" data-permission="DENIED" type="radio" name="role[9]" id="denied-9">
                                                            <label for="denied-9" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="25" data-permission="GRANTED" type="radio" name="role[9]" id="GRANTED-9" value="2">
                                                            <label for="GRANTED-9" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="25" data-permission="WRITE" type="radio" name="role[9]" id="write-9" value="3">
                                                            <label for="write-9" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="25" data-permission="DENIED" type="radio" name="role[10]" id="denied-10">
                                                            <label for="denied-10" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="25" data-permission="GRANTED" type="radio" name="role[10]" id="GRANTED-10" value="2">
                                                            <label for="GRANTED-10" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="25" data-permission="WRITE" type="radio" name="role[10]" id="write-10" value="3">
                                                            <label for="write-10" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="25" data-permission="DENIED" type="radio" name="role[11]" id="denied-11">
                                                            <label for="denied-11" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="25" data-permission="GRANTED" type="radio" name="role[11]" id="GRANTED-11" value="2">
                                                            <label for="GRANTED-11" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="25" data-permission="WRITE" type="radio" name="role[11]" id="write-11" value="3">
                                                            <label for="write-11" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Approvals</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="26" data-permission="DENIED" type="radio" name="role[12]" id="denied-12">
                                                            <label for="denied-12" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="26" data-permission="GRANTED" type="radio" name="role[12]" id="GRANTED-12" value="2">
                                                            <label for="GRANTED-12" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="26" data-permission="WRITE" type="radio" name="role[12]" id="write-12" value="3">
                                                            <label for="write-12" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="26" data-permission="DENIED" type="radio" name="role[13]" id="denied-13">
                                                            <label for="denied-13" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="26" data-permission="GRANTED" type="radio" name="role[13]" id="GRANTED-13" value="2">
                                                            <label for="GRANTED-13" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="26" data-permission="WRITE" type="radio" name="role[13]" id="write-13" value="3">
                                                            <label for="write-13" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="26" data-permission="DENIED" type="radio" name="role[14]" id="denied-14">
                                                            <label for="denied-14" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="26" data-permission="GRANTED" type="radio" name="role[14]" id="GRANTED-14" value="2">
                                                            <label for="GRANTED-14" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="26" data-permission="WRITE" type="radio" name="role[14]" id="write-14" value="3">
                                                            <label for="write-14" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="26" data-permission="DENIED" type="radio" name="role[15]" id="denied-15">
                                                            <label for="denied-15" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="26" data-permission="GRANTED" type="radio" name="role[15]" id="GRANTED-15" value="2">
                                                            <label for="GRANTED-15" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="26" data-permission="WRITE" type="radio" name="role[15]" id="write-15" value="3">
                                                            <label for="write-15" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="26" data-permission="DENIED" type="radio" name="role[16]" id="denied-16">
                                                            <label for="denied-16" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="26" data-permission="GRANTED" type="radio" name="role[16]" id="GRANTED-16" value="2">
                                                            <label for="GRANTED-16" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="26" data-permission="WRITE" type="radio" name="role[16]" id="write-16" value="3">
                                                            <label for="write-16" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="26" data-permission="DENIED" type="radio" name="role[17]" id="denied-17">
                                                            <label for="denied-17" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="26" data-permission="GRANTED" type="radio" name="role[17]" id="GRANTED-17" value="2">
                                                            <label for="GRANTED-17" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="26" data-permission="WRITE" type="radio" name="role[17]" id="write-17" value="3">
                                                            <label for="write-17" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-776975c020f95d6b6cfc8e753c538b22" data-toggle="collapse" aria-expanded="false">
                                                        Inventories		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-776975c020f95d6b6cfc8e753c538b22" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="27" data-permission="DENIED" type="radio" name="role[18]" id="denied-18">
                                                            <label for="denied-18" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="27" data-permission="GRANTED" type="radio" name="role[18]" id="GRANTED-18" value="2">
                                                            <label for="GRANTED-18" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="27" data-permission="WRITE" type="radio" name="role[18]" id="write-18" value="3">
                                                            <label for="write-18" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="27" data-permission="DENIED" type="radio" name="role[19]" id="denied-19">
                                                            <label for="denied-19" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="27" data-permission="GRANTED" type="radio" name="role[19]" id="GRANTED-19" value="2">
                                                            <label for="GRANTED-19" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="27" data-permission="WRITE" type="radio" name="role[19]" id="write-19" value="3">
                                                            <label for="write-19" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="27" data-permission="DENIED" type="radio" name="role[20]" id="denied-20">
                                                            <label for="denied-20" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="27" data-permission="GRANTED" type="radio" name="role[20]" id="GRANTED-20" value="2">
                                                            <label for="GRANTED-20" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="27" data-permission="WRITE" type="radio" name="role[20]" id="write-20" value="3">
                                                            <label for="write-20" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="27" data-permission="DENIED" type="radio" name="role[21]" id="denied-21">
                                                            <label for="denied-21" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="27" data-permission="GRANTED" type="radio" name="role[21]" id="GRANTED-21" value="2">
                                                            <label for="GRANTED-21" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="27" data-permission="WRITE" type="radio" name="role[21]" id="write-21" value="3">
                                                            <label for="write-21" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="27" data-permission="DENIED" type="radio" name="role[22]" id="denied-22">
                                                            <label for="denied-22" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="27" data-permission="GRANTED" type="radio" name="role[22]" id="GRANTED-22" value="2">
                                                            <label for="GRANTED-22" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="27" data-permission="WRITE" type="radio" name="role[22]" id="write-22" value="3">
                                                            <label for="write-22" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="27" data-permission="DENIED" type="radio" name="role[23]" id="denied-23">
                                                            <label for="denied-23" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="27" data-permission="GRANTED" type="radio" name="role[23]" id="GRANTED-23" value="2">
                                                            <label for="GRANTED-23" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="27" data-permission="WRITE" type="radio" name="role[23]" id="write-23" value="3">
                                                            <label for="write-23" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Approvals</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="28" data-permission="DENIED" type="radio" name="role[24]" id="denied-24">
                                                            <label for="denied-24" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="28" data-permission="GRANTED" type="radio" name="role[24]" id="GRANTED-24" value="2">
                                                            <label for="GRANTED-24" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="28" data-permission="WRITE" type="radio" name="role[24]" id="write-24" value="3">
                                                            <label for="write-24" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="28" data-permission="DENIED" type="radio" name="role[25]" id="denied-25">
                                                            <label for="denied-25" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="28" data-permission="GRANTED" type="radio" name="role[25]" id="GRANTED-25" value="2">
                                                            <label for="GRANTED-25" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="28" data-permission="WRITE" type="radio" name="role[25]" id="write-25" value="3">
                                                            <label for="write-25" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="28" data-permission="DENIED" type="radio" name="role[26]" id="denied-26">
                                                            <label for="denied-26" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="28" data-permission="GRANTED" type="radio" name="role[26]" id="GRANTED-26" value="2">
                                                            <label for="GRANTED-26" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="28" data-permission="WRITE" type="radio" name="role[26]" id="write-26" value="3">
                                                            <label for="write-26" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="28" data-permission="DENIED" type="radio" name="role[27]" id="denied-27">
                                                            <label for="denied-27" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="28" data-permission="GRANTED" type="radio" name="role[27]" id="GRANTED-27" value="2">
                                                            <label for="GRANTED-27" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="28" data-permission="WRITE" type="radio" name="role[27]" id="write-27" value="3">
                                                            <label for="write-27" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="28" data-permission="DENIED" type="radio" name="role[28]" id="denied-28">
                                                            <label for="denied-28" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="28" data-permission="GRANTED" type="radio" name="role[28]" id="GRANTED-28" value="2">
                                                            <label for="GRANTED-28" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="28" data-permission="WRITE" type="radio" name="role[28]" id="write-28" value="3">
                                                            <label for="write-28" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="28" data-permission="DENIED" type="radio" name="role[29]" id="denied-29">
                                                            <label for="denied-29" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="28" data-permission="GRANTED" type="radio" name="role[29]" id="GRANTED-29" value="2">
                                                            <label for="GRANTED-29" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="28" data-permission="WRITE" type="radio" name="role[29]" id="write-29" value="3">
                                                            <label for="write-29" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-3d235183656c456174ecc91b1d4c0d02" data-toggle="collapse" aria-expanded="false">
                                                        Leases		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-3d235183656c456174ecc91b1d4c0d02" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="29" data-permission="DENIED" type="radio" name="role[30]" id="denied-30">
                                                            <label for="denied-30" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="29" data-permission="GRANTED" type="radio" name="role[30]" id="GRANTED-30" value="2">
                                                            <label for="GRANTED-30" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="29" data-permission="WRITE" type="radio" name="role[30]" id="write-30" value="3">
                                                            <label for="write-30" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="29" data-permission="DENIED" type="radio" name="role[31]" id="denied-31">
                                                            <label for="denied-31" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="29" data-permission="GRANTED" type="radio" name="role[31]" id="GRANTED-31" value="2">
                                                            <label for="GRANTED-31" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="29" data-permission="WRITE" type="radio" name="role[31]" id="write-31" value="3">
                                                            <label for="write-31" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="29" data-permission="DENIED" type="radio" name="role[32]" id="denied-32">
                                                            <label for="denied-32" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="29" data-permission="GRANTED" type="radio" name="role[32]" id="GRANTED-32" value="2">
                                                            <label for="GRANTED-32" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="29" data-permission="WRITE" type="radio" name="role[32]" id="write-32" value="3">
                                                            <label for="write-32" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="29" data-permission="DENIED" type="radio" name="role[33]" id="denied-33">
                                                            <label for="denied-33" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="29" data-permission="GRANTED" type="radio" name="role[33]" id="GRANTED-33" value="2">
                                                            <label for="GRANTED-33" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="29" data-permission="WRITE" type="radio" name="role[33]" id="write-33" value="3">
                                                            <label for="write-33" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="29" data-permission="DENIED" type="radio" name="role[34]" id="denied-34">
                                                            <label for="denied-34" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="29" data-permission="GRANTED" type="radio" name="role[34]" id="GRANTED-34" value="2">
                                                            <label for="GRANTED-34" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="29" data-permission="WRITE" type="radio" name="role[34]" id="write-34" value="3">
                                                            <label for="write-34" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="29" data-permission="DENIED" type="radio" name="role[35]" id="denied-35">
                                                            <label for="denied-35" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="29" data-permission="GRANTED" type="radio" name="role[35]" id="GRANTED-35" value="2">
                                                            <label for="GRANTED-35" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="29" data-permission="WRITE" type="radio" name="role[35]" id="write-35" value="3">
                                                            <label for="write-35" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Approvals</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="30" data-permission="DENIED" type="radio" name="role[36]" id="denied-36">
                                                            <label for="denied-36" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="30" data-permission="GRANTED" type="radio" name="role[36]" id="GRANTED-36" value="2">
                                                            <label for="GRANTED-36" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="30" data-permission="WRITE" type="radio" name="role[36]" id="write-36" value="3">
                                                            <label for="write-36" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="30" data-permission="DENIED" type="radio" name="role[37]" id="denied-37">
                                                            <label for="denied-37" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="30" data-permission="GRANTED" type="radio" name="role[37]" id="GRANTED-37" value="2">
                                                            <label for="GRANTED-37" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="30" data-permission="WRITE" type="radio" name="role[37]" id="write-37" value="3">
                                                            <label for="write-37" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="30" data-permission="DENIED" type="radio" name="role[38]" id="denied-38">
                                                            <label for="denied-38" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="30" data-permission="GRANTED" type="radio" name="role[38]" id="GRANTED-38" value="2">
                                                            <label for="GRANTED-38" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="30" data-permission="WRITE" type="radio" name="role[38]" id="write-38" value="3">
                                                            <label for="write-38" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="30" data-permission="DENIED" type="radio" name="role[39]" id="denied-39">
                                                            <label for="denied-39" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="30" data-permission="GRANTED" type="radio" name="role[39]" id="GRANTED-39" value="2">
                                                            <label for="GRANTED-39" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="30" data-permission="WRITE" type="radio" name="role[39]" id="write-39" value="3">
                                                            <label for="write-39" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="30" data-permission="DENIED" type="radio" name="role[40]" id="denied-40">
                                                            <label for="denied-40" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="30" data-permission="GRANTED" type="radio" name="role[40]" id="GRANTED-40" value="2">
                                                            <label for="GRANTED-40" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="30" data-permission="WRITE" type="radio" name="role[40]" id="write-40" value="3">
                                                            <label for="write-40" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="30" data-permission="DENIED" type="radio" name="role[41]" id="denied-41">
                                                            <label for="denied-41" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="30" data-permission="GRANTED" type="radio" name="role[41]" id="GRANTED-41" value="2">
                                                            <label for="GRANTED-41" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="30" data-permission="WRITE" type="radio" name="role[41]" id="write-41" value="3">
                                                            <label for="write-41" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-0d6ef3e3945c8b932fc4b8ea2c9e61c6" data-toggle="collapse" aria-expanded="false">
                                                        Categories		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-0d6ef3e3945c8b932fc4b8ea2c9e61c6" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="31" data-permission="DENIED" type="radio" name="role[42]" id="denied-42">
                                                            <label for="denied-42" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="31" data-permission="GRANTED" type="radio" name="role[42]" id="GRANTED-42" value="2">
                                                            <label for="GRANTED-42" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="31" data-permission="WRITE" type="radio" name="role[42]" id="write-42" value="3">
                                                            <label for="write-42" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="31" data-permission="DENIED" type="radio" name="role[43]" id="denied-43">
                                                            <label for="denied-43" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="31" data-permission="GRANTED" type="radio" name="role[43]" id="GRANTED-43" value="2">
                                                            <label for="GRANTED-43" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="31" data-permission="WRITE" type="radio" name="role[43]" id="write-43" value="3">
                                                            <label for="write-43" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="31" data-permission="DENIED" type="radio" name="role[44]" id="denied-44">
                                                            <label for="denied-44" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="31" data-permission="GRANTED" type="radio" name="role[44]" id="GRANTED-44" value="2">
                                                            <label for="GRANTED-44" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="31" data-permission="WRITE" type="radio" name="role[44]" id="write-44" value="3">
                                                            <label for="write-44" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="31" data-permission="DENIED" type="radio" name="role[45]" id="denied-45">
                                                            <label for="denied-45" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="31" data-permission="GRANTED" type="radio" name="role[45]" id="GRANTED-45" value="2">
                                                            <label for="GRANTED-45" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="31" data-permission="WRITE" type="radio" name="role[45]" id="write-45" value="3">
                                                            <label for="write-45" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="31" data-permission="DENIED" type="radio" name="role[46]" id="denied-46">
                                                            <label for="denied-46" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="31" data-permission="GRANTED" type="radio" name="role[46]" id="GRANTED-46" value="2">
                                                            <label for="GRANTED-46" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="31" data-permission="WRITE" type="radio" name="role[46]" id="write-46" value="3">
                                                            <label for="write-46" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="31" data-permission="DENIED" type="radio" name="role[47]" id="denied-47">
                                                            <label for="denied-47" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="31" data-permission="GRANTED" type="radio" name="role[47]" id="GRANTED-47" value="2">
                                                            <label for="GRANTED-47" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="31" data-permission="WRITE" type="radio" name="role[47]" id="write-47" value="3">
                                                            <label for="write-47" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-10cb23a5df5c816851180613a2de9e77" data-toggle="collapse" aria-expanded="false">
                                                        Locations		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-10cb23a5df5c816851180613a2de9e77" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="32" data-permission="DENIED" type="radio" name="role[48]" id="denied-48">
                                                            <label for="denied-48" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="32" data-permission="GRANTED" type="radio" name="role[48]" id="GRANTED-48" value="2">
                                                            <label for="GRANTED-48" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="32" data-permission="WRITE" type="radio" name="role[48]" id="write-48" value="3">
                                                            <label for="write-48" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="32" data-permission="DENIED" type="radio" name="role[49]" id="denied-49">
                                                            <label for="denied-49" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="32" data-permission="GRANTED" type="radio" name="role[49]" id="GRANTED-49" value="2">
                                                            <label for="GRANTED-49" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="32" data-permission="WRITE" type="radio" name="role[49]" id="write-49" value="3">
                                                            <label for="write-49" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="32" data-permission="DENIED" type="radio" name="role[50]" id="denied-50">
                                                            <label for="denied-50" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="32" data-permission="GRANTED" type="radio" name="role[50]" id="GRANTED-50" value="2">
                                                            <label for="GRANTED-50" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="32" data-permission="WRITE" type="radio" name="role[50]" id="write-50" value="3">
                                                            <label for="write-50" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="32" data-permission="DENIED" type="radio" name="role[51]" id="denied-51">
                                                            <label for="denied-51" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="32" data-permission="GRANTED" type="radio" name="role[51]" id="GRANTED-51" value="2">
                                                            <label for="GRANTED-51" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="32" data-permission="WRITE" type="radio" name="role[51]" id="write-51" value="3">
                                                            <label for="write-51" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="32" data-permission="DENIED" type="radio" name="role[52]" id="denied-52">
                                                            <label for="denied-52" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="32" data-permission="GRANTED" type="radio" name="role[52]" id="GRANTED-52" value="2">
                                                            <label for="GRANTED-52" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="32" data-permission="WRITE" type="radio" name="role[52]" id="write-52" value="3">
                                                            <label for="write-52" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="32" data-permission="DENIED" type="radio" name="role[53]" id="denied-53">
                                                            <label for="denied-53" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="32" data-permission="GRANTED" type="radio" name="role[53]" id="GRANTED-53" value="2">
                                                            <label for="GRANTED-53" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="32" data-permission="WRITE" type="radio" name="role[53]" id="write-53" value="3">
                                                            <label for="write-53" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-e58ad847608b64dcbf7f1698d90317af" data-toggle="collapse" aria-expanded="false">
                                                        Vendors		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-e58ad847608b64dcbf7f1698d90317af" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="33" data-permission="DENIED" type="radio" name="role[54]" id="denied-54">
                                                            <label for="denied-54" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="33" data-permission="GRANTED" type="radio" name="role[54]" id="GRANTED-54" value="2">
                                                            <label for="GRANTED-54" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="33" data-permission="WRITE" type="radio" name="role[54]" id="write-54" value="3">
                                                            <label for="write-54" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="33" data-permission="DENIED" type="radio" name="role[55]" id="denied-55">
                                                            <label for="denied-55" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="33" data-permission="GRANTED" type="radio" name="role[55]" id="GRANTED-55" value="2">
                                                            <label for="GRANTED-55" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="33" data-permission="WRITE" type="radio" name="role[55]" id="write-55" value="3">
                                                            <label for="write-55" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="33" data-permission="DENIED" type="radio" name="role[56]" id="denied-56">
                                                            <label for="denied-56" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="33" data-permission="GRANTED" type="radio" name="role[56]" id="GRANTED-56" value="2">
                                                            <label for="GRANTED-56" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="33" data-permission="WRITE" type="radio" name="role[56]" id="write-56" value="3">
                                                            <label for="write-56" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="33" data-permission="DENIED" type="radio" name="role[57]" id="denied-57">
                                                            <label for="denied-57" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="33" data-permission="GRANTED" type="radio" name="role[57]" id="GRANTED-57" value="2">
                                                            <label for="GRANTED-57" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="33" data-permission="WRITE" type="radio" name="role[57]" id="write-57" value="3">
                                                            <label for="write-57" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="33" data-permission="DENIED" type="radio" name="role[58]" id="denied-58">
                                                            <label for="denied-58" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="33" data-permission="GRANTED" type="radio" name="role[58]" id="GRANTED-58" value="2">
                                                            <label for="GRANTED-58" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="33" data-permission="WRITE" type="radio" name="role[58]" id="write-58" value="3">
                                                            <label for="write-58" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="33" data-permission="DENIED" type="radio" name="role[59]" id="denied-59">
                                                            <label for="denied-59" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="33" data-permission="GRANTED" type="radio" name="role[59]" id="GRANTED-59" value="2">
                                                            <label for="GRANTED-59" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="33" data-permission="WRITE" type="radio" name="role[59]" id="write-59" value="3">
                                                            <label for="write-59" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Form Contact</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="34" data-permission="DENIED" type="radio" name="role[60]" id="denied-60">
                                                            <label for="denied-60" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="34" data-permission="GRANTED" type="radio" name="role[60]" id="GRANTED-60" value="2">
                                                            <label for="GRANTED-60" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="34" data-permission="WRITE" type="radio" name="role[60]" id="write-60" value="3">
                                                            <label for="write-60" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="34" data-permission="DENIED" type="radio" name="role[61]" id="denied-61">
                                                            <label for="denied-61" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="34" data-permission="GRANTED" type="radio" name="role[61]" id="GRANTED-61" value="2">
                                                            <label for="GRANTED-61" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="34" data-permission="WRITE" type="radio" name="role[61]" id="write-61" value="3">
                                                            <label for="write-61" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="34" data-permission="DENIED" type="radio" name="role[62]" id="denied-62">
                                                            <label for="denied-62" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="34" data-permission="GRANTED" type="radio" name="role[62]" id="GRANTED-62" value="2">
                                                            <label for="GRANTED-62" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="34" data-permission="WRITE" type="radio" name="role[62]" id="write-62" value="3">
                                                            <label for="write-62" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="34" data-permission="DENIED" type="radio" name="role[63]" id="denied-63">
                                                            <label for="denied-63" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="34" data-permission="GRANTED" type="radio" name="role[63]" id="GRANTED-63" value="2">
                                                            <label for="GRANTED-63" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="34" data-permission="WRITE" type="radio" name="role[63]" id="write-63" value="3">
                                                            <label for="write-63" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="34" data-permission="DENIED" type="radio" name="role[64]" id="denied-64">
                                                            <label for="denied-64" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="34" data-permission="GRANTED" type="radio" name="role[64]" id="GRANTED-64" value="2">
                                                            <label for="GRANTED-64" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="34" data-permission="WRITE" type="radio" name="role[64]" id="write-64" value="3">
                                                            <label for="write-64" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="34" data-permission="DENIED" type="radio" name="role[65]" id="denied-65">
                                                            <label for="denied-65" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="34" data-permission="GRANTED" type="radio" name="role[65]" id="GRANTED-65" value="2">
                                                            <label for="GRANTED-65" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="34" data-permission="WRITE" type="radio" name="role[65]" id="write-65" value="3">
                                                            <label for="write-65" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tr>
                                                <td colspan="3">
                                                    <a href="#controller-3f89d95f78935b8f853310b78c7d82e9" data-toggle="collapse" aria-expanded="false">
                                                        Movements		                                                        </a>
                                                </td>
                                            </tr>
                                            <tbody id="controller-3f89d95f78935b8f853310b78c7d82e9" class="collapse">
                                            <tr>
                                                <th width="30%">Methods</th>
                                                <th width="30%">Roles</th>
                                            </tr>
                                            <tr>
                                                <td>Index</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="35" data-permission="DENIED" type="radio" name="role[66]" id="denied-66">
                                                            <label for="denied-66" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="35" data-permission="GRANTED" type="radio" name="role[66]" id="GRANTED-66" value="2">
                                                            <label for="GRANTED-66" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="35" data-permission="WRITE" type="radio" name="role[66]" id="write-66" value="3">
                                                            <label for="write-66" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="35" data-permission="DENIED" type="radio" name="role[67]" id="denied-67">
                                                            <label for="denied-67" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="35" data-permission="GRANTED" type="radio" name="role[67]" id="GRANTED-67" value="2">
                                                            <label for="GRANTED-67" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="35" data-permission="WRITE" type="radio" name="role[67]" id="write-67" value="3">
                                                            <label for="write-67" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="35" data-permission="DENIED" type="radio" name="role[68]" id="denied-68">
                                                            <label for="denied-68" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="35" data-permission="GRANTED" type="radio" name="role[68]" id="GRANTED-68" value="2">
                                                            <label for="GRANTED-68" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="35" data-permission="WRITE" type="radio" name="role[68]" id="write-68" value="3">
                                                            <label for="write-68" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="35" data-permission="DENIED" type="radio" name="role[69]" id="denied-69">
                                                            <label for="denied-69" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="35" data-permission="GRANTED" type="radio" name="role[69]" id="GRANTED-69" value="2">
                                                            <label for="GRANTED-69" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="35" data-permission="WRITE" type="radio" name="role[69]" id="write-69" value="3">
                                                            <label for="write-69" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="35" data-permission="DENIED" type="radio" name="role[70]" id="denied-70">
                                                            <label for="denied-70" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="35" data-permission="GRANTED" type="radio" name="role[70]" id="GRANTED-70" value="2">
                                                            <label for="GRANTED-70" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="35" data-permission="WRITE" type="radio" name="role[70]" id="write-70" value="3">
                                                            <label for="write-70" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="35" data-permission="DENIED" type="radio" name="role[71]" id="denied-71">
                                                            <label for="denied-71" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="35" data-permission="GRANTED" type="radio" name="role[71]" id="GRANTED-71" value="2">
                                                            <label for="GRANTED-71" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="35" data-permission="WRITE" type="radio" name="role[71]" id="write-71" value="3">
                                                            <label for="write-71" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Approvals</td>
                                                <td>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Developer</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="1" data-segment="36" data-permission="DENIED" type="radio" name="role[72]" id="denied-72">
                                                            <label for="denied-72" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="36" data-permission="GRANTED" type="radio" name="role[72]" id="GRANTED-72" value="2">
                                                            <label for="GRANTED-72" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="1" data-segment="36" data-permission="WRITE" type="radio" name="role[72]" id="write-72" value="3">
                                                            <label for="write-72" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Administrator</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="2" data-segment="36" data-permission="DENIED" type="radio" name="role[73]" id="denied-73">
                                                            <label for="denied-73" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="36" data-permission="GRANTED" type="radio" name="role[73]" id="GRANTED-73" value="2">
                                                            <label for="GRANTED-73" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="2" data-segment="36" data-permission="WRITE" type="radio" name="role[73]" id="write-73" value="3">
                                                            <label for="write-73" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>User</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="3" data-segment="36" data-permission="DENIED" type="radio" name="role[74]" id="denied-74">
                                                            <label for="denied-74" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="3" data-segment="36" data-permission="GRANTED" type="radio" name="role[74]" id="GRANTED-74" value="2">
                                                            <label for="GRANTED-74" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="3" data-segment="36" data-permission="WRITE" type="radio" name="role[74]" id="write-74" value="3">
                                                            <label for="write-74" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Manager</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="4" data-segment="36" data-permission="DENIED" type="radio" name="role[75]" id="denied-75">
                                                            <label for="denied-75" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="4" data-segment="36" data-permission="GRANTED" type="radio" name="role[75]" id="GRANTED-75" value="2">
                                                            <label for="GRANTED-75" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="4" data-segment="36" data-permission="WRITE" type="radio" name="role[75]" id="write-75" value="3">
                                                            <label for="write-75" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Supervisor</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="5" data-segment="36" data-permission="DENIED" type="radio" name="role[76]" id="denied-76">
                                                            <label for="denied-76" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="5" data-segment="36" data-permission="GRANTED" type="radio" name="role[76]" id="GRANTED-76" value="2">
                                                            <label for="GRANTED-76" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="5" data-segment="36" data-permission="WRITE" type="radio" name="role[76]" id="write-76" value="3">
                                                            <label for="write-76" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="d-flex align-items-center justify-content-between mb-2">
                                                        <span>Staff</span>
                                                        <div class="three-state-switch">
                                                            <input class="insert-role" data-role="6" data-segment="36" data-permission="DENIED" type="radio" name="role[77]" id="denied-77">
                                                            <label for="denied-77" class="switch-danger ml-0" data-toggle="tooltip" data-original-title="Denied">
                                                                <span><i class="fas fa-ban"></i></span>
                                                            </label>
                                                            <input class="insert-role" data-role="6" data-segment="36" data-permission="GRANTED" type="radio" name="role[77]" id="GRANTED-77" value="2">
                                                            <label for="GRANTED-77" class="switch-info" data-toggle="tooltip" data-original-title="GRANTED Only">
                                                                <span><i class="fas fa-eye"></i></span>
                                                            </label>
                                                            <input checked class="insert-role" data-role="6" data-segment="36" data-permission="WRITE" type="radio" name="role[77]" id="write-77" value="3">
                                                            <label for="write-77" class="switch-success mr-0" data-toggle="tooltip" data-original-title="Can Write">
                                                                <span><i class="fas fa-pencil-alt"></i></span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                            </tbody>

                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>