<div class="page-settings">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">
                            <?php echo $tabs; ?>
                        </div>
                    </div>
                </div>
                <form>
                    <div class="card">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                    <h5 class="mb-0">System Config</h5>
                                </div>
                                <div class="col-auto ml-auto">
                                    <button type="submit" class="btn btn-primary">
                                        <?php echo $language->getLine('BTN_SAVE'); ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-md-6">
                                        <h6 class="font-weight-bold">System Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Path to Log Folder</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control" value="home/public_html">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Help Server</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>English (GB)</option>
                                                </select>
                                            </div>
                                        </div>

                                        <h6 class="font-weight-bold mt-5">Debug Setting</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Debug System</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Debug Language</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>

                                        <h6 class="font-weight-bold mt-5">Session Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Session Handler</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>Database</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Session Lifetime</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control" value="15">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Shared Session</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <h6 class="font-weight-bold">Cache Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Cache Handler</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>File</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Path to Cache Folder</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control" value="home/public_html">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Cache Time</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control" value="15">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Platform Specific Caching</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">System Cache</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>OFF - Disbled Cache</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                    <h5 class="mb-0">Server Config</h5>
                                </div>
                                <div class="col-auto ml-auto">
                                    <button type="submit" class="btn btn-primary">
                                        <?php echo $language->getLine('BTN_SAVE'); ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-md-6">
                                        <h6 class="font-weight-bold">Server Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Path to Temp Folder</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control" value="home/public_html">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Gzip Page Compression</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Error Reporting</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>System Default</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Force HTTPS</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>None</option>
                                                </select>
                                            </div>
                                        </div>

                                        <h6 class="font-weight-bold mt-5">Locations Setting</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Server Time Zone</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>Indonesia</option>
                                                </select>
                                            </div>
                                        </div>

                                        <h6 class="font-weight-bold mt-5">FTP Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Enable FTP</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>

                                        <h6 class="font-weight-bold mt-5">Proxy Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Enable Proxy</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <h6 class="font-weight-bold">Database Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Database Type</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>MySQLi</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Host</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control" value="localhost">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Database Username</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Database Name</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Database Tables Prefix</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>

                                        <h6 class="font-weight-bold mt-5">Mail Settings</h6>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Send Mail</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Disable Mass Mail</label>
                                            <div class="col-sm-7">
                                                <label class="switch mt-2">
                                                    <input type="checkbox">
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">From Email</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Reply To Email</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Reply To Name</label>
                                            <div class="col-sm-7">
                                                <input type="text" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-5 col-form-label">Mailer</label>
                                            <div class="col-sm-7">
                                                <select class="form-control custom-select">
                                                    <option>PHP Mail</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <div class="col-sm-12">
                                                <button class="btn btn-default">Send Test Mail</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>