<div class="page-system">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <?php echo $tabs; ?>
                <div class="card">
                    <div class="card-body with-table">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped mb-0">
                                <thead>
                                <tr>
                                    <th><?php echo language('ITEM'); ?></th>
                                    <th><?php echo language('GLOBAL'); ?></th>
                                    <th><?php echo language('LOCAL'); ?></th>
                                    <th><?php echo language('ACCESS'); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach( $phpSettings as $item => $phpSetting ): ?>
                                    <tr>
                                        <td><?php echo $item; ?></td>
                                        <td><?php echo $phpSetting['global_value']; ?></td>
                                        <td><?php echo $phpSetting['local_value']; ?></td>
                                        <td><?php echo $phpSetting['access']; ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>