<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <form action="" method="post" enctype="multipart/form-data">
                <div class="card">
                    <h5 class="card-header d-flex align-items-center justify-content-between">
                        Settings	                    
                        <div class="card-options">
                            <button type="submit" class="btn btn-primary btn-md">
                                Save                                
                            </button>
                        </div>
                    </h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                <input name="photo" type="file" class="dropify" data-height="140" data-default-file="" data-allowed-file-extensions="jpg png">
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input class="form-control" type="text" name="name" value="Eddy Dharma">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Username</label>
                                            <input class="form-control" type="text" name="username" value="restumulya">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input name="email" class="form-control" type="email" value="eddydharna56@gmail.com">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Mobile</label>
                                            <input name="mobile" class="form-control" type="text" value="0811392268">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Gender</label>
                                    <select name="gender" class="form-control custom-select">
                                        <option value="MALE">Male</option>
                                        <option value="FEMALE">Female</option>
                                        <option value="UNDEFINED" selected="">Undefined</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Religion</label>
                                    <select name="religion" class="form-control custom-select">
                                        <option>Undefined</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Marital</label>
                                    <select name="marital" class="form-control custom-select">
                                        <option value="UNDEFINED" selected="">Undefined</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Birthplace</label>
                                    <input name="birthplace" class="form-control" type="text" value="" placeholder="Birthplace">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Birthday</label>
                                    <input name="birthday" class="form-control datepicker" type="text" value="" placeholder="Birthday">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>