<div class="page-transactions">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">Detail Pesanan</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <div class="row justify-content-between">
                    <div class="col-md-auto">
                        <div class="media align-items-center">
                            <div class="avatar-30 mr-3">
                                <img src="assets/img/avatar-female.png" alt="">
                            </div>
                            <div class="media-body">
                                <h5 class="mb-0">
                                    <a href="#">PT. Kredit Impian</a>
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-auto">
                        <span>31 Agustus 2019 06:00 AM</span>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5 border-right">
                        <div class="media">
                            <div class="avatar-30 mr-3">
                                <img src="assets/img/avatar-female.png" alt="">
                            </div>
                            <div class="media-body">
                                <h5 class="mb-0">
                                    <a href="#">PT. Kredit Impian</a>
                                </h5>
                                <p>(INV/20190805/XIX/VIII/349483812)</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5 border-right">
                        <p class="mb-0">Status</p>
                        <h5>Pesanan Selesai</h5>
                    </div>
                    <div class="col-md-2">
                        <p class="mb-0">Total Belanja</p>
                        <h5 class="text-primary">Rp. 2.000.000</h5>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-5 border-right">
                        <div class="media align-items-center">
                            <div class="avatar-80 mr-3">
                                <img src="assets/img/avatar-female.png" alt="">
                            </div>
                            <div class="media-body">
                                <h5 class="d-flex align-items-center">
                                    <span class="btn btn-default btn-xs mr-2 text-uppercase">CODE</span>
                                    <a href="#" target="_blank">Product Name</a>
                                </h5>
                                <p>Rp. 2.000.000</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <p class="mb-0">
                            Total Harga Produk
                        </p>
                        <h5 class="text-primary">
                            Rp. 2.000.000
                        </h5>
                    </div>
                    <div class="col-md-2">
                        <a href="#" class="btn btn-primary btn-block">Beli Lagi</a>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Pembayaran</h5>
            </div>
            <div class="card-body with-table">
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <td width="70%">Total Harga</td>
                                <td>Rp. 2.000.000</td>
                            </tr>
                            <tr>
                                <td width="70%">Biaya Asuransi</td>
                                <td>Rp. 200.000</td>
                            </tr>
                            <tr>
                                <td width="70%">Discount</td>
                                <td>Rp. 200.000</td>
                            </tr>
                            <tr>
                                <td width="70%">Total Pembayaran</td>
                                <td class="text-primary font-weight-bold">Rp. 2.000.000</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Status Pesanan</h5>
            </div>
            <div class="card-body">
                <div class="tracker-list v2">

                    <div class="tracker-item active">
                        <div class="d-flex align-items-strech">
                            <div class="tracker-body text-right">
                                <div class="mb-1">
                                    <span class="badge badge-light no-radius text--grey">Buyer</span>
                                </div>
                                <div class="tracker-head mb-1">
                                    <span class="track-date">16 February 2018</span>
                                </div>
                                <div>13:30</div>
                            </div>
                            <div class="tracker-body">
                                <div class="tracker-dot"></div>
                                <div class="tracker-head">
                                    <span class="status-track">Transaksi Selesai</span>
                                </div>
                                <div class="tracker-desc">
                                    Dana akan diteruskan ke penjual
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tracker-item">
                        <div class="d-flex align-items-strech">
                            <div class="tracker-body text-right">
                                <div class="mb-1">
                                    <span class="badge badge-light no-radius text--grey">System Tracker</span>
                                </div>
                                <div class="tracker-head mb-1">
                                    <span class="track-date">16 February 2018</span>
                                </div>
                                <div>13:30</div>
                            </div>
                            <div class="tracker-body">
                                <div class="tracker-dot"></div>
                                <div class="tracker-head">
                                    <span class="status-track">Transaksi Selesai</span>
                                </div>
                                <div class="tracker-desc">
                                    Dana akan diteruskan ke penjual Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis officiis sed rerum cum molestias, magni consectetur
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tracker-item">
                        <div class="d-flex align-items-strech">
                            <div class="tracker-body text-right">
                                <div class="mb-1">
                                    <span class="badge badge-light no-radius text--grey">System Tracker</span>
                                </div>
                                <div class="tracker-head mb-1">
                                    <span class="track-date">16 February 2018</span>
                                </div>
                                <div>13:30</div>
                            </div>
                            <div class="tracker-body">
                                <div class="tracker-dot"></div>
                                <div class="tracker-head">
                                    <span class="status-track">Transaksi Selesai</span>
                                </div>
                                <div class="tracker-desc">
                                    Dana akan diteruskan ke penjual Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis officiis sed rerum cum molestias, magni consectetur
                                </div>
                            </div>
                        </div>
                    </div>
            
                </div>
            </div>
        </div>
    </div>
</div>