<div class="page-system">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header p-0 px-3">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">Companies</h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <div class="nav-pages">
                                            <ul class="nav">
                                                <li class="nav-item">
                                                    <a href="<?= base_url('companies'); ?>" class="nav-link" data-toggle="tooltip" title="Grid View">
                                                        <i class="fas fa-th-large"></i>
                                                    </a>
                                                </li>
                                                <li class="nav-item">
                                                    <a href="<?= base_url('companies/table'); ?>" class="nav-link active" data-toggle="tooltip" title="Table View">
                                                        <i class="fas fa-table"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-auto">
                                        <a href="<?=base_url('companies/form');?>" class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?=current_url();?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <option>10</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Period</span>
                                            </div>
                                            <input class="form-control input-daterange-datepicker" type="text" name="period" value="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Keyword" value="" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="#">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered datatables-basic">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>ID</th>
                                    <th>PIC</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="media align-items-center">
                                            <div class="avatar-30 mr-2">
                                                <img src="assets/img/avatar-female.png" alt="">
                                            </div>
                                            <div class="media-body">
                                                <a href="<?=base_url('companies-detail');?>">PT. Kredit Impian</a>
                                            </div>
                                        </div>
                                    </td>
                                    <td>1</td>
                                    <td>Teguh Rianto - CEO</td>
                                    <td>
                                        <a href="mailto:teguh@mailinator.com">teguh@mailinator.com</a>
                                    </td>
                                    <td>
                                        <a href="tel:08177367263">08177367263</a>
                                    </td>
                                    <td>
                                        <span class="badge badge-success py-1">Active</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Edit">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="View">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Stats">
                                                <i class="fas fa-chart-bar"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Copy">
                                                <i class="fa fa-copy"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Trash">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="media align-items-center">
                                            <div class="avatar-text-30 mr-2">
                                                IK
                                            </div>
                                            <div class="media-body">
                                                <a href="<?=base_url('companies-detail');?>">PT. Impian Kredit</a>
                                            </div>
                                        </div>
                                    </td>
                                    <td>2</td>
                                    <td>Teguh Rianto - CTO</td>
                                    <td>
                                        <a href="mailto:teguh@mailinator.com">teguh@mailinator.com</a>
                                    </td>
                                    <td>
                                        <a href="tel:08177367263">08177367263</a>
                                    </td>
                                    <td>
                                        <span class="badge badge-success py-1">Active</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Edit">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="View">
                                                <i class="fa fa-eye"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Stats">
                                                <i class="fas fa-chart-bar"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Copy">
                                                <i class="fa fa-copy"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Trash">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>