<div class="page-form">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <h5 class="mb-0">Form</h5>
                            </div>
                            <div class="col-auto ml-auto">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    Cancel
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h2 class="font-weight-bold">Form Advanced</h2>

                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-3">Select With Search</h4>

                                <p class="text-muted">Single Select</p>
                                <p class="text-muted">
                                    Select can take a regular select box like this...
                                </p>

                                <div class="form-group">
                                    <select class="form-control select-dropdown" multiple>
                                        <option>Select</option>
                                        <optgroup label="Alaskan/Hawaiian Time Zone">
                                            <option value="AK">Alaska</option>
                                            <option value="HI">Hawaii</option>
                                        </optgroup>
                                        <optgroup label="Pacific Time Zone">
                                            <option value="CA">California</option>
                                            <option value="NV">Nevada</option>
                                            <option value="OR">Oregon</option>
                                            <option value="WA">Washington</option>
                                        </optgroup>
                                        <optgroup label="Mountain Time Zone">
                                            <option value="AZ">Arizona</option>
                                            <option value="CO">Colorado</option>
                                            <option value="ID">Idaho</option>
                                            <option value="MT">Montana</option>
                                            <option value="NE">Nebraska</option>
                                            <option value="NM">New Mexico</option>
                                            <option value="ND">North Dakota</option>
                                            <option value="UT">Utah</option>
                                            <option value="WY">Wyoming</option>
                                        </optgroup>
                                        <optgroup label="Central Time Zone">
                                            <option value="AL">Alabama</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="IL">Illinois</option>
                                            <option value="IA">Iowa</option>
                                            <option value="KS">Kansas</option>
                                            <option value="KY">Kentucky</option>
                                            <option value="LA">Louisiana</option>
                                            <option value="MN">Minnesota</option>
                                            <option value="MS">Mississippi</option>
                                            <option value="MO">Missouri</option>
                                            <option value="OK">Oklahoma</option>
                                            <option value="SD">South Dakota</option>
                                            <option value="TX">Texas</option>
                                            <option value="TN">Tennessee</option>
                                            <option value="WI">Wisconsin</option>
                                        </optgroup>
                                        <optgroup label="Eastern Time Zone">
                                            <option value="CT">Connecticut</option>
                                            <option value="DE">Delaware</option>
                                            <option value="FL">Florida</option>
                                            <option value="GA">Georgia</option>
                                            <option value="IN">Indiana</option>
                                            <option value="ME">Maine</option>
                                            <option value="MD">Maryland</option>
                                            <option value="MA">Massachusetts</option>
                                            <option value="MI">Michigan</option>
                                            <option value="NH">New Hampshire</option>
                                            <option value="NJ">New Jersey</option>
                                            <option value="NY">New York</option>
                                            <option value="NC">North Carolina</option>
                                            <option value="OH">Ohio</option>
                                            <option value="PA">Pennsylvania</option>
                                            <option value="RI">Rhode Island</option>
                                            <option value="SC">South Carolina</option>
                                            <option value="VT">Vermont</option>
                                            <option value="VA">Virginia</option>
                                            <option value="WV">West Virginia</option>
                                        </optgroup>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <select class="form-control select-with-search">
                                        <option>Select</option>
                                        <optgroup label="Alaskan/Hawaiian Time Zone">
                                            <option value="AK">Alaska</option>
                                            <option value="HI">Hawaii</option>
                                        </optgroup>
                                        <optgroup label="Pacific Time Zone">
                                            <option value="CA">California</option>
                                            <option value="NV">Nevada</option>
                                            <option value="OR">Oregon</option>
                                            <option value="WA">Washington</option>
                                        </optgroup>
                                        <optgroup label="Mountain Time Zone">
                                            <option value="AZ">Arizona</option>
                                            <option value="CO">Colorado</option>
                                            <option value="ID">Idaho</option>
                                            <option value="MT">Montana</option>
                                            <option value="NE">Nebraska</option>
                                            <option value="NM">New Mexico</option>
                                            <option value="ND">North Dakota</option>
                                            <option value="UT">Utah</option>
                                            <option value="WY">Wyoming</option>
                                        </optgroup>
                                        <optgroup label="Central Time Zone">
                                            <option value="AL">Alabama</option>
                                            <option value="AR">Arkansas</option>
                                            <option value="IL">Illinois</option>
                                            <option value="IA">Iowa</option>
                                            <option value="KS">Kansas</option>
                                            <option value="KY">Kentucky</option>
                                            <option value="LA">Louisiana</option>
                                            <option value="MN">Minnesota</option>
                                            <option value="MS">Mississippi</option>
                                            <option value="MO">Missouri</option>
                                            <option value="OK">Oklahoma</option>
                                            <option value="SD">South Dakota</option>
                                            <option value="TX">Texas</option>
                                            <option value="TN">Tennessee</option>
                                            <option value="WI">Wisconsin</option>
                                        </optgroup>
                                        <optgroup label="Eastern Time Zone">
                                            <option value="CT">Connecticut</option>
                                            <option value="DE">Delaware</option>
                                            <option value="FL">Florida</option>
                                            <option value="GA">Georgia</option>
                                            <option value="IN">Indiana</option>
                                            <option value="ME">Maine</option>
                                            <option value="MD">Maryland</option>
                                            <option value="MA">Massachusetts</option>
                                            <option value="MI">Michigan</option>
                                            <option value="NH">New Hampshire</option>
                                            <option value="NJ">New Jersey</option>
                                            <option value="NY">New York</option>
                                            <option value="NC">North Carolina</option>
                                            <option value="OH">Ohio</option>
                                            <option value="PA">Pennsylvania</option>
                                            <option value="RI">Rhode Island</option>
                                            <option value="SC">South Carolina</option>
                                            <option value="VT">Vermont</option>
                                            <option value="VA">Virginia</option>
                                            <option value="WV">West Virginia</option>
                                        </optgroup>
                                    </select>
                                </div>


                                <p class="text-muted mt-3">Multiple Select</p>
                                <p class="text-muted">
                                    Select2 can take a regular select box like this...
                                </p>

                                <select class="form-control select-with-search" multiple="multiple" multiple data-placeholder="Choose ...">
                                    <optgroup label="Alaskan/Hawaiian Time Zone">
                                        <option value="AK">Alaska</option>
                                        <option value="HI">Hawaii</option>
                                    </optgroup>
                                    <optgroup label="Pacific Time Zone">
                                        <option value="CA">California</option>
                                        <option value="NV">Nevada</option>
                                        <option value="OR">Oregon</option>
                                        <option value="WA">Washington</option>
                                    </optgroup>
                                    <optgroup label="Mountain Time Zone">
                                        <option value="AZ">Arizona</option>
                                        <option value="CO">Colorado</option>
                                        <option value="ID">Idaho</option>
                                        <option value="MT">Montana</option>
                                        <option value="NE">Nebraska</option>
                                        <option value="NM">New Mexico</option>
                                        <option value="ND">North Dakota</option>
                                        <option value="UT">Utah</option>
                                        <option value="WY">Wyoming</option>
                                    </optgroup>
                                    <optgroup label="Central Time Zone">
                                        <option value="AL">Alabama</option>
                                        <option value="AR">Arkansas</option>
                                        <option value="IL">Illinois</option>
                                        <option value="IA">Iowa</option>
                                        <option value="KS">Kansas</option>
                                        <option value="KY">Kentucky</option>
                                        <option value="LA">Louisiana</option>
                                        <option value="MN">Minnesota</option>
                                        <option value="MS">Mississippi</option>
                                        <option value="MO">Missouri</option>
                                        <option value="OK">Oklahoma</option>
                                        <option value="SD">South Dakota</option>
                                        <option value="TX">Texas</option>
                                        <option value="TN">Tennessee</option>
                                        <option value="WI">Wisconsin</option>
                                    </optgroup>
                                    <optgroup label="Eastern Time Zone">
                                        <option value="CT">Connecticut</option>
                                        <option value="DE">Delaware</option>
                                        <option value="FL">Florida</option>
                                        <option value="GA">Georgia</option>
                                        <option value="IN">Indiana</option>
                                        <option value="ME">Maine</option>
                                        <option value="MD">Maryland</option>
                                        <option value="MA">Massachusetts</option>
                                        <option value="MI">Michigan</option>
                                        <option value="NH">New Hampshire</option>
                                        <option value="NJ">New Jersey</option>
                                        <option value="NY">New York</option>
                                        <option value="NC">North Carolina</option>
                                        <option value="OH">Ohio</option>
                                        <option value="PA">Pennsylvania</option>
                                        <option value="RI">Rhode Island</option>
                                        <option value="SC">South Carolina</option>
                                        <option value="VT">Vermont</option>
                                        <option value="VA">Virginia</option>
                                        <option value="WV">West Virginia</option>
                                    </optgroup>
                                </select>
                            </div>

                            <div class="col-md-6">
                                <h4 class="mb-3">Tags Input</h4>

                                <p class="text-muted font-weight-bold">Input Tags</p>
                                <p class="text-muted">
                                    Just add <code>data-role="tagsinput"</code> to your input field to automatically change it to a tags input field.
                                </p>
                                <div class="tags-default">
                                    <input type="text" value="Amsterdam,Washington,Sydney" data-role="tagsinput" placeholder="add tags" />
                                </div>

                                <p class="mt-3 font-weight-bold text-muted">True multi value</p>
                                <p class="text-muted">
                                    Use a <code>&lt;select multiple /&gt;</code> as your input element for a tags input, to gain true multivalue
                                    support.
                                    Instead of a comma separated string, the values will be set in an array. Existing <code>&lt;option /&gt;</code>
                                    elements will automatically be set as tags. This makes it also possible to create tags containing a comma.
                                </p>
                                <div class="m-b-0">
                                    <select multiple data-role="tagsinput">
                                        <option value="Amsterdam">Amsterdam</option>
                                        <option value="Washington">Washington</option>
                                        <option value="Sydney">Sydney</option>
                                        <option value="Beijing">Beijing</option>
                                        <option value="Cairo">Cairo</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <p class="text-muted mt-3">Multiple Select with Search</p>
                        <p class="text-muted">
                            Multiselect
                        </p>

                        <select class="form-control multiselect-search" multiple="multiple" multiple">
                            <optgroup label="Alaskan/Hawaiian Time Zone">
                                <option value="AK">Alaska</option>
                                <option value="HI">Hawaii</option>
                            </optgroup>
                            <optgroup label="Pacific Time Zone">
                                <option value="CA">California</option>
                                <option value="NV">Nevada</option>
                                <option value="OR">Oregon</option>
                                <option value="WA">Washington</option>
                            </optgroup>
                            <optgroup label="Mountain Time Zone">
                                <option value="AZ">Arizona</option>
                                <option value="CO">Colorado</option>
                                <option value="ID">Idaho</option>
                                <option value="MT">Montana</option>
                                <option value="NE">Nebraska</option>
                                <option value="NM">New Mexico</option>
                                <option value="ND">North Dakota</option>
                                <option value="UT">Utah</option>
                                <option value="WY">Wyoming</option>
                            </optgroup>
                            <optgroup label="Central Time Zone">
                                <option value="AL">Alabama</option>
                                <option value="AR">Arkansas</option>
                                <option value="IL">Illinois</option>
                                <option value="IA">Iowa</option>
                                <option value="KS">Kansas</option>
                                <option value="KY">Kentucky</option>
                                <option value="LA">Louisiana</option>
                                <option value="MN">Minnesota</option>
                                <option value="MS">Mississippi</option>
                                <option value="MO">Missouri</option>
                                <option value="OK">Oklahoma</option>
                                <option value="SD">South Dakota</option>
                                <option value="TX">Texas</option>
                                <option value="TN">Tennessee</option>
                                <option value="WI">Wisconsin</option>
                            </optgroup>
                            <optgroup label="Eastern Time Zone">
                                <option value="CT">Connecticut</option>
                                <option value="DE">Delaware</option>
                                <option value="FL">Florida</option>
                                <option value="GA">Georgia</option>
                                <option value="IN">Indiana</option>
                                <option value="ME">Maine</option>
                                <option value="MD">Maryland</option>
                                <option value="MA">Massachusetts</option>
                                <option value="MI">Michigan</option>
                                <option value="NH">New Hampshire</option>
                                <option value="NJ">New Jersey</option>
                                <option value="NY">New York</option>
                                <option value="NC">North Carolina</option>
                                <option value="OH">Ohio</option>
                                <option value="PA">Pennsylvania</option>
                                <option value="RI">Rhode Island</option>
                                <option value="SC">South Carolina</option>
                                <option value="VT">Vermont</option>
                                <option value="VA">Virginia</option>
                                <option value="WV">West Virginia</option>
                            </optgroup>
                        </select>

                        <hr class="my-5">

                        <h2 class="font-weight-bold">Form Mask</h2>

                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-3">Input Masks</h4>
                                <p class="text-muted">
                                    Your awesome text goes here.Your awesome text goes here.
                                </p>

                                <form action="#">
                                    <div class="form-group">
                                        <label>ISBN 1</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '999-99-999-9999-9'" class="form-control">
                                        <span class="text-muted">e.g "999-99-999-9999-9"</span>
                                    </div>
                                    <div class="form-group">
                                        <label>ISBN 2</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '999 99 999 9999 9'" class="form-control">
                                        <span class="text-muted">999 99 999 9999 9</span>
                                    </div>
                                    <div class="form-group">
                                        <label>ISBN 3</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '999/99/999/9999/9'" class="form-control">
                                        <span class="text-muted">999/99/999/9999/9</span>
                                    </div>
                                    <div class="form-group">
                                        <label>IPV4</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '999.999.999.999'" class="form-control">
                                        <span class="text-muted">192.168.110.310</span>
                                    </div>
                                    <div class="form-group m-b-0">
                                        <label>IPV6</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '9999:9999:9999:9:999:9999:9999:9999'" class="form-control">
                                        <span class="text-muted">4deg:1340:6547:2:540:h8je:ve73:98pd</span>
                                    </div>
                                </form>
                            </div>
                            <div class="col-md-6">
                                <h4 class="mb-3">Input Masks</h4>
                                <p class="text-muted">
                                    Your awesome text goes here.Your awesome text goes here.
                                </p>

                                <form action="#">
                                    <div class="form-group">
                                        <label>Tax ID</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '99-9999999'" class="form-control">
                                        <span class="text-muted">99-9999999</span>
                                    </div>
                                    <div class="form-group">
                                        <label>Phone</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '(999) 999-9999'" class="form-control">
                                        <span class="text-muted">(999) 999-9999</span>
                                    </div>
                                    <div class="form-group">
                                        <label>Currency</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '$ 999,999,999.99'" class="form-control">
                                        <span class="text-muted">$ 999,999,999.99</span>
                                    </div>
                                    <div class="form-group">
                                        <label>Date</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '99/99/9999'" class="form-control">
                                        <span class="text-muted">dd/mm/yyyy</span>
                                    </div>
                                    <div class="form-group m-b-0">
                                        <label>Date 2</label>
                                        <input type="text" placeholder="" data-inputmask="'mask' : '99-99-9999'" class="form-control">
                                        <span class="text-muted">dd-mm-yyyy</span>
                                    </div>

                                </form>
                            </div>
                        </div>

                        <hr class="my-5">

                        <h2 class="font-weight-bold">Form Pickers</h2>

                        <div class="row">
                            <div class="col-md-12">
                                <h4 class="mb-3">Colorpicker</h4>
                                <p>Bootstrap Colorpicker is a modular color picker plugin for Bootstrap 4.</p>
                                <div class="form-group">
                                    <input type="text" class="form-control color-picker">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-3">Timepicker</h4>
                                <p class="text-muted">
                                    Easily select a time for a text input using your mouse or keyboards arrow keys.
                                </p>

                                <div class="form-group">
                                    <label>Default Time Picker</label>

                                    <div class="input-group">
                                        <input type="text" class="form-control timepicker">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fas fa-clock"></i></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label>24 Hour Mode Time Picker</label>

                                    <div class="input-group">
                                        <input type="text" class="form-control timepicker-24">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fas fa-clock"></i></span>
                                        </div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    <label>Specify a step for the minute field</label>

                                    <div class="input-group">
                                        <input type="text" class="form-control timepicker-step">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fas fa-clock"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <h4 class="mb-3">Date Range Picker</h4>
                                <p class="text-muted">
                                    A JavaScript component for choosing date ranges.
                                    Designed to work with the Bootstrap CSS framework.
                                </p>

                                <form>
                                    <div class="form-group">
                                        <label>With all options</label>
                                        <input type="text" class="form-control reportrange" />
                                    </div>
                                    <div class="form-group">
                                        <label>Date Range Pick</label>
                                        <div>
                                            <input class="form-control input-daterange-datepicker" type="text" name="daterange" value="01/01/2017 - 01/31/2018" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Date Range With Time</label>
                                        <div>
                                            <input type="text" class="form-control input-daterange-timepicker" name="daterange" value="01/01/2017 1:30 PM - 01/01/2017 2:00 PM" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Limit Selectable Dates</label>
                                        <div>
                                            <input class="form-control input-limit-datepicker" type="text" name="daterange" value="06/01/2017 - 06/07/2017" />
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <h4 class="mb-3">Date Picker</h4>
                                <p class="text-muted">
                                    The datepicker is tied to a standard form input field. Click on the input to open
                                    an interactive calendar in a small overlay. Click elsewhere on the page or hit the Esc
                                    key to close. If a date is chosen, feedback is shown as the input's value.
                                </p>

                                <form action="#">
                                    <div class="row">
                                        <div class="col-lg-8">
                                            <div class="form-group">
                                                <label>Default Functionality</label>
                                                <div>
                                                    <div class="input-group">
                                                        <input type="text" class="form-control datepicker" placeholder="mm/dd/yyyy">
                                                        <div class="input-group-append">
                                                            <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label>Auto Close</label>
                                                <div>
                                                    <div class="input-group">
                                                        <input type="text" class="form-control datepicker-autoclose" placeholder="mm/dd/yyyy">
                                                        <div class="input-group-append">
                                                            <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label>Multiple Date</label>
                                                <div>
                                                    <div class="input-group">
                                                        <input type="text" class="form-control datepicker-multiple-date" placeholder="mm/dd/yyyy">
                                                        <div class="input-group-append">
                                                            <span class="input-group-text"><i class="fas fa-calendar"></i></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label>Date Range</label>
                                                <div>
                                                    <div class="input-daterange input-group date-range" id="date-range">
                                                        <input type="text" class="form-control" name="start" />
                                                        <input type="text" class="form-control" name="end" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-4">
                                            <label>Display Inline</label>
                                            <div class="center-block" style="margin: 10px auto">
                                                <div class="datepicker-inline"></div>
                                            </div><!-- input-group -->
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>

                        <hr class="my-5">

                        <h2 class="font-weight-bold">Form Validation</h2>

                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-3">Basic Form</h4>
                                <p class="text-muted">
                                    Parsley is a javascript form validation library. It helps you provide your users with feedback on
                                    their form submission before sending it to your server.
                                </p>

                                <form action="#" class="form-validation">
                                    <div class="form-group">
                                        <label for="userName">User Name<span class="text-danger">*</span></label>
                                        <input type="text" name="nick" parsley-trigger="change" required placeholder="Enter user name"
                                               class="form-control" id="userName">
                                    </div>
                                    <div class="form-group">
                                        <label for="emailAddress">Email address<span class="text-danger">*</span></label>
                                        <input type="email" name="email" parsley-trigger="change" required placeholder="Enter email"
                                               class="form-control" id="emailAddress">
                                    </div>
                                    <div class="form-group">
                                        <label for="pass1">Password<span class="text-danger">*</span></label>
                                        <input id="pass1" type="password" placeholder="Password" required class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="passWord2">Confirm Password <span class="text-danger">*</span></label>
                                        <input data-parsley-equalto="#pass1" type="password" required placeholder="Password" class="form-control"
                                               id="passWord2">
                                    </div>
                                    <div class="form-group">
                                        <div class="checkbox checkbox-purple">
                                            <input id="checkbox6a" type="checkbox">
                                            <label for="checkbox6a">
                                                Remember me
                                            </label>
                                        </div>

                                    </div>

                                    <div class="form-group text-right m-b-0">
                                        <button class="btn btn-primary" type="submit">
                                            Submit
                                        </button>
                                        <button type="reset" class="btn btn-light">
                                            Cancel
                                        </button>
                                    </div>

                                </form>
                            </div>

                            <div class="col-md-6">
                                <h4 class="mb-3">Horizontal Form</h4>
                                <p class="text-muted">
                                    Parsley is a javascript form validation library. It helps you provide your users with feedback on
                                    their form submission before sending it to your server.
                                </p>

                                <form role="form" class="form-validation">
                                    <div class="form-group row">
                                        <label for="inputEmail3" class="col-4 col-form-label">Email<span class="text-danger">*</span></label>
                                        <div class="col-7">
                                            <input type="email" required parsley-type="email" class="form-control" id="inputEmail3"
                                                   placeholder="Email">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="hori-pass1" class="col-4 col-form-label">Password<span class="text-danger">*</span></label>
                                        <div class="col-7">
                                            <input id="hori-pass1" type="password" placeholder="Password" required class="form-control">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="hori-pass2" class="col-4 col-form-label">Confirm Password
                                            <span class="text-danger">*</span></label>
                                        <div class="col-7">
                                            <input data-parsley-equalto="#hori-pass1" type="password" required placeholder="Password"
                                                   class="form-control" id="hori-pass2">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="webSite" class="col-4 col-form-label">Web Site<span class="text-danger">*</span></label>
                                        <div class="col-7">
                                            <input type="url" required parsley-type="url" class="form-control" id="webSite" placeholder="URL">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-8 offset-4">
                                            <div class="checkbox checkbox-purple">
                                                <input id="checkbox6" type="checkbox">
                                                <label for="checkbox6">
                                                    Remember me
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-8 offset-4">
                                            <button type="submit" class="btn btn-primary">
                                                Register
                                            </button>
                                            <button type="reset" class="btn btn-light">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <div class="col-md-6">
                                <h4 class="mb-3">Validation type</h4>
                                <p class="text-muted">
                                    Parsley is a javascript form validation library. It helps you provide your users with feedback on
                                    their form submission before sending it to your server.
                                </p>

                                <form class="form-validation" action="#">
                                    <div class="form-group">
                                        <label>Required</label>
                                        <input type="text" class="form-control" required placeholder="Type something" />
                                    </div>

                                    <div class="form-group">
                                        <label>Equal To</label>
                                        <div>
                                            <input type="password" id="pass2" class="form-control" required placeholder="Password" />
                                        </div>
                                        <div class="mt-2">
                                            <input type="password" class="form-control" required data-parsley-equalto="#pass2"
                                                   placeholder="Re-Type Password" />
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>E-Mail</label>
                                        <div>
                                            <input type="email" class="form-control" required parsley-type="email" placeholder="Enter a valid e-mail" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>URL</label>
                                        <div>
                                            <input parsley-type="url" type="url" class="form-control" required placeholder="URL" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Digits</label>
                                        <div>
                                            <input data-parsley-type="digits" type="text" class="form-control" required placeholder="Enter only digits" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Number</label>
                                        <div>
                                            <input data-parsley-type="number" type="text" class="form-control" required placeholder="Enter only numbers" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Alphanumeric</label>
                                        <div>
                                            <input data-parsley-type="alphanum" type="text" class="form-control" required placeholder="Enter alphanumeric value" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Textarea</label>
                                        <div>
                                            <textarea required class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div>
                                            <button type="submit" class="btn btn-primary">
                                                Submit
                                            </button>
                                            <button type="reset" class="btn btn-light">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <div class="col-md-6">
                                <h4 class="mb-3">Range validation</h4>
                                <p class="text-muted">
                                    Parsley is a javascript form validation library. It helps you provide your users with feedback on
                                    their form submission before sending it to your server.
                                </p>

                                <form action="#" class="form-validation">

                                    <div class="form-group">
                                        <label>Min Length</label>
                                        <div>
                                            <input type="text" class="form-control" required data-parsley-minlength="6" placeholder="Min 6 chars." />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Max Length</label>
                                        <div>
                                            <input type="text" class="form-control" required data-parsley-maxlength="6" placeholder="Max 6 chars." />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Range Length</label>
                                        <div>
                                            <input type="text" class="form-control" required data-parsley-length="[5,10]" placeholder="Text between 5 - 10 chars length" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Min Value</label>
                                        <div>
                                            <input type="text" class="form-control" required data-parsley-min="6" placeholder="Min value is 6" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Max Value</label>
                                        <div>
                                            <input type="text" class="form-control" required data-parsley-max="6" placeholder="Max value is 6" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Range Value</label>
                                        <div>
                                            <input class="form-control" required type="text" min="6" max="100" placeholder="Number between 6 - 100" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Regular Exp</label>
                                        <div>
                                            <input type="text" class="form-control" required data-parsley-pattern="#[A-Fa-f0-9]{6}"
                                                   placeholder="Hex. Color" />
                                        </div>
                                    </div>

                                    <div class="form-group m-b-0">
                                        <div>
                                            <button type="submit" class="btn btn-primary">
                                                Submit
                                            </button>
                                            <button type="reset" class="btn btn-light">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <hr class="my-5">


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>