<div class="page-form">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <h5 class="mb-0">Form</h5>
                            </div>
                            <div class="col-auto ml-auto">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    Cancel
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <h2 class="font-weight-bold">Form Basic</h2>

                        <h4 class="mb-3">Input Type</h4>
                        <p class="text-muted">
                            Most common form control, text-based input fields. Includes support for all HTML5 types: <code>text</code>, <code>password</code>,
                            <code>datetime</code>, <code>datetime-local</code>, <code>date</code>, <code>month</code>, <code>time</code>, <code>week</code>,
                            <code>number</code>, <code>email</code>, <code>url</code>, <code>search</code>, <code>tel</code>, and <code>color</code>.
                        </p>

                        <div class="row">
                            <div class="col-12">
                                <div>
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label>Text</label>
                                            <input type="text" class="form-control" value="Some text value...">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email">Email</label>
                                            <input type="email" id="example-email" name="example-email" class="form-control" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" value="password">
                                        </div>

                                        <div class="form-group">
                                            <label>Placeholder</label>
                                            <input type="text" class="form-control" placeholder="placeholder">
                                        </div>
                                        <div class="form-group">
                                            <label>Text area</label>
                                            <textarea class="form-control" rows="5"></textarea>
                                        </div>

                                        <div class="form-group">
                                            <label>Readonly</label>
                                            <input type="text" class="form-control" readonly="" value="Readonly value">
                                        </div>
                                        <div class="form-group">
                                            <label>Disabled</label>
                                            <input type="text" class="form-control" disabled="" value="Disabled value">
                                        </div>

                                        <div class="form-group">
                                            <label>Static control</label>
                                            <p class="form-control-static">email@example.com</p>
                                        </div>
                                        <div class="form-group">
                                            <label>Helping text</label>
                                            <input type="text" class="form-control" placeholder="Helping text">
                                            <span class="help-block"><small>A block of help text that breaks onto a new line and may extend
                                                beyond one line.</small></span>
                                        </div>

                                        <div class="form-group">
                                            <label>Input Select</label>
                                            <select class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                            <h6>Multiple select</h6>
                                            <select multiple class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Default file input</label>
                                            <input type="file" class="form-control">
                                        </div>

                                        <div class="form-group">
                                            <label>Date</label>
                                            <input class="form-control" type="date" name="date">
                                        </div>

                                        <div class="form-group">
                                            <label>Month</label>
                                            <input class="form-control" type="month" name="month">
                                        </div>

                                        <div class="form-group">
                                            <label>Time</label>
                                            <input class="form-control" type="time" name="time">
                                        </div>

                                        <div class="form-group">
                                            <label>Week</label>
                                            <input class="form-control" type="week" name="week">
                                        </div>

                                        <div class="form-group">
                                            <label>Number</label>
                                            <input class="form-control" type="number" name="number">
                                        </div>

                                        <div class="form-group">
                                            <label>URL</label>
                                            <input class="form-control" type="url" name="url">
                                        </div>

                                        <div class="form-group">
                                            <label>Search</label>
                                            <input class="form-control" type="search" name="search">
                                        </div>

                                        <div class="form-group">
                                            <label>Tel</label>
                                            <input class="form-control" type="tel" name="tel">
                                        </div>

                                        <div class="form-group">
                                            <label>Color</label>
                                            <input class="form-control" type="color" name="color">
                                        </div>

                                        <div class="form-group">
                                            <label>Range</label>
                                            <input class="form-control" type="range" name="range" min="0" max="10">
                                        </div>

                                    </form>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-3">Select menu</h4>
                                <p class="text-muted">
                                    Custom <code class="highlighter-rouge">&lt;select&gt;</code> menus need only a custom class, <code class="highlighter-rouge">.custom-select</code>
                                    to trigger the custom styles.
                                </p>

                                <select class="custom-select">
                                    <option selected>Open this select menu</option>
                                    <option value="1">One</option>
                                    <option value="2">Two</option>
                                    <option value="3">Three</option>
                                </select>
                            </div>

                            <div class="col-md-6">
                                <h4 class="mb-3">Checkboxes and radios</h4>
                                <div>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck1">
                                        <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
                                    </div>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck2">
                                        <label class="custom-control-label" for="customCheck2">Check this custom checkbox</label>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <div class="custom-control custom-radio">
                                        <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
                                        <label class="custom-control-label" for="customRadio1">Toggle this custom radio</label>
                                    </div>
                                    <div class="custom-control custom-radio">
                                        <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                                        <label class="custom-control-label" for="customRadio2">Or toggle this other custom radio</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>