<div class="page-form">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <h5 class="mb-0">Form</h5>
                            </div>
                            <div class="col-auto ml-auto">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    Cancel
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div>
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label>Text</label>
                                            <input type="text" class="form-control" value="Some text value...">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email">Email</label>
                                            <input type="email" id="example-email" name="example-email" class="form-control" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" value="password">
                                        </div>

                                        <div class="form-group">
                                            <label>Placeholder</label>
                                            <input type="text" class="form-control" placeholder="placeholder">
                                        </div>
                                        <div class="form-group">
                                            <label>Text area</label>
                                            <textarea class="form-control" rows="5"></textarea>
                                        </div>

                                        <div class="form-group">
                                            <label>Readonly</label>
                                            <input type="text" class="form-control" readonly="" value="Readonly value">
                                        </div>
                                        <div class="form-group">
                                            <label>Disabled</label>
                                            <input type="text" class="form-control" disabled="" value="Disabled value">
                                        </div>

                                        <div class="form-group">
                                            <label>Static control</label>
                                            <p class="form-control-static">email@example.com</p>
                                        </div>
                                        <div class="form-group">
                                            <label>Helping text</label>
                                            <input type="text" class="form-control" placeholder="Helping text">
                                            <span class="help-block"><small>A block of help text that breaks onto a new line and may extend
                                                beyond one line.</small></span>
                                        </div>

                                        <div class="form-group">
                                            <label>Input Select</label>
                                            <select class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                            <h6>Multiple select</h6>
                                            <select multiple class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Default file input</label>
                                            <input type="file" class="form-control">
                                        </div>

                                        <div class="form-group">
                                            <label>Date</label>
                                            <input class="form-control" type="date" name="date">
                                        </div>

                                        <div class="form-group">
                                            <label>Month</label>
                                            <input class="form-control" type="month" name="month">
                                        </div>

                                        <div class="form-group">
                                            <label>Time</label>
                                            <input class="form-control" type="time" name="time">
                                        </div>

                                        <div class="form-group">
                                            <label>Week</label>
                                            <input class="form-control" type="week" name="week">
                                        </div>

                                        <div class="form-group">
                                            <label>Number</label>
                                            <input class="form-control" type="number" name="number">
                                        </div>

                                        <div class="form-group">
                                            <label>URL</label>
                                            <input class="form-control" type="url" name="url">
                                        </div>

                                        <div class="form-group">
                                            <label>Search</label>
                                            <input class="form-control" type="search" name="search">
                                        </div>

                                        <div class="form-group">
                                            <label>Tel</label>
                                            <input class="form-control" type="tel" name="tel">
                                        </div>

                                        <div class="form-group">
                                            <label>Color</label>
                                            <input class="form-control" type="color" name="color">
                                        </div>

                                        <div class="form-group">
                                            <label>Range</label>
                                            <input class="form-control" type="range" name="range" min="0" max="10">
                                        </div>

                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <h5 class="mb-0">Form</h5>
                            </div>
                            <div class="col-auto ml-auto">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    Cancel
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div>
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label>Text</label>
                                            <input type="text" class="form-control" value="Some text value...">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email">Email</label>
                                            <input type="email" id="example-email" name="example-email" class="form-control" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" value="password">
                                        </div>

                                        <div class="form-group">
                                            <label>Placeholder</label>
                                            <input type="text" class="form-control" placeholder="placeholder">
                                        </div>
                                        <div class="form-group">
                                            <label>Text area</label>
                                            <textarea class="form-control" rows="5"></textarea>
                                        </div>

                                        <div class="form-group">
                                            <label>Readonly</label>
                                            <input type="text" class="form-control" readonly="" value="Readonly value">
                                        </div>
                                        <div class="form-group">
                                            <label>Disabled</label>
                                            <input type="text" class="form-control" disabled="" value="Disabled value">
                                        </div>

                                        <div class="form-group">
                                            <label>Static control</label>
                                            <p class="form-control-static">email@example.com</p>
                                        </div>
                                        <div class="form-group">
                                            <label>Helping text</label>
                                            <input type="text" class="form-control" placeholder="Helping text">
                                            <span class="help-block"><small>A block of help text that breaks onto a new line and may extend
                                                beyond one line.</small></span>
                                        </div>

                                        <div class="form-group">
                                            <label>Input Select</label>
                                            <select class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                            <h6>Multiple select</h6>
                                            <select multiple class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Default file input</label>
                                            <input type="file" class="form-control">
                                        </div>

                                        <div class="form-group">
                                            <label>Date</label>
                                            <input class="form-control" type="date" name="date">
                                        </div>

                                        <div class="form-group">
                                            <label>Month</label>
                                            <input class="form-control" type="month" name="month">
                                        </div>

                                        <div class="form-group">
                                            <label>Time</label>
                                            <input class="form-control" type="time" name="time">
                                        </div>

                                        <div class="form-group">
                                            <label>Week</label>
                                            <input class="form-control" type="week" name="week">
                                        </div>

                                        <div class="form-group">
                                            <label>Number</label>
                                            <input class="form-control" type="number" name="number">
                                        </div>

                                        <div class="form-group">
                                            <label>URL</label>
                                            <input class="form-control" type="url" name="url">
                                        </div>

                                        <div class="form-group">
                                            <label>Search</label>
                                            <input class="form-control" type="search" name="search">
                                        </div>

                                        <div class="form-group">
                                            <label>Tel</label>
                                            <input class="form-control" type="tel" name="tel">
                                        </div>

                                        <div class="form-group">
                                            <label>Color</label>
                                            <input class="form-control" type="color" name="color">
                                        </div>

                                        <div class="form-group">
                                            <label>Range</label>
                                            <input class="form-control" type="range" name="range" min="0" max="10">
                                        </div>

                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col-auto">
                                <h5 class="mb-0">Form</h5>
                            </div>
                            <div class="col-auto ml-auto">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    Cancel
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <div>
                                    <form class="form-horizontal" role="form">
                                        <div class="form-group">
                                            <label>Text</label>
                                            <input type="text" class="form-control" value="Some text value...">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email">Email</label>
                                            <input type="email" id="example-email" name="example-email" class="form-control" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label>Password</label>
                                            <input type="password" class="form-control" value="password">
                                        </div>

                                        <div class="form-group">
                                            <label>Placeholder</label>
                                            <input type="text" class="form-control" placeholder="placeholder">
                                        </div>
                                        <div class="form-group">
                                            <label>Text area</label>
                                            <textarea class="form-control" rows="5"></textarea>
                                        </div>

                                        <div class="form-group">
                                            <label>Readonly</label>
                                            <input type="text" class="form-control" readonly="" value="Readonly value">
                                        </div>
                                        <div class="form-group">
                                            <label>Disabled</label>
                                            <input type="text" class="form-control" disabled="" value="Disabled value">
                                        </div>

                                        <div class="form-group">
                                            <label>Static control</label>
                                            <p class="form-control-static">email@example.com</p>
                                        </div>
                                        <div class="form-group">
                                            <label>Helping text</label>
                                            <input type="text" class="form-control" placeholder="Helping text">
                                            <span class="help-block"><small>A block of help text that breaks onto a new line and may extend
                                                beyond one line.</small></span>
                                        </div>

                                        <div class="form-group">
                                            <label>Input Select</label>
                                            <select class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                            <h6>Multiple select</h6>
                                            <select multiple class="form-control">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Default file input</label>
                                            <input type="file" class="form-control">
                                        </div>

                                        <div class="form-group">
                                            <label>Date</label>
                                            <input class="form-control" type="date" name="date">
                                        </div>

                                        <div class="form-group">
                                            <label>Month</label>
                                            <input class="form-control" type="month" name="month">
                                        </div>

                                        <div class="form-group">
                                            <label>Time</label>
                                            <input class="form-control" type="time" name="time">
                                        </div>

                                        <div class="form-group">
                                            <label>Week</label>
                                            <input class="form-control" type="week" name="week">
                                        </div>

                                        <div class="form-group">
                                            <label>Number</label>
                                            <input class="form-control" type="number" name="number">
                                        </div>

                                        <div class="form-group">
                                            <label>URL</label>
                                            <input class="form-control" type="url" name="url">
                                        </div>

                                        <div class="form-group">
                                            <label>Search</label>
                                            <input class="form-control" type="search" name="search">
                                        </div>

                                        <div class="form-group">
                                            <label>Tel</label>
                                            <input class="form-control" type="tel" name="tel">
                                        </div>

                                        <div class="form-group">
                                            <label>Color</label>
                                            <input class="form-control" type="color" name="color">
                                        </div>

                                        <div class="form-group">
                                            <label>Range</label>
                                            <input class="form-control" type="range" name="range" min="0" max="10">
                                        </div>

                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>