<div class="page-system">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header p-0 px-3">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">Members</h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <div class="nav-pages">
                                            <ul class="nav">
                                                <li class="nav-item">
                                                    <a href="<?= base_url('members'); ?>" class="nav-link active" data-toggle="tooltip" title="Grid View">
                                                        <i class="fas fa-th-large"></i>
                                                    </a>
                                                </li>
                                                <li class="nav-item">
                                                    <a href="<?= base_url('members/table'); ?>" class="nav-link" data-toggle="tooltip" title="Table View">
                                                        <i class="fas fa-table"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-auto">
                                        <a href="<?=base_url('members/form');?>" class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?=current_url();?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <?php foreach($entries as $entry): ?>
                                                    <option value="<?php echo $entry; ?>" <?php echo ($get->entries == $entry ? 'selected' : ''); ?>><?php echo $entry; ?></option>
                                                <?php endforeach; ?>
                                                <option value="ALL" <?= ($get->entries ? (!is_numeric($get->entries) ? 'selected' : '') : '') ?>><?php echo $language->getLine('ALL') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Period</span>
                                            </div>
                                            <input class="form-control input-daterange-datepicker-empty" type="text" name="period" value="<?= ($get->period ? $get->period : '') ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Member Name" value="<?= ($get->keyword ? $get->keyword : '') ?>" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="<?= base_url('members') ?>">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <?php if ($members): ?>
            <?php foreach ($members as $member): ?>
                        <div class="card">
                            <div class="card-body">
                                <div class="row justify-content-between">
                                    <div class="col">
                                        <div class="row">
                                            <div class="col-md-auto">
                                                <div class="media align-items-center">
                                                    <div class="avatar-80 mr-3">
                                                        <img src="<?= $member->image ?>" alt="">
                                                    </div>
                                                    <div class="media-body">
                                                        <h5>
                                                            <a href="<?=base_url('members/detail/'.$member->id);?>">
                                                                <?= $member->fullname ?>
                                                            </a>
                                                        </h5>
                                                        <div class="d-block">
                                                            <?php if ($member->metadata('username')): ?>
                                                                <a href="<?=base_url('members/detail/'.$member->id);?>" class="btn btn-xs btn-default btn-icon mr-1 mb-1"> <i class="fa fa-at"></i> <?= $member->metadata('username')->username ?> </a>
                                                            <?php endif; ?>
                                                            <?php if ($member->metadata('email')): ?>
                                                                <a href="mailto:<?= $member->metadata('email')->email ?>" class="btn btn-xs btn-default btn-icon mr-1 mb-1"> <i class="fa fa-envelope"></i> <?= $member->metadata('email')->email ?> </a>
                                                            <?php endif; ?>
                                                            <?php if ($member->metadata('phone')): ?>
                                                                <a href="tel:<?= $member->metadata('phone')->phone ?>" class="btn btn-xs btn-default btn-icon mr-1 mb-1"> <i class="fa fa-phone"></i> <?= $member->metadata('phone')->phone ?> </a>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div class="d-flex flex-wrap">
                                                            <div class="btn-group btn-group-xs mr-2 mb-2"> 
                                                                <span class="btn btn-default btn-xs"><?=language('DATE_JOIN');?> </span>
                                                                <span class="btn btn-xs btn-default"><?= date('j F Y', strtotime($member->record->create->timestamp)) ?></span>
                                                            </div>
                                                            <div class="btn-group btn-group-xs mr-2 mb-2"> 
                                                                <span class="btn btn-default btn-xs"> <?=language('STATUS');?> </span>
                                                                <span class="btn btn-xs btn-default"><?= $member->record->status ?></span>
                                                            </div>
                                                            <div class="btn-group btn-group-xs mr-2 mb-2"> 
                                                                <span class="btn btn-default btn-xs"> <?=language('TRANSACTIONS');?> </span>
                                                                <span class="btn btn-xs btn-default">321</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <div class="dropdown text-right">
                                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" href="<?php echo base_url('members/form/'.$member->id); ?>">
                                                    <i class="fas fa-pencil-alt"></i>
                                                    Edit
                                                </a>
                                                <a class="dropdown-item" href="<?=base_url('members/detail/'.$member->id);?>">
                                                    <i class="fa fa-eye"></i>
                                                    View
                                                </a>
                                                <!-- <a class="dropdown-item" href="#">
                                                    <i class="fas fa-chart-bar"></i>
                                                    Stats
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                    <i class="fa fa-copy"></i>
                                                    Copy
                                                </a> -->
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="<?= base_url('/members/delete/'.$member->id) ?>">
                                                    <i class="fa fa-trash"></i>
                                                    Trash
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
            <?php endforeach; ?>
            <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('members', [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('members', [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $members->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="period" value="<?= $get->period ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $members->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$members->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
        <?php endif; ?>

    </div>
</div>