<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <h3 class="mb-4">Detail Country</h3>
                    </div>
                </div>

                <div class="card">
                    <div class="table-responsive">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Name</th>
                                    <td><?= $country->name; ?></td>
                                </tr>
                                <tr>
                                    <th>Code String</th>
                                    <td><?= $country->code_string; ?></td>
                                </tr>
                                <tr>
                                    <th>Code Num</th>
                                    <td><?= $country->code_num; ?></td>
                                </tr>
                                <tr>
                                    <th>Code Iso</th>
                                    <td><?= $country->code_iso; ?></td>
                                </tr>
                                <tr>
                                    <th>Code Iso3</th>
                                    <td><?= $country->code_iso3; ?></td>
                                </tr>
                                <tr>
                                    <th>Code Phone</th>
                                    <td><?= $country->code_phone; ?></td>
                                </tr>
                                <tr>
                                    <th>Record Status</th>
                                    <td><?= $country->record_status; ?></td>
                                </tr>
                                <tr>
                                    <th>Date Created</th>
                                    <td><?= $country->record_create_timestamp; ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <?php //echo view('components/pagination', [], true); ?>
                
            </div>
        </div>
    </div>
</div>