<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">
                            <?php echo $tabs; ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">

                            </div>
                            <div class="col-auto">
                                <a href="<?=base_url('settings/users/form');?>" class="btn btn-primary">
                                    <?php echo language('ADD_NEW_USER'); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="list-group user-list">
                    <div class="list-group-item">
                        <div class="media align-items-center">
                            <div class="avatar avatar-70 mr-3">
                                <img src="assets/img/avatar-male.png">
                            </div>
                            <div class="media-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h5 class="mb-0">
                                        <a href="#">Circle Creative</a>
                                    </h5>
                                    <h6 class="mb-1">
                                        <span class="text-lowercase">@developer</span>
                                    </h6>
                                    <button class="btn btn-primary btn-xs btn-icon">
                                        <i class="fas fa-user-lock"></i> Developer
                                    </button>
                                </div>
                                <div class="user-action">
                                    <div class="dropdown">
                                        <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="#">
                                                <i class="fas fa-pencil-alt"></i>
                                                Edit
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-trash"></i>
                                                Delete
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="list-group-item">
                        <div class="media align-items-center">
                            <div class="avatar avatar-70 mr-3">
                                <img src="assets/img/avatar-male.png">
                            </div>
                            <div class="media-body d-flex align-items-center justify-content-between">
                                <div>
                                    <h5 class="mb-0">
                                        <a href="#">Circle Creative</a>
                                    </h5>
                                    <h6 class="mb-1">
                                        <span class="text-lowercase">@developer</span>
                                    </h6>
                                    <button class="btn btn-primary btn-xs btn-icon">
                                        <i class="fas fa-user-lock"></i> Developer
                                    </button>
                                </div>
                                <div class="user-action">
                                    <div class="dropdown">
                                        <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="#">
                                                <i class="fas fa-pencil-alt"></i>
                                                Edit
                                            </a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">
                                                <i class="fa fa-trash"></i>
                                                Delete
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>