<!DOCTYPE html>
<html>
<head>
    <title>{{$meta->title}}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {{ $assets->head }}

	<script type="text/javascript">
        var ajaxSettings = {
            "async": true,
            "crossDomain": true,
            "method": "GET",
            "headers": {
                "X-WEB-TOKEN": "<?=config('web-token')?>>",
            }
        }
	</script>
</head>
<body class="venus-admin">
    <header class="header">
        {{$partials->header}}
    </header>
    <aside class="sidebar-left">
        {{$partials->sidebar}}
    </aside>
    <main id="page-content" class="main">
        {{$partials->content}}
    </main>
    <?php if (null !== ($message = $session->getFlash('success'))): ?>
        <script type="text/javascript">
            Swal.fire({
                title: '<?php echo language('ALERT_SUCCESS_HEADING'); ?>',
                text: '<?php echo $message; ?>',
                type: 'success'
            })
        </script>
    <?php elseif (null !== ($message = $session->getFlash('danger'))): ?>
        <script type="text/javascript">
            Swal.fire({
                title: '<?php echo language('ALERT_DANGER_HEADING'); ?>',
                text: '<?php echo $message; ?>',
                type: 'error'
            })
        </script>
    <?php endif; ?>
    {{ $assets->body }}
</body>
</html>
