<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
        	<div class="card-header">Global Config</div>
            <div class="card-body">
            	<form>
	            	<div class="row">
	            		<div class="col-md-6">
	            			<h6>Site Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Site Name</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="O2System">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Site Offline</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Mouse-over Edit Icons for</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>Modules</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Default Editor</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>TinyMCE</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Default Captcha</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>none</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Default Access Level</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>Public</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Default List Limit</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>20</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Default Feed Limit</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>10</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Feed Email Address</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>Author</option>
							      	</select>
							    </div>
							</div>

							<h6 class="mt-5">Metadata Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Site Meta Descriptions</label>
							    <div class="col-sm-7">
							      	<textarea class="form-control">O2System is Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							      	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</textarea>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Site Meta Keywords</label>
							    <div class="col-sm-7">
							      	<textarea class="form-control">O2System is Lorem ipsum dolor sit amet</textarea>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Robots</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>Index, Follow</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Content Rights</label>
							    <div class="col-sm-7">
							      	<textarea class="form-control"></textarea>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Show Author Meta Tag</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Show O2System Version</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>
	            		</div>
	            		<div class="col-md-6">
	            			<h6>SEO Settings</h6>
	            			<div class="form-group row">
								<label class="col-sm-5 col-form-label">Search Engine Friendly URLs</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" checked class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Use URL Rewriting</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Add Suffix to URL</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Unicode Aliases</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Site Name in Page Titles</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>No</option>
							      	</select>
							    </div>
							</div>

							<h6 class="mt-5">Cookie Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Cookie Domain</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Cookie Path</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control">
							    </div>
							</div>
	            		</div>
	            	</div>
	            </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>