<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
        	<div class="card-header">System Config</div>
            <div class="card-body">
            	<form>
	            	<div class="row">
	            		<div class="col-md-6">
	            			<h6>System Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Path to Log Folder</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="home/public_html">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Help Server</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>English (GB)</option>
							      	</select>
							    </div>
							</div>

							<h6 class="mt-5">Debug Setting</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Debug System</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Debug Language</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>

							<h6 class="mt-5">Session Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Session Handler</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>Database</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Session Lifetime</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="15">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Shared Session</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
	            		</div>
	            		<div class="col-md-6">
	            			<h6>Cache Settings</h6>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Cache Handler</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>File</option>
							      	</select>
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Path to Cache Folder</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="home/public_html">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Cache Time</label>
							    <div class="col-sm-7">
							      	<input type="text" class="form-control" value="15">
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">Platform Specific Caching</label>
							    <div class="col-sm-7">
							      	<input type="checkbox" class="js-switch" data-color="#009efb" />
							    </div>
							</div>
							<div class="form-group row">
								<label class="col-sm-5 col-form-label">System Cache</label>
							    <div class="col-sm-7">
							      	<select class="form-control custom-select">
										<option>OFF - Disbled Cache</option>
							      	</select>
							    </div>
							</div>
	            		</div>
	            	</div>
	            </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form class="form-horizontal">
                    <div class="form-group row mb-0">
                        <div class="col-md-10">
                            <button class="btn btn-success"><i class="fa fa-save"></i> Save</button>
                            <button class="btn btn-default"><i class="fa fa-check text-success"></i> Save & Close</button>
                            <button class="btn btn-default"><i class="fa fa-times text-danger"></i> Cancel</button>
                        </div>
                        <div class="col-md-2 text-right">
                        	<a href="javascript:void(0);" class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>