<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <div class="card">
                <div class="card-body p-0">
                    <div class="nav-pages">    
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Published</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Trash</a>
                            </li>
                        </ul>

                        <form class="nav-search">
                            <div class="search-icon open-search">
                                <i class="fas fa-search"></i>
                            </div>
                            <div class="search-input">
                                <input type="search" placeholder="Search...">
                            </div>
                            <div class="search-icon close-search">
                                <i class="fas fa-times"></i>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div data-role="search-not-found" class="row justify-content-center">
        <div class="col-md-4 text-center p-3">
            <img src="./assets/img/nopost.png" class="img-fluid">
            <h3 class="mt-3">Whoops!</h3>
            <h6 class="text-danger mb-4">
                No pages found.
            </h6>
            <a href="<?php echo base_url('pages/form'); ?>" class="btn btn-primary btn-md">Add New Page</a>
        </div>
    </div>

    <div class="post-list">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="card" role="preloader">
                    <div class="card-body">
                        <div class="post-item">
                            <div class="post-item-detail">
                                <h1>
                                    <a href="#" class="content-placeholder d-inline-block mb-2">Post Title with Long Text</a>
                                </h1>
                                <div class="post-item-meta">
                                    <span class="post-time content-placeholder">Jan 5, 2018 3:51 PM</span>   
                                </div>
                            </div>
                            <div class="post-thumbnail">
                                <a href="#" class="content-placeholder">
                                    <img src="assets/img/nopost.png">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <div class="post-item">
                            <div class="post-item-detail">
                                <h1>
                                    <a href="#">Post Title with Long Text</a>
                                </h1>
                                <div class="post-item-meta">
                                    <span class="post-time">Jan 5, 2018 3:51 PM</span>   
                                </div>
                            </div>
                            <div class="post-thumbnail">
                                <a href="#">
                                    <img src="assets/img/nopost.png">
                                </a>
                            </div>
                            <div class="post-action">
                                <div class="dropdown">
                                    <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="<?php echo base_url('pages/form'); ?>">
                                            <i class="fas fa-pencil-alt"></i>
                                            Edit
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            <i class="fa fa-eye"></i>
                                            View
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            <i class="fas fa-chart-bar"></i>
                                            Stats
                                        </a>
                                        <a class="dropdown-item" href="#">
                                            <i class="fa fa-copy"></i>
                                            Copy
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">
                                            <i class="fa fa-trash"></i>
                                            Trash
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <div class="card nav-pagination">
                <div class="card-body">
                    <div class="row justify-content-between">
                        <div class="col-sm-6 col-md-6">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <a href="#" class="btn btn-default">Prev</a>
                                </div>
                                <div class="input-group-append">
                                    <a href="#" class="btn btn-default">Next</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-3">
                            <form>
                                <div class="input-group">
                                    <select class="custom-select">
                                        <option>1</option>
                                        <option>10</option>
                                        <option>30</option>
                                    </select>
            
                                    <div class="input-group-append">
                                        <button type="submit" class="btn btn-default">Go</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <p class="mb-0">Show <span>1</span> from <span>100</span></p>
                </div>
            </div>
        </div>
    </div>
</div>