<div class="page-place-detail">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-11">
                <div class="row justify-content-center mb-4">
                    <div class="col-auto">
                        <div class="media align-items-center">
                            <div class="avatar-80 mr-3">
                                <img src="<?= $company->image ?>" alt="">
                            </div>
                            <div class="media-body">
                                <h4 class="d-flex align-items-center">
                                    <span class="btn btn-default btn-xs mr-2 text-uppercase"><?= $company->category->title ?></span>
                                    <?= $company->name ?>
                                </h4>
                                <div class="d-block">
                                    <?php if ($company->metadata('email')): ?>
                                        <a href="mailto:<?= $company->metadata('email')->email ?>"
                                           class="btn btn-xs btn-default btn-icon"> <i
                                                class="fa fa-envelope"></i> <?= $company->metadata('email')->email ?>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($company->metadata('phone')): ?>
                                        <a href="tel:<?= $company->metadata('phone')->phone ?>"
                                           class="btn btn-xs btn-default btn-icon"> <i
                                                class="fa fa-phone"></i> <?= $company->metadata('phone')->phone ?> </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header p-0">
                        <div class="nav-pages">
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= base_url('/companies/overview/' . $company->id); ?>">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active"
                                       href="<?= base_url('/companies/overview/contacts/' . $company->id); ?>">Contacts</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="<?= base_url('companies/overview/products/' . $company->id); ?>">Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="<?= base_url('companies/overview/transactions/' . $company->id); ?>">Transactions</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="<?= base_url('companies/overview/members/' . $company->id); ?>">Members</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link"
                                       href="<?= base_url('companies/overview/users/' . $company->id); ?>">Users</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">
                                    Contact
                                </h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <a href="<?= base_url('/companies/overview/contacts/form/' . $company->id); ?>"
                                           class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?= current_url(); ?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <?php foreach($entries as $entry): ?>
                                                    <option value="<?php echo $entry; ?>" <?php echo ($get->entries == $entry ? 'selected' : ''); ?>><?php echo $entry; ?></option>
                                                <?php endforeach; ?>
                                                <option value="ALL" <?= ($get->entries ? (!is_numeric($get->entries) ? 'selected' : '') : '') ?>><?php echo $language->getLine('ALL') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Period</span>
                                            </div>
                                            <input class="form-control input-daterange-datepicker-empty" type="text" name="period" value="<?= ($get->period ? $get->period : '') ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Contact Name" value="<?= ($get->keyword ? $get->keyword : '') ?>" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="<?= base_url('companies/overview/contacts/'.$company->id) ?>">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- List -->
                <?php if ($contacts): ?>
                    <?php foreach ($contacts as $contact): ?>
                        <div class="card">
                            <div class="card-body">
                                <div class="row justify-content-between">
                                    <div class="col">
                                        <div class="row">
                                            <div class="col-md-auto">
                                                <div class="media align-items-center">
                                                    <div class="avatar-80 mr-3">
                                                        <img src="<?= $contact->image ?>" alt="">
                                                    </div>
                                                    <div class="media-body">
                                                        <h5><?= $contact->name ?>
                                                            &mdash; <?= $contact->job_title ?></h5>
                                                        <div class="d-block">
                                                            <?php if ($contact->emails): ?>
                                                                <a href="mailto:<?= $contact->emails ?>"
                                                                   class="btn btn-xs btn-default btn-icon mr-1 mb-1"> <i
                                                                        class="fa fa-envelope"></i> <?= $contact->emails ?>
                                                                </a>
                                                            <?php endif ?>
                                                            <?php if ($contact->mobiles): ?>
                                                                <a href="tel:<?= $contact->mobiles ?>"
                                                                   class="btn btn-xs btn-default btn-icon mr-1 mb-1"> <i
                                                                        class="fa fa-phone"></i> <?= $contact->mobiles ?>
                                                                </a>
                                                            <?php endif ?>


                                                        </div>
                                                        <div class="d-block">
                                                            <?php if ($contact->messengers): ?>
                                                                <?php foreach ($contact->messengers as $key => $value): ?>
                                                                    <a href="tel:<?= $value ?>"
                                                                       class="btn btn-xs btn-default btn-icon mr-1 mb-1">
                                                                        <i class="fab fa-<?= ($key == 'wechat' ? 'weixin' : $key) ?>"></i> <?= $value ?>
                                                                    </a>
                                                                <?php endforeach; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div class="d-block">
                                                            <?php if ($contact->socials): ?>
                                                                <?php foreach ($contact->socials as $key => $value): ?>
                                                                    <a href="<?= $value ?>"
                                                                       class="btn btn-xs btn-default btn-icon mr-1 mb-1">
                                                                        <i class="fab fa-<?= $key ?>"></i> <?= $value ?>
                                                                    </a>
                                                                <?php endforeach; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <div class="dropdown text-right">
                                            <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button"
                                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item"
                                                   href="<?php echo base_url('/companies/overview/contacts/form/' . $company->id, ['id_contact' => $contact->id]); ?>">
                                                    <i class="fas fa-pencil-alt"></i>
                                                    Edit
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                    <i class="fa fa-eye"></i>
                                                    View
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                    <i class="fas fa-chart-bar"></i>
                                                    Stats
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                    <i class="fa fa-copy"></i>
                                                    Copy
                                                </a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item"
                                                   href="<?= base_url('/companies/overview/contacts/delete/' . $contact->id) ?>">
                                                    <i class="fa fa-trash"></i>
                                                    Trash
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('companies/overview/contacts/'.$company->id, [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('companies/overview/contacts/'.$company->id, [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $contacts->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="period" value="<?= $get->period ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $contacts->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$contacts->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</div>
