Hai Budi,

<h3>Satu Langkah Lagi</h3>

Dengan ini kami memberitahukan bahwa kamu baru saja melakukan pembelian di platform CodePolitan. Adapun rincian pembeliannya adalah sebagai berikut:

Nama Produk	: Contoh
Harga : Rp 249.421
Tanggal	: 09/07/2020
Total Harga	: Rp 249.421

Untuk melanjutkan dan menyelesaikan pembelian, silakan melakukan pembayaran senilai Rp 249.421 ke rekening berikut ini:

Bank Mandiri Syariah Cabang Cimahi
A/N : PT. GOCART INDONESIA
No. Rekening : 7098174747

<h3>Konfirmasi</h3>

Setelah melakukan pembayaran, harap segera melakukan komfirmasi pembayaran melalui link berikut: https://www.get-gocart.com/payment/transfer/confirmation.

Untuk proses pembayaran manual melalui transfer bank, kami hanya melakukan pengecekan setelah kamu melakukan konfirmasi pembayaran. Oleh karena itu, pastikan untuk melakukan konfirmasi pembayaran setelah melakukan pembayaran.

Jika kamu mengalami kesulitan dalam melakukan konfirmasi pembayaran dan aktivasi akun, kamu bisa menghubungi kami melalui WhatsApp atau telpon melalui 087778086140. Kami akan dengan senang hati membantu. Terima kasih.

Salam,
GOCART INDONESIA