<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" action="<?php echo current_url(); ?>" enctype="multipart/form-data">
                    <div class="card">
                        <h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->title; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                    </div>
                    <div class="card">
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Parent</label>
                                        <select class="form-control select-dropdown" data-live-search="true" name="id_parent">
                                            <option value="1">Root</option>
                                            <option value="2">Electronic</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Title</label>
                                        <input class="form-control" type="text" name="title" value="" placeholder="" required="">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea name="description" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>