<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" action="<?php echo base_url('master/taxonomies/terms/form'); ?>" enctype="multipart/form-data">
                    <?php if ($post->id): ?>
                        <input type="hidden" name="id" value="<?= $post->id ?>">
                    <?php endif; ?>
                    <div class="card">
                        <h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->title; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                    </div>
                    <div class="card">
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" name="photo" class="dropify" data-default-file="<?= $post->photo ?>">
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" class="form-control" name="name" value="<?= $post->name ?>">
                                    </div>
                                    <div class="form-group">
                                        <label>Description</label>
                                        <textarea name="description" class="form-control"><?= $post->description ?></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="record_status" class="custom-select">
                                            <?php foreach ($masterdata_status as $key => $value): ?>
                                                <option value="<?= $key ?>"><?= $value ?></option>
                                            <?php endforeach ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>