<div class="page-system">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">Taxonomies Terms</h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <div class="dropdown">
                                            <a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Manage </a> 
                                            <div class="dropdown-menu"> 
                                                <a class="dropdown-item" href="<?=base_url('/master/taxonomies');?>"> Taxonomies </a> 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-auto">
                                        <a href="<?=base_url('/master/taxonomies/terms/form');?>" class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?=current_url();?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <?php foreach($entries as $entry): ?>
                                                    <option value="<?php echo $entry; ?>" <?php echo ($get->entries == $entry ? 'selected' : ''); ?>><?php echo $entry; ?></option>
                                                <?php endforeach; ?>
                                                <option value="ALL" <?= ($get->entries ? (!is_numeric($get->entries) ? 'selected' : '') : '') ?>><?php echo $language->getLine('ALL') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Terms Name" value="<?= ($get->keyword ? $get->keyword : '') ?>" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="<?= base_url('/master/taxonomies/terms') ?>">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered datatables-basic">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Terms</th>
                                    <th>Slug</th>
                                    <th>Description</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($terms): ?>
                                    <?php foreach ($terms as $term): ?>
                                    <tr>
                                        <td>
                                            <div class="avatar-30">
                                                <img src="<?= $term->photo ?>" alt="">
                                            </div>
                                        </td>
                                        <td><?= $term->name ?></td>
                                        <td><?= $term->slug ?></td>
                                        <td><?= $term->description ?></td>
                                        <td>
                                            <div class="btn-group btn-group-sm">
                                                <?php if ($term->record->status == 'PUBLISH'): ?>
                                                <a class="btn btn-default btn-sm" href="<?= base_url('/master/taxonomies/terms/form/'.$term->id) ?>" data-toggle="tooltip" title="Edit">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                    <?php if (!$term->check_taxonomies): ?>
                                                        <a class="btn btn-default btn-sm" href="<?= base_url('/master/taxonomies/terms/delete/'.$term->id) ?>" data-toggle="tooltip" title="Trash">
                                                            <i class="fa fa-trash"></i>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        </td>
                                    </tr>                                        
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php if ($terms): ?>
                                <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('master/taxonomies/terms', [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('master/taxonomies/terms', [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $terms->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="id_taxonomy_term" value="<?= $get->id_taxonomy_term ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $terms->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$terms->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>