<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" action="<?php echo base_url('site/appearance/sliders/form'); ?>" enctype="multipart/form-data">
                    <?php if ($post->id): ?>
                        <input type="hidden" name="id" value="<?= $post->id ?>">
                    <?php endif; ?>
                    <div class="card">
                        <h5 class="card-header d-flex justify-content-between align-items-center">
                            <?php echo $page->title; ?>

                            <div class="card-options">
                                <button type="button" class="btn btn-default btn-md" data-action="cancel">
                                    <?php echo $language->getLine('BTN_CANCEL'); ?>
                                </button>
                                <button type="submit" class="btn btn-primary btn-md">
                                    <?php echo $language->getLine('BTN_SAVE'); ?>
                                </button>
                            </div>
                        </h5>
                    </div>
                    <div class="card">
                        <div class="card-body" id="modal-form" data-title="<?php echo $page->header; ?>" data-action="<?php echo current_url(); ?>">
                            <div class="row">
                                <!-- <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" name="photo" class="dropify" data-default-file="<?= $post->image ?>">
                                    </div>
                                </div> -->
                                <div class="col-md">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Taxonomies Terms</label>
                                                <input type="hidden" name="id_taxonomy_term" value="<?= $term->id ?>">
                                                <input type="text" class="form-control" readonly value="<?= $term->name ?>">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Categories Parents</label>
                                                <select name="id_parent" class="form-control select-dropdown" data-live-search="true">
                                                    <option value="0" selected>ROOT</option>
                                                    <?php foreach ($parents as $parent): ?>
                                                        <?php if ($post->id == $parent->id): ?>
                                                            <?php continue; ?>
                                                        <?php endif ?>
                                                        <option value="<?= $parent->id ?>" <?= ($post->id_parent == $parent->id ? 'selected' : '') ?>><?= $parent->name ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Categories Name</label>
                                        <input type="text" class="form-control" name="name" value="<?= $post->name ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>