<div class="page-system">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">
                                    Sliders
                                </h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <a href="<?=base_url('site/appearance/sliders/form');?>" class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?=current_url();?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <?php foreach($entries as $entry): ?>
                                                    <option value="<?php echo $entry; ?>" <?php echo ($get->entries == $entry ? 'selected' : ''); ?>><?php echo $entry; ?></option>
                                                <?php endforeach; ?>
                                                <option value="ALL" <?= ($get->entries ? (!is_numeric($get->entries) ? 'selected' : '') : '') ?>><?php echo $language->getLine('ALL') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Taxonomy Name" value="<?= ($get->keyword ? $get->keyword : '') ?>" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="<?= base_url('site/appearance/sliders') ?>">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered datatables-basic">
                            <thead>
                                <tr>
                                    <th>Categories</th>
                                    <th>Total Sliders</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if ($taxonomies): ?>
                                    <?php foreach ($taxonomies as $taxonomy): ?>
                                        <tr>
                                            <td><?= $taxonomy->name ?></td>
                                            <td><?= $taxonomy->total_sliders ?></td>
                                            <td>
                                                <div class="btn-group btn-group-sm">
                                                    <a class="btn btn-default btn-sm" href="<?= base_url('site/appearance/sliders/form/'.$taxonomy->id); ?>" data-toggle="tooltip" title="Edit">
                                                        <i class="fas fa-pencil-alt"></i>
                                                    </a>
                                                    <a class="btn btn-default btn-sm" href="<?= base_url('site/appearance/sliders/detail/'.$taxonomy->id); ?>" data-toggle="tooltip" title="View">
                                                        <i class="fa fa-eye"></i>
                                                    </a>
                                                    <!-- <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Stats">
                                                        <i class="fas fa-chart-bar"></i>
                                                    </a>
                                                    <a class="btn btn-default btn-sm" href="#" data-toggle="tooltip" title="Copy">
                                                        <i class="fa fa-copy"></i>
                                                    </a> -->
                                                    <?php if (!$taxonomy->check_child): ?>
                                                        <a class="btn btn-default btn-sm" href="<?= current_url(); ?>" data-id="<?= $taxonomy->id ?>" data-action="delete" data-toggle="tooltip" title="Trash">
                                                            <i class="fa fa-trash"></i>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <?php if ($taxonomies): ?>
            <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('site/appearance/sliders', [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('site/appearance/sliders', [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $taxonomies->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $taxonomies->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$taxonomies->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
        <?php endif ?>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(document).on('click', '[data-action="delete"]', function(e){
            e.preventDefault();
            var id = $(this).data('id');
            let domain_url = "<?= domain_url('/taxonomies/delete', null, 'api') ?>";
            $.ajax({
                url: domain_url,
                type: "POST",
                data:"id="+id,
                success: function(result){
                    window.location.href =  espresso.helpers.url.base("site/appearance/sliders");
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
    });
</script>