<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="nav-pages">
                            <?php echo $tabs; ?>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">

                            </div>
                            <div class="col-auto">
                                <a href="<?= base_url('system/settings/modules/form'); ?>" class="btn btn-primary">
                                    <?php echo language('ADD_NEW_MODULES'); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body with-table">
                        <div class="table-responsive">
                            <table class="table table-striped valign-middle">
                                <thead>
                                <tr>
                                    <th>Namespace</th>
                                    <th>Type</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/15">
                                            App\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">APP</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/15">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/15"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/1">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">APP</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/1">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/1"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/3">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\BuildingManagement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/3">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/3"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/4">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Company\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/4">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/4"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/5">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Finance\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/5">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/5"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/6">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Goods\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/6">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/6"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/7">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\HumanResource\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/7">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/7"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/8">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Learning\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/8">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/8"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/9">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\MasterData\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/9">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/9"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/10">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Office\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/10">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/10"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/11">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Personal\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/11">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/11"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/12">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Scrum\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/12">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/12"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/13">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Shuttle\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/13">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/13"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/14">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\System\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/14">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/14"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/37">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\FixedAssets\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/37">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/37"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/38">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Customers\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/38">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/38"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/39">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Companies\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/39">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/39"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/43">
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Quiz\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/43">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/43"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/2">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\AssetsManagement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/2">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/2"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/16">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Administrator\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/16">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/16"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/17">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\AssetsManagement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/17">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/17"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/18">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\BuildingManagement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/18">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/18"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/19">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Company\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/19">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/19"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/20">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Customers\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/20">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/20"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/21">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Documentations\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/21">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/21"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/22">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Finance\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/22">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/22"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/23">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            Goods\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/23">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/23"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/24">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Helpdesk\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/24">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/24"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/25">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\HumanResource\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/25">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/25"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/26">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Learning\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/26">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/26"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/27">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Office\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/27">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/27"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/28">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Personal\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/28">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/28"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/29">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Shuttle\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/29">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/29"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/30">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Goods\Backup\Inventory\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/30">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/30"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/31">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Goods\Backup\Procurement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/31">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/31"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/32">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Api\Modules\Goods\Backup\Suppliers\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/32">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/32"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/33">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            Procurement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/33">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/33"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/34">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            Suppliers\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/34">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/34"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/35">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\FixedAssets\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/35">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/35"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/36">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Tasks\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/36">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/36"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/40">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Companies\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/40">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/40"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/41">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\ProjectManagement\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/41">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/41"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/42">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Quiz\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/42">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/42"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/44">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Agenda\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/44">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/44"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="https://itsynergy.mandayamedical.group/administrator/modules/detail/45">
                                            &nbsp;&nbsp;&nbsp;&nbsp; ↳
                                            App\Modules\Documents\ </a>
                                    </td>
                                    <td>
                                        <span class="text-uppercase badge badge-info">MODULE</span>
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/form/45">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a class="btn btn-default btn-sm"
                                               href="https://itsynergy.mandayamedical.group/administrator/modules/delete/45"
                                               data-action="delete">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>