<div class="page-sliders">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-11">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-auto">
                                <h5 class="mb-0">
                                    <?= $taxonomy->name ?>
                                </h5>
                            </div>
                            <div class="col-md-8">
                                <div class="form-row align-items-center justify-content-end">
                                    <div class="col-md-auto">
                                        <a href="<?=base_url('site/appearance/sliders/detail/form', ['id_taxonomy' => $taxonomy->id ]);?>" class="btn btn-primary">Add</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0">
                        <form action="<?=current_url();?>">
                            <div class="form-row align-items-center">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Entries</span>
                                            </div>
                                            <select name="entries" class="form-control custom-select">
                                                <?php foreach($entries as $entry): ?>
                                                    <option value="<?php echo $entry; ?>" <?php echo ($get->entries == $entry ? 'selected' : ''); ?>><?php echo $entry; ?></option>
                                                <?php endforeach; ?>
                                                <option value="ALL" <?= ($get->entries ? (!is_numeric($get->entries) ? 'selected' : '') : '') ?>><?php echo $language->getLine('ALL') ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">Period</span>
                                            </div>
                                            <input class="form-control input-daterange-datepicker-empty" type="text" placeholder="Start - Finish Publishing" name="period" value="<?= ($get->period ? $get->period : '') ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Slider Title" value="<?= ($get->keyword ? $get->keyword : '') ?>" name="keyword">
                                    </div>
                                </div>
                                <div class="col-md text-right">
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Filter</button>
                                        <a class="btn btn-default" href="#">Reset</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <?php if ($sliders): ?>
                    <?php foreach ($sliders as $slider): ?>
                        <div class="card">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-auto">
                                        <div class="slide-img">
                                            <img src="<?= $slider->image ?>" alt="" class="w-100">
                                        </div>
                                    </div>
                                    <div class="col-md">
                                        <div class="row">
                                            <div class="col-10">
                                                <div class="form-group">
                                                    <label>Title</label>
                                                    <p><?= $slider->title ?></p>
                                                </div>
                                                <div class="form-group">
                                                    <label>Description</label>
                                                    <p><?= $slider->content ?></p>
                                                </div>
                                            </div>
                                            <div class="col-2 text-right">
                                                <div class="dropdown">
                                                    <a class="dropdown-toggle dropdown-ellipsis" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <!-- <a class="dropdown-item" href="#" data-fancybox>
                                                            <i class="fa fa-eye"></i>
                                                            View
                                                        </a> -->
                                                        <a class="dropdown-item" href="<?php echo base_url('site/appearance/sliders/detail/form/'.$slider->id, ['id_taxonomy' => $taxonomy->id]); ?>">
                                                            <i class="fas fa-pencil-alt"></i>
                                                            Edit
                                                        </a>
                                                        <div class="dropdown-divider"></div>
                                                        <a class="dropdown-item" href="<?= current_url(); ?>" data-id="<?= $slider->id ?>" data-action="delete">
                                                            <i class="fa fa-trash"></i>
                                                            Trash
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
            <div class="card nav-pagination">
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-sm-6 col-md-6">
                                    <div class="btn-group">
                                        <a href="<?=base_url('site/appearance/sliders/detail/'.$taxonomy->id, [
                                        'page' => input()->get('page') - 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=($page = input()->get('page')) <= 1 ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('PREV'); ?>
                                        </a>
                                        <?php if (($page = input()->get('page')) == 0):?>
                                            <?php $page = $page + 1; ?>
                                        <?php endif; ?>
                                        <a href="<?=base_url('site/appearance/sliders/detail/'.$taxonomy->id, [
                                        'page' => $page + 1,
                                        'entries' => $get->entries,
                                        'period' => $get->period,
                                        'keyword' => $get->keyword,
                                        ]); ?>" class="btn btn-default <?=$page >= $sliders->info->num_pages ? 'disabled' : ''; ?>" >
                                            <?php echo $language->getLine('NEXT'); ?>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-sm-4 col-md-3">
                                    <form action="<?=current_url(); ?>" method="get">
                                        <input type="hidden" name="entries" value="<?= $get->entries ?>">
                                        <input type="hidden" name="period" value="<?= $get->period ?>">
                                        <input type="hidden" name="keyword" value="<?= $get->keyword ?>">
                                        <div class="input-group">
                                            <select class="custom-select select2" name="page" method="get">
                                                <?php for ($i = 1; $i <= $sliders->info->num_pages; ++$i):?>
                                                    <option value="<?=$i; ?>" <?= input()->get('page') == $i ? 'selected' : '' ?>><?=$i; ?></option>
                                                <?php endfor; ?>
                                            </select>

                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-primary" <?= !$sliders->info->num_pages ? 'disabled' : '' ?>>Go</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
        
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(document).on('click', '[data-action="delete"]', function(e){
            e.preventDefault();
            var id = $(this).data('id');
            let id_taxonomy = "<?= $taxonomy->id ?>";
            let domain_url = "<?= domain_url('/sliders/delete', null, 'api') ?>";
            $.ajax({
                url: domain_url,
                type: "POST",
                data:"id="+id,
                success: function(result){
                    window.location.href =  espresso.helpers.url.base("site/appearance/sliders/detail/" + id_taxonomy);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
    });
</script>